// Code generated by ent, DO NOT EDIT.

package pathplan

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pathplan type in the database.
	Label = "path_plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlanKey holds the string denoting the plan_key field in the database.
	FieldPlanKey = "plan_key"
	// FieldTotalDist holds the string denoting the total_dist field in the database.
	FieldTotalDist = "total_dist"
	// FieldOrderJSON holds the string denoting the order_json field in the database.
	FieldOrderJSON = "order_json"
	// FieldSegmentsJSON holds the string denoting the segments_json field in the database.
	FieldSegmentsJSON = "segments_json"
	// FieldWarehouseID holds the string denoting the warehouse_id field in the database.
	FieldWarehouseID = "warehouse_id"
	// EdgeWarehouse holds the string denoting the warehouse edge name in mutations.
	EdgeWarehouse = "warehouse"
	// Table holds the table name of the pathplan in the database.
	Table = "path_plans"
	// WarehouseTable is the table that holds the warehouse relation/edge.
	WarehouseTable = "path_plans"
	// WarehouseInverseTable is the table name for the Warehouse entity.
	// It exists in this package in order to avoid circular dependency with the "warehouse" package.
	WarehouseInverseTable = "warehouses"
	// WarehouseColumn is the table column denoting the warehouse relation/edge.
	WarehouseColumn = "warehouse_id"
)

// Columns holds all SQL columns for pathplan fields.
var Columns = []string{
	FieldID,
	FieldPlanKey,
	FieldTotalDist,
	FieldOrderJSON,
	FieldSegmentsJSON,
	FieldWarehouseID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTotalDist holds the default value on creation for the "total_dist" field.
	DefaultTotalDist int
	// DefaultOrderJSON holds the default value on creation for the "order_json" field.
	DefaultOrderJSON string
	// DefaultSegmentsJSON holds the default value on creation for the "segments_json" field.
	DefaultSegmentsJSON string
)

// OrderOption defines the ordering options for the PathPlan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlanKey orders the results by the plan_key field.
func ByPlanKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanKey, opts...).ToFunc()
}

// ByTotalDist orders the results by the total_dist field.
func ByTotalDist(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalDist, opts...).ToFunc()
}

// ByOrderJSON orders the results by the order_json field.
func ByOrderJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderJSON, opts...).ToFunc()
}

// BySegmentsJSON orders the results by the segments_json field.
func BySegmentsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSegmentsJSON, opts...).ToFunc()
}

// ByWarehouseID orders the results by the warehouse_id field.
func ByWarehouseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWarehouseID, opts...).ToFunc()
}

// ByWarehouseField orders the results by warehouse field.
func ByWarehouseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWarehouseStep(), sql.OrderByField(field, opts...))
	}
}
func newWarehouseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WarehouseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WarehouseTable, WarehouseColumn),
	)
}
