// Code generated by ent, DO NOT EDIT.

package pathplan

import (
	"warehouse/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldLTE(FieldID, id))
}

// PlanKey applies equality check predicate on the "plan_key" field. It's identical to PlanKeyEQ.
func PlanKey(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEQ(FieldPlanKey, v))
}

// TotalDist applies equality check predicate on the "total_dist" field. It's identical to TotalDistEQ.
func TotalDist(v int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEQ(FieldTotalDist, v))
}

// OrderJSON applies equality check predicate on the "order_json" field. It's identical to OrderJSONEQ.
func OrderJSON(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEQ(FieldOrderJSON, v))
}

// SegmentsJSON applies equality check predicate on the "segments_json" field. It's identical to SegmentsJSONEQ.
func SegmentsJSON(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEQ(FieldSegmentsJSON, v))
}

// WarehouseID applies equality check predicate on the "warehouse_id" field. It's identical to WarehouseIDEQ.
func WarehouseID(v int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEQ(FieldWarehouseID, v))
}

// PlanKeyEQ applies the EQ predicate on the "plan_key" field.
func PlanKeyEQ(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEQ(FieldPlanKey, v))
}

// PlanKeyNEQ applies the NEQ predicate on the "plan_key" field.
func PlanKeyNEQ(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNEQ(FieldPlanKey, v))
}

// PlanKeyIn applies the In predicate on the "plan_key" field.
func PlanKeyIn(vs ...string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldIn(FieldPlanKey, vs...))
}

// PlanKeyNotIn applies the NotIn predicate on the "plan_key" field.
func PlanKeyNotIn(vs ...string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNotIn(FieldPlanKey, vs...))
}

// PlanKeyGT applies the GT predicate on the "plan_key" field.
func PlanKeyGT(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldGT(FieldPlanKey, v))
}

// PlanKeyGTE applies the GTE predicate on the "plan_key" field.
func PlanKeyGTE(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldGTE(FieldPlanKey, v))
}

// PlanKeyLT applies the LT predicate on the "plan_key" field.
func PlanKeyLT(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldLT(FieldPlanKey, v))
}

// PlanKeyLTE applies the LTE predicate on the "plan_key" field.
func PlanKeyLTE(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldLTE(FieldPlanKey, v))
}

// PlanKeyContains applies the Contains predicate on the "plan_key" field.
func PlanKeyContains(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldContains(FieldPlanKey, v))
}

// PlanKeyHasPrefix applies the HasPrefix predicate on the "plan_key" field.
func PlanKeyHasPrefix(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldHasPrefix(FieldPlanKey, v))
}

// PlanKeyHasSuffix applies the HasSuffix predicate on the "plan_key" field.
func PlanKeyHasSuffix(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldHasSuffix(FieldPlanKey, v))
}

// PlanKeyEqualFold applies the EqualFold predicate on the "plan_key" field.
func PlanKeyEqualFold(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEqualFold(FieldPlanKey, v))
}

// PlanKeyContainsFold applies the ContainsFold predicate on the "plan_key" field.
func PlanKeyContainsFold(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldContainsFold(FieldPlanKey, v))
}

// TotalDistEQ applies the EQ predicate on the "total_dist" field.
func TotalDistEQ(v int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEQ(FieldTotalDist, v))
}

// TotalDistNEQ applies the NEQ predicate on the "total_dist" field.
func TotalDistNEQ(v int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNEQ(FieldTotalDist, v))
}

// TotalDistIn applies the In predicate on the "total_dist" field.
func TotalDistIn(vs ...int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldIn(FieldTotalDist, vs...))
}

// TotalDistNotIn applies the NotIn predicate on the "total_dist" field.
func TotalDistNotIn(vs ...int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNotIn(FieldTotalDist, vs...))
}

// TotalDistGT applies the GT predicate on the "total_dist" field.
func TotalDistGT(v int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldGT(FieldTotalDist, v))
}

// TotalDistGTE applies the GTE predicate on the "total_dist" field.
func TotalDistGTE(v int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldGTE(FieldTotalDist, v))
}

// TotalDistLT applies the LT predicate on the "total_dist" field.
func TotalDistLT(v int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldLT(FieldTotalDist, v))
}

// TotalDistLTE applies the LTE predicate on the "total_dist" field.
func TotalDistLTE(v int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldLTE(FieldTotalDist, v))
}

// OrderJSONEQ applies the EQ predicate on the "order_json" field.
func OrderJSONEQ(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEQ(FieldOrderJSON, v))
}

// OrderJSONNEQ applies the NEQ predicate on the "order_json" field.
func OrderJSONNEQ(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNEQ(FieldOrderJSON, v))
}

// OrderJSONIn applies the In predicate on the "order_json" field.
func OrderJSONIn(vs ...string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldIn(FieldOrderJSON, vs...))
}

// OrderJSONNotIn applies the NotIn predicate on the "order_json" field.
func OrderJSONNotIn(vs ...string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNotIn(FieldOrderJSON, vs...))
}

// OrderJSONGT applies the GT predicate on the "order_json" field.
func OrderJSONGT(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldGT(FieldOrderJSON, v))
}

// OrderJSONGTE applies the GTE predicate on the "order_json" field.
func OrderJSONGTE(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldGTE(FieldOrderJSON, v))
}

// OrderJSONLT applies the LT predicate on the "order_json" field.
func OrderJSONLT(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldLT(FieldOrderJSON, v))
}

// OrderJSONLTE applies the LTE predicate on the "order_json" field.
func OrderJSONLTE(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldLTE(FieldOrderJSON, v))
}

// OrderJSONContains applies the Contains predicate on the "order_json" field.
func OrderJSONContains(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldContains(FieldOrderJSON, v))
}

// OrderJSONHasPrefix applies the HasPrefix predicate on the "order_json" field.
func OrderJSONHasPrefix(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldHasPrefix(FieldOrderJSON, v))
}

// OrderJSONHasSuffix applies the HasSuffix predicate on the "order_json" field.
func OrderJSONHasSuffix(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldHasSuffix(FieldOrderJSON, v))
}

// OrderJSONEqualFold applies the EqualFold predicate on the "order_json" field.
func OrderJSONEqualFold(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEqualFold(FieldOrderJSON, v))
}

// OrderJSONContainsFold applies the ContainsFold predicate on the "order_json" field.
func OrderJSONContainsFold(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldContainsFold(FieldOrderJSON, v))
}

// SegmentsJSONEQ applies the EQ predicate on the "segments_json" field.
func SegmentsJSONEQ(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEQ(FieldSegmentsJSON, v))
}

// SegmentsJSONNEQ applies the NEQ predicate on the "segments_json" field.
func SegmentsJSONNEQ(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNEQ(FieldSegmentsJSON, v))
}

// SegmentsJSONIn applies the In predicate on the "segments_json" field.
func SegmentsJSONIn(vs ...string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldIn(FieldSegmentsJSON, vs...))
}

// SegmentsJSONNotIn applies the NotIn predicate on the "segments_json" field.
func SegmentsJSONNotIn(vs ...string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNotIn(FieldSegmentsJSON, vs...))
}

// SegmentsJSONGT applies the GT predicate on the "segments_json" field.
func SegmentsJSONGT(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldGT(FieldSegmentsJSON, v))
}

// SegmentsJSONGTE applies the GTE predicate on the "segments_json" field.
func SegmentsJSONGTE(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldGTE(FieldSegmentsJSON, v))
}

// SegmentsJSONLT applies the LT predicate on the "segments_json" field.
func SegmentsJSONLT(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldLT(FieldSegmentsJSON, v))
}

// SegmentsJSONLTE applies the LTE predicate on the "segments_json" field.
func SegmentsJSONLTE(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldLTE(FieldSegmentsJSON, v))
}

// SegmentsJSONContains applies the Contains predicate on the "segments_json" field.
func SegmentsJSONContains(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldContains(FieldSegmentsJSON, v))
}

// SegmentsJSONHasPrefix applies the HasPrefix predicate on the "segments_json" field.
func SegmentsJSONHasPrefix(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldHasPrefix(FieldSegmentsJSON, v))
}

// SegmentsJSONHasSuffix applies the HasSuffix predicate on the "segments_json" field.
func SegmentsJSONHasSuffix(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldHasSuffix(FieldSegmentsJSON, v))
}

// SegmentsJSONEqualFold applies the EqualFold predicate on the "segments_json" field.
func SegmentsJSONEqualFold(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEqualFold(FieldSegmentsJSON, v))
}

// SegmentsJSONContainsFold applies the ContainsFold predicate on the "segments_json" field.
func SegmentsJSONContainsFold(v string) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldContainsFold(FieldSegmentsJSON, v))
}

// WarehouseIDEQ applies the EQ predicate on the "warehouse_id" field.
func WarehouseIDEQ(v int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldEQ(FieldWarehouseID, v))
}

// WarehouseIDNEQ applies the NEQ predicate on the "warehouse_id" field.
func WarehouseIDNEQ(v int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNEQ(FieldWarehouseID, v))
}

// WarehouseIDIn applies the In predicate on the "warehouse_id" field.
func WarehouseIDIn(vs ...int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldIn(FieldWarehouseID, vs...))
}

// WarehouseIDNotIn applies the NotIn predicate on the "warehouse_id" field.
func WarehouseIDNotIn(vs ...int) predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNotIn(FieldWarehouseID, vs...))
}

// WarehouseIDIsNil applies the IsNil predicate on the "warehouse_id" field.
func WarehouseIDIsNil() predicate.PathPlan {
	return predicate.PathPlan(sql.FieldIsNull(FieldWarehouseID))
}

// WarehouseIDNotNil applies the NotNil predicate on the "warehouse_id" field.
func WarehouseIDNotNil() predicate.PathPlan {
	return predicate.PathPlan(sql.FieldNotNull(FieldWarehouseID))
}

// HasWarehouse applies the HasEdge predicate on the "warehouse" edge.
func HasWarehouse() predicate.PathPlan {
	return predicate.PathPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WarehouseTable, WarehouseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWarehouseWith applies the HasEdge predicate on the "warehouse" edge with a given conditions (other predicates).
func HasWarehouseWith(preds ...predicate.Warehouse) predicate.PathPlan {
	return predicate.PathPlan(func(s *sql.Selector) {
		step := newWarehouseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PathPlan) predicate.PathPlan {
	return predicate.PathPlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PathPlan) predicate.PathPlan {
	return predicate.PathPlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PathPlan) predicate.PathPlan {
	return predicate.PathPlan(sql.NotPredicates(p))
}
