// Code generated by ent, DO NOT EDIT.

package warehouse

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the warehouse type in the database.
	Label = "warehouse"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldStoreID holds the string denoting the store_id field in the database.
	FieldStoreID = "store_id"
	// EdgeStore holds the string denoting the store edge name in mutations.
	EdgeStore = "store"
	// EdgeShelves holds the string denoting the shelves edge name in mutations.
	EdgeShelves = "shelves"
	// EdgePathPlans holds the string denoting the path_plans edge name in mutations.
	EdgePathPlans = "path_plans"
	// EdgeLandmarks holds the string denoting the landmarks edge name in mutations.
	EdgeLandmarks = "landmarks"
	// Table holds the table name of the warehouse in the database.
	Table = "warehouses"
	// StoreTable is the table that holds the store relation/edge.
	StoreTable = "warehouses"
	// StoreInverseTable is the table name for the Store entity.
	// It exists in this package in order to avoid circular dependency with the "store" package.
	StoreInverseTable = "stores"
	// StoreColumn is the table column denoting the store relation/edge.
	StoreColumn = "store_id"
	// ShelvesTable is the table that holds the shelves relation/edge.
	ShelvesTable = "shelves"
	// ShelvesInverseTable is the table name for the Shelf entity.
	// It exists in this package in order to avoid circular dependency with the "shelf" package.
	ShelvesInverseTable = "shelves"
	// ShelvesColumn is the table column denoting the shelves relation/edge.
	ShelvesColumn = "warehouse_id"
	// PathPlansTable is the table that holds the path_plans relation/edge.
	PathPlansTable = "path_plans"
	// PathPlansInverseTable is the table name for the PathPlan entity.
	// It exists in this package in order to avoid circular dependency with the "pathplan" package.
	PathPlansInverseTable = "path_plans"
	// PathPlansColumn is the table column denoting the path_plans relation/edge.
	PathPlansColumn = "warehouse_id"
	// LandmarksTable is the table that holds the landmarks relation/edge.
	LandmarksTable = "landmarks"
	// LandmarksInverseTable is the table name for the Landmark entity.
	// It exists in this package in order to avoid circular dependency with the "landmark" package.
	LandmarksInverseTable = "landmarks"
	// LandmarksColumn is the table column denoting the landmarks relation/edge.
	LandmarksColumn = "warehouse_id"
)

// Columns holds all SQL columns for warehouse fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCode,
	FieldStoreID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultCode holds the default value on creation for the "code" field.
	DefaultCode string
)

// OrderOption defines the ordering options for the Warehouse queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByStoreID orders the results by the store_id field.
func ByStoreID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoreID, opts...).ToFunc()
}

// ByStoreField orders the results by store field.
func ByStoreField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStoreStep(), sql.OrderByField(field, opts...))
	}
}

// ByShelvesCount orders the results by shelves count.
func ByShelvesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newShelvesStep(), opts...)
	}
}

// ByShelves orders the results by shelves terms.
func ByShelves(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newShelvesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPathPlansCount orders the results by path_plans count.
func ByPathPlansCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPathPlansStep(), opts...)
	}
}

// ByPathPlans orders the results by path_plans terms.
func ByPathPlans(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPathPlansStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLandmarksCount orders the results by landmarks count.
func ByLandmarksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLandmarksStep(), opts...)
	}
}

// ByLandmarks orders the results by landmarks terms.
func ByLandmarks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLandmarksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStoreStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StoreInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StoreTable, StoreColumn),
	)
}
func newShelvesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ShelvesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ShelvesTable, ShelvesColumn),
	)
}
func newPathPlansStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PathPlansInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PathPlansTable, PathPlansColumn),
	)
}
func newLandmarksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LandmarksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LandmarksTable, LandmarksColumn),
	)
}
