// Code generated by ent, DO NOT EDIT.

package shelf

import (
	"warehouse/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Shelf {
	return predicate.Shelf(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Shelf {
	return predicate.Shelf(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Shelf {
	return predicate.Shelf(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Shelf {
	return predicate.Shelf(sql.FieldLTE(FieldID, id))
}

// ShelfNumber applies equality check predicate on the "shelf_number" field. It's identical to ShelfNumberEQ.
func ShelfNumber(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldShelfNumber, v))
}

// Bold applies equality check predicate on the "bold" field. It's identical to BoldEQ.
func Bold(v bool) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldBold, v))
}

// Col applies equality check predicate on the "col" field. It's identical to ColEQ.
func Col(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldCol, v))
}

// Row applies equality check predicate on the "row" field. It's identical to RowEQ.
func Row(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldRow, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldHeight, v))
}

// IsHorizontal applies equality check predicate on the "is_horizontal" field. It's identical to IsHorizontalEQ.
func IsHorizontal(v bool) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldIsHorizontal, v))
}

// IsVerticalLong applies equality check predicate on the "is_vertical_long" field. It's identical to IsVerticalLongEQ.
func IsVerticalLong(v bool) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldIsVerticalLong, v))
}

// WarehouseID applies equality check predicate on the "warehouse_id" field. It's identical to WarehouseIDEQ.
func WarehouseID(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldWarehouseID, v))
}

// ShelfNumberEQ applies the EQ predicate on the "shelf_number" field.
func ShelfNumberEQ(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldShelfNumber, v))
}

// ShelfNumberNEQ applies the NEQ predicate on the "shelf_number" field.
func ShelfNumberNEQ(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNEQ(FieldShelfNumber, v))
}

// ShelfNumberIn applies the In predicate on the "shelf_number" field.
func ShelfNumberIn(vs ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldIn(FieldShelfNumber, vs...))
}

// ShelfNumberNotIn applies the NotIn predicate on the "shelf_number" field.
func ShelfNumberNotIn(vs ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNotIn(FieldShelfNumber, vs...))
}

// ShelfNumberGT applies the GT predicate on the "shelf_number" field.
func ShelfNumberGT(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldGT(FieldShelfNumber, v))
}

// ShelfNumberGTE applies the GTE predicate on the "shelf_number" field.
func ShelfNumberGTE(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldGTE(FieldShelfNumber, v))
}

// ShelfNumberLT applies the LT predicate on the "shelf_number" field.
func ShelfNumberLT(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldLT(FieldShelfNumber, v))
}

// ShelfNumberLTE applies the LTE predicate on the "shelf_number" field.
func ShelfNumberLTE(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldLTE(FieldShelfNumber, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.Shelf {
	return predicate.Shelf(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.Shelf {
	return predicate.Shelf(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.Shelf {
	return predicate.Shelf(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.Shelf {
	return predicate.Shelf(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.Shelf {
	return predicate.Shelf(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.Shelf {
	return predicate.Shelf(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.Shelf {
	return predicate.Shelf(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.Shelf {
	return predicate.Shelf(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.Shelf {
	return predicate.Shelf(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.Shelf {
	return predicate.Shelf(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.Shelf {
	return predicate.Shelf(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.Shelf {
	return predicate.Shelf(sql.FieldContainsFold(FieldLabel, v))
}

// BoldEQ applies the EQ predicate on the "bold" field.
func BoldEQ(v bool) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldBold, v))
}

// BoldNEQ applies the NEQ predicate on the "bold" field.
func BoldNEQ(v bool) predicate.Shelf {
	return predicate.Shelf(sql.FieldNEQ(FieldBold, v))
}

// ColEQ applies the EQ predicate on the "col" field.
func ColEQ(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldCol, v))
}

// ColNEQ applies the NEQ predicate on the "col" field.
func ColNEQ(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNEQ(FieldCol, v))
}

// ColIn applies the In predicate on the "col" field.
func ColIn(vs ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldIn(FieldCol, vs...))
}

// ColNotIn applies the NotIn predicate on the "col" field.
func ColNotIn(vs ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNotIn(FieldCol, vs...))
}

// ColGT applies the GT predicate on the "col" field.
func ColGT(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldGT(FieldCol, v))
}

// ColGTE applies the GTE predicate on the "col" field.
func ColGTE(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldGTE(FieldCol, v))
}

// ColLT applies the LT predicate on the "col" field.
func ColLT(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldLT(FieldCol, v))
}

// ColLTE applies the LTE predicate on the "col" field.
func ColLTE(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldLTE(FieldCol, v))
}

// RowEQ applies the EQ predicate on the "row" field.
func RowEQ(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldRow, v))
}

// RowNEQ applies the NEQ predicate on the "row" field.
func RowNEQ(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNEQ(FieldRow, v))
}

// RowIn applies the In predicate on the "row" field.
func RowIn(vs ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldIn(FieldRow, vs...))
}

// RowNotIn applies the NotIn predicate on the "row" field.
func RowNotIn(vs ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNotIn(FieldRow, vs...))
}

// RowGT applies the GT predicate on the "row" field.
func RowGT(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldGT(FieldRow, v))
}

// RowGTE applies the GTE predicate on the "row" field.
func RowGTE(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldGTE(FieldRow, v))
}

// RowLT applies the LT predicate on the "row" field.
func RowLT(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldLT(FieldRow, v))
}

// RowLTE applies the LTE predicate on the "row" field.
func RowLTE(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldLTE(FieldRow, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldLTE(FieldWidth, v))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldLTE(FieldHeight, v))
}

// IsHorizontalEQ applies the EQ predicate on the "is_horizontal" field.
func IsHorizontalEQ(v bool) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldIsHorizontal, v))
}

// IsHorizontalNEQ applies the NEQ predicate on the "is_horizontal" field.
func IsHorizontalNEQ(v bool) predicate.Shelf {
	return predicate.Shelf(sql.FieldNEQ(FieldIsHorizontal, v))
}

// IsVerticalLongEQ applies the EQ predicate on the "is_vertical_long" field.
func IsVerticalLongEQ(v bool) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldIsVerticalLong, v))
}

// IsVerticalLongNEQ applies the NEQ predicate on the "is_vertical_long" field.
func IsVerticalLongNEQ(v bool) predicate.Shelf {
	return predicate.Shelf(sql.FieldNEQ(FieldIsVerticalLong, v))
}

// WarehouseIDEQ applies the EQ predicate on the "warehouse_id" field.
func WarehouseIDEQ(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldEQ(FieldWarehouseID, v))
}

// WarehouseIDNEQ applies the NEQ predicate on the "warehouse_id" field.
func WarehouseIDNEQ(v int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNEQ(FieldWarehouseID, v))
}

// WarehouseIDIn applies the In predicate on the "warehouse_id" field.
func WarehouseIDIn(vs ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldIn(FieldWarehouseID, vs...))
}

// WarehouseIDNotIn applies the NotIn predicate on the "warehouse_id" field.
func WarehouseIDNotIn(vs ...int) predicate.Shelf {
	return predicate.Shelf(sql.FieldNotIn(FieldWarehouseID, vs...))
}

// WarehouseIDIsNil applies the IsNil predicate on the "warehouse_id" field.
func WarehouseIDIsNil() predicate.Shelf {
	return predicate.Shelf(sql.FieldIsNull(FieldWarehouseID))
}

// WarehouseIDNotNil applies the NotNil predicate on the "warehouse_id" field.
func WarehouseIDNotNil() predicate.Shelf {
	return predicate.Shelf(sql.FieldNotNull(FieldWarehouseID))
}

// HasWarehouse applies the HasEdge predicate on the "warehouse" edge.
func HasWarehouse() predicate.Shelf {
	return predicate.Shelf(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WarehouseTable, WarehouseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWarehouseWith applies the HasEdge predicate on the "warehouse" edge with a given conditions (other predicates).
func HasWarehouseWith(preds ...predicate.Warehouse) predicate.Shelf {
	return predicate.Shelf(func(s *sql.Selector) {
		step := newWarehouseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUnits applies the HasEdge predicate on the "units" edge.
func HasUnits() predicate.Shelf {
	return predicate.Shelf(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UnitsTable, UnitsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUnitsWith applies the HasEdge predicate on the "units" edge with a given conditions (other predicates).
func HasUnitsWith(preds ...predicate.ShelfUnit) predicate.Shelf {
	return predicate.Shelf(func(s *sql.Selector) {
		step := newUnitsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPackages applies the HasEdge predicate on the "packages" edge.
func HasPackages() predicate.Shelf {
	return predicate.Shelf(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PackagesTable, PackagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPackagesWith applies the HasEdge predicate on the "packages" edge with a given conditions (other predicates).
func HasPackagesWith(preds ...predicate.GoodsPackage) predicate.Shelf {
	return predicate.Shelf(func(s *sql.Selector) {
		step := newPackagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Shelf) predicate.Shelf {
	return predicate.Shelf(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Shelf) predicate.Shelf {
	return predicate.Shelf(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Shelf) predicate.Shelf {
	return predicate.Shelf(sql.NotPredicates(p))
}
