// Code generated by ent, DO NOT EDIT.

package product

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEan13 holds the string denoting the ean13 field in the database.
	FieldEan13 = "ean13"
	// FieldEan8 holds the string denoting the ean8 field in the database.
	FieldEan8 = "ean8"
	// FieldQrCode holds the string denoting the qr_code field in the database.
	FieldQrCode = "qr_code"
	// EdgeUnits holds the string denoting the units edge name in mutations.
	EdgeUnits = "units"
	// EdgePackages holds the string denoting the packages edge name in mutations.
	EdgePackages = "packages"
	// Table holds the table name of the product in the database.
	Table = "products"
	// UnitsTable is the table that holds the units relation/edge.
	UnitsTable = "shelf_units"
	// UnitsInverseTable is the table name for the ShelfUnit entity.
	// It exists in this package in order to avoid circular dependency with the "shelfunit" package.
	UnitsInverseTable = "shelf_units"
	// UnitsColumn is the table column denoting the units relation/edge.
	UnitsColumn = "product_id"
	// PackagesTable is the table that holds the packages relation/edge.
	PackagesTable = "packages"
	// PackagesInverseTable is the table name for the GoodsPackage entity.
	// It exists in this package in order to avoid circular dependency with the "goodspackage" package.
	PackagesInverseTable = "packages"
	// PackagesColumn is the table column denoting the packages relation/edge.
	PackagesColumn = "product_id"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEan13,
	FieldEan8,
	FieldQrCode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEan13 holds the default value on creation for the "ean13" field.
	DefaultEan13 string
	// DefaultEan8 holds the default value on creation for the "ean8" field.
	DefaultEan8 string
	// DefaultQrCode holds the default value on creation for the "qr_code" field.
	DefaultQrCode string
)

// OrderOption defines the ordering options for the Product queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEan13 orders the results by the ean13 field.
func ByEan13(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEan13, opts...).ToFunc()
}

// ByEan8 orders the results by the ean8 field.
func ByEan8(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEan8, opts...).ToFunc()
}

// ByQrCode orders the results by the qr_code field.
func ByQrCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQrCode, opts...).ToFunc()
}

// ByUnitsCount orders the results by units count.
func ByUnitsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUnitsStep(), opts...)
	}
}

// ByUnits orders the results by units terms.
func ByUnits(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUnitsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPackagesCount orders the results by packages count.
func ByPackagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPackagesStep(), opts...)
	}
}

// ByPackages orders the results by packages terms.
func ByPackages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPackagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUnitsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UnitsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, UnitsTable, UnitsColumn),
	)
}
func newPackagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PackagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PackagesTable, PackagesColumn),
	)
}
