// Code generated by ent, DO NOT EDIT.

package goodspackage

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the goodspackage type in the database.
	Label = "goods_package"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPackageID holds the string denoting the package_id field in the database.
	FieldPackageID = "package_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// EdgeShelf holds the string denoting the shelf edge name in mutations.
	EdgeShelf = "shelf"
	// EdgeUnit holds the string denoting the unit edge name in mutations.
	EdgeUnit = "unit"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// Table holds the table name of the goodspackage in the database.
	Table = "packages"
	// ShelfTable is the table that holds the shelf relation/edge.
	ShelfTable = "packages"
	// ShelfInverseTable is the table name for the Shelf entity.
	// It exists in this package in order to avoid circular dependency with the "shelf" package.
	ShelfInverseTable = "shelves"
	// ShelfColumn is the table column denoting the shelf relation/edge.
	ShelfColumn = "shelf_packages"
	// UnitTable is the table that holds the unit relation/edge.
	UnitTable = "packages"
	// UnitInverseTable is the table name for the ShelfUnit entity.
	// It exists in this package in order to avoid circular dependency with the "shelfunit" package.
	UnitInverseTable = "shelf_units"
	// UnitColumn is the table column denoting the unit relation/edge.
	UnitColumn = "shelf_unit_packages"
	// ProductTable is the table that holds the product relation/edge.
	ProductTable = "packages"
	// ProductInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductInverseTable = "products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_id"
)

// Columns holds all SQL columns for goodspackage fields.
var Columns = []string{
	FieldID,
	FieldPackageID,
	FieldStatus,
	FieldPriority,
	FieldNote,
	FieldProductID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "packages"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"shelf_packages",
	"shelf_unit_packages",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultNote holds the default value on creation for the "note" field.
	DefaultNote string
)

// OrderOption defines the ordering options for the GoodsPackage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPackageID orders the results by the package_id field.
func ByPackageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPackageID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByShelfField orders the results by shelf field.
func ByShelfField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newShelfStep(), sql.OrderByField(field, opts...))
	}
}

// ByUnitField orders the results by unit field.
func ByUnitField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUnitStep(), sql.OrderByField(field, opts...))
	}
}

// ByProductField orders the results by product field.
func ByProductField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductStep(), sql.OrderByField(field, opts...))
	}
}
func newShelfStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ShelfInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ShelfTable, ShelfColumn),
	)
}
func newUnitStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UnitInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UnitTable, UnitColumn),
	)
}
func newProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
	)
}
