// Code generated by ent, DO NOT EDIT.

package shelfunit

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the shelfunit type in the database.
	Label = "shelf_unit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUnitNumber holds the string denoting the unit_number field in the database.
	FieldUnitNumber = "unit_number"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldPositionFrac holds the string denoting the position_frac field in the database.
	FieldPositionFrac = "position_frac"
	// FieldAccessCol holds the string denoting the access_col field in the database.
	FieldAccessCol = "access_col"
	// FieldAccessRow holds the string denoting the access_row field in the database.
	FieldAccessRow = "access_row"
	// FieldCapacity holds the string denoting the capacity field in the database.
	FieldCapacity = "capacity"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// EdgeShelf holds the string denoting the shelf edge name in mutations.
	EdgeShelf = "shelf"
	// EdgePackages holds the string denoting the packages edge name in mutations.
	EdgePackages = "packages"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// Table holds the table name of the shelfunit in the database.
	Table = "shelf_units"
	// ShelfTable is the table that holds the shelf relation/edge.
	ShelfTable = "shelf_units"
	// ShelfInverseTable is the table name for the Shelf entity.
	// It exists in this package in order to avoid circular dependency with the "shelf" package.
	ShelfInverseTable = "shelves"
	// ShelfColumn is the table column denoting the shelf relation/edge.
	ShelfColumn = "shelf_units"
	// PackagesTable is the table that holds the packages relation/edge.
	PackagesTable = "packages"
	// PackagesInverseTable is the table name for the GoodsPackage entity.
	// It exists in this package in order to avoid circular dependency with the "goodspackage" package.
	PackagesInverseTable = "packages"
	// PackagesColumn is the table column denoting the packages relation/edge.
	PackagesColumn = "shelf_unit_packages"
	// ProductTable is the table that holds the product relation/edge.
	ProductTable = "shelf_units"
	// ProductInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductInverseTable = "products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_id"
)

// Columns holds all SQL columns for shelfunit fields.
var Columns = []string{
	FieldID,
	FieldUnitNumber,
	FieldLabel,
	FieldPositionFrac,
	FieldAccessCol,
	FieldAccessRow,
	FieldCapacity,
	FieldProductID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "shelf_units"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"shelf_units",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLabel holds the default value on creation for the "label" field.
	DefaultLabel string
	// DefaultPositionFrac holds the default value on creation for the "position_frac" field.
	DefaultPositionFrac float64
	// DefaultAccessCol holds the default value on creation for the "access_col" field.
	DefaultAccessCol int
	// DefaultAccessRow holds the default value on creation for the "access_row" field.
	DefaultAccessRow int
	// DefaultCapacity holds the default value on creation for the "capacity" field.
	DefaultCapacity int
)

// OrderOption defines the ordering options for the ShelfUnit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUnitNumber orders the results by the unit_number field.
func ByUnitNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitNumber, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByPositionFrac orders the results by the position_frac field.
func ByPositionFrac(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionFrac, opts...).ToFunc()
}

// ByAccessCol orders the results by the access_col field.
func ByAccessCol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessCol, opts...).ToFunc()
}

// ByAccessRow orders the results by the access_row field.
func ByAccessRow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessRow, opts...).ToFunc()
}

// ByCapacity orders the results by the capacity field.
func ByCapacity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapacity, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByShelfField orders the results by shelf field.
func ByShelfField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newShelfStep(), sql.OrderByField(field, opts...))
	}
}

// ByPackagesCount orders the results by packages count.
func ByPackagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPackagesStep(), opts...)
	}
}

// ByPackages orders the results by packages terms.
func ByPackages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPackagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProductField orders the results by product field.
func ByProductField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductStep(), sql.OrderByField(field, opts...))
	}
}
func newShelfStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ShelfInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ShelfTable, ShelfColumn),
	)
}
func newPackagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PackagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PackagesTable, PackagesColumn),
	)
}
func newProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ProductTable, ProductColumn),
	)
}
