// Code generated by ent, DO NOT EDIT.

package landmark

import (
	"warehouse/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Landmark {
	return predicate.Landmark(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Landmark {
	return predicate.Landmark(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Landmark {
	return predicate.Landmark(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Landmark {
	return predicate.Landmark(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Landmark {
	return predicate.Landmark(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Landmark {
	return predicate.Landmark(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Landmark {
	return predicate.Landmark(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldName, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldKind, v))
}

// Col applies equality check predicate on the "col" field. It's identical to ColEQ.
func Col(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldCol, v))
}

// Row applies equality check predicate on the "row" field. It's identical to RowEQ.
func Row(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldRow, v))
}

// IsMovable applies equality check predicate on the "is_movable" field. It's identical to IsMovableEQ.
func IsMovable(v bool) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldIsMovable, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldNote, v))
}

// WarehouseID applies equality check predicate on the "warehouse_id" field. It's identical to WarehouseIDEQ.
func WarehouseID(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldWarehouseID, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Landmark {
	return predicate.Landmark(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Landmark {
	return predicate.Landmark(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Landmark {
	return predicate.Landmark(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Landmark {
	return predicate.Landmark(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldContainsFold(FieldName, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Landmark {
	return predicate.Landmark(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Landmark {
	return predicate.Landmark(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldContainsFold(FieldKind, v))
}

// ColEQ applies the EQ predicate on the "col" field.
func ColEQ(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldCol, v))
}

// ColNEQ applies the NEQ predicate on the "col" field.
func ColNEQ(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldNEQ(FieldCol, v))
}

// ColIn applies the In predicate on the "col" field.
func ColIn(vs ...int) predicate.Landmark {
	return predicate.Landmark(sql.FieldIn(FieldCol, vs...))
}

// ColNotIn applies the NotIn predicate on the "col" field.
func ColNotIn(vs ...int) predicate.Landmark {
	return predicate.Landmark(sql.FieldNotIn(FieldCol, vs...))
}

// ColGT applies the GT predicate on the "col" field.
func ColGT(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldGT(FieldCol, v))
}

// ColGTE applies the GTE predicate on the "col" field.
func ColGTE(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldGTE(FieldCol, v))
}

// ColLT applies the LT predicate on the "col" field.
func ColLT(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldLT(FieldCol, v))
}

// ColLTE applies the LTE predicate on the "col" field.
func ColLTE(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldLTE(FieldCol, v))
}

// RowEQ applies the EQ predicate on the "row" field.
func RowEQ(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldRow, v))
}

// RowNEQ applies the NEQ predicate on the "row" field.
func RowNEQ(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldNEQ(FieldRow, v))
}

// RowIn applies the In predicate on the "row" field.
func RowIn(vs ...int) predicate.Landmark {
	return predicate.Landmark(sql.FieldIn(FieldRow, vs...))
}

// RowNotIn applies the NotIn predicate on the "row" field.
func RowNotIn(vs ...int) predicate.Landmark {
	return predicate.Landmark(sql.FieldNotIn(FieldRow, vs...))
}

// RowGT applies the GT predicate on the "row" field.
func RowGT(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldGT(FieldRow, v))
}

// RowGTE applies the GTE predicate on the "row" field.
func RowGTE(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldGTE(FieldRow, v))
}

// RowLT applies the LT predicate on the "row" field.
func RowLT(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldLT(FieldRow, v))
}

// RowLTE applies the LTE predicate on the "row" field.
func RowLTE(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldLTE(FieldRow, v))
}

// IsMovableEQ applies the EQ predicate on the "is_movable" field.
func IsMovableEQ(v bool) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldIsMovable, v))
}

// IsMovableNEQ applies the NEQ predicate on the "is_movable" field.
func IsMovableNEQ(v bool) predicate.Landmark {
	return predicate.Landmark(sql.FieldNEQ(FieldIsMovable, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Landmark {
	return predicate.Landmark(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Landmark {
	return predicate.Landmark(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Landmark {
	return predicate.Landmark(sql.FieldContainsFold(FieldNote, v))
}

// WarehouseIDEQ applies the EQ predicate on the "warehouse_id" field.
func WarehouseIDEQ(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldEQ(FieldWarehouseID, v))
}

// WarehouseIDNEQ applies the NEQ predicate on the "warehouse_id" field.
func WarehouseIDNEQ(v int) predicate.Landmark {
	return predicate.Landmark(sql.FieldNEQ(FieldWarehouseID, v))
}

// WarehouseIDIn applies the In predicate on the "warehouse_id" field.
func WarehouseIDIn(vs ...int) predicate.Landmark {
	return predicate.Landmark(sql.FieldIn(FieldWarehouseID, vs...))
}

// WarehouseIDNotIn applies the NotIn predicate on the "warehouse_id" field.
func WarehouseIDNotIn(vs ...int) predicate.Landmark {
	return predicate.Landmark(sql.FieldNotIn(FieldWarehouseID, vs...))
}

// WarehouseIDIsNil applies the IsNil predicate on the "warehouse_id" field.
func WarehouseIDIsNil() predicate.Landmark {
	return predicate.Landmark(sql.FieldIsNull(FieldWarehouseID))
}

// WarehouseIDNotNil applies the NotNil predicate on the "warehouse_id" field.
func WarehouseIDNotNil() predicate.Landmark {
	return predicate.Landmark(sql.FieldNotNull(FieldWarehouseID))
}

// HasWarehouse applies the HasEdge predicate on the "warehouse" edge.
func HasWarehouse() predicate.Landmark {
	return predicate.Landmark(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WarehouseTable, WarehouseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWarehouseWith applies the HasEdge predicate on the "warehouse" edge with a given conditions (other predicates).
func HasWarehouseWith(preds ...predicate.Warehouse) predicate.Landmark {
	return predicate.Landmark(func(s *sql.Selector) {
		step := newWarehouseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Landmark) predicate.Landmark {
	return predicate.Landmark(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Landmark) predicate.Landmark {
	return predicate.Landmark(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Landmark) predicate.Landmark {
	return predicate.Landmark(sql.NotPredicates(p))
}
