// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"warehouse/ent/goodspackage"
	"warehouse/ent/product"
	"warehouse/ent/shelf"
	"warehouse/ent/shelfunit"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoodsPackageCreate is the builder for creating a GoodsPackage entity.
type GoodsPackageCreate struct {
	config
	mutation *GoodsPackageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPackageID sets the "package_id" field.
func (_c *GoodsPackageCreate) SetPackageID(v string) *GoodsPackageCreate {
	_c.mutation.SetPackageID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *GoodsPackageCreate) SetStatus(v string) *GoodsPackageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GoodsPackageCreate) SetNillableStatus(v *string) *GoodsPackageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *GoodsPackageCreate) SetPriority(v int) *GoodsPackageCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *GoodsPackageCreate) SetNillablePriority(v *int) *GoodsPackageCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *GoodsPackageCreate) SetNote(v string) *GoodsPackageCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *GoodsPackageCreate) SetNillableNote(v *string) *GoodsPackageCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *GoodsPackageCreate) SetProductID(v int) *GoodsPackageCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_c *GoodsPackageCreate) SetNillableProductID(v *int) *GoodsPackageCreate {
	if v != nil {
		_c.SetProductID(*v)
	}
	return _c
}

// SetShelfID sets the "shelf" edge to the Shelf entity by ID.
func (_c *GoodsPackageCreate) SetShelfID(id int) *GoodsPackageCreate {
	_c.mutation.SetShelfID(id)
	return _c
}

// SetNillableShelfID sets the "shelf" edge to the Shelf entity by ID if the given value is not nil.
func (_c *GoodsPackageCreate) SetNillableShelfID(id *int) *GoodsPackageCreate {
	if id != nil {
		_c = _c.SetShelfID(*id)
	}
	return _c
}

// SetShelf sets the "shelf" edge to the Shelf entity.
func (_c *GoodsPackageCreate) SetShelf(v *Shelf) *GoodsPackageCreate {
	return _c.SetShelfID(v.ID)
}

// SetUnitID sets the "unit" edge to the ShelfUnit entity by ID.
func (_c *GoodsPackageCreate) SetUnitID(id int) *GoodsPackageCreate {
	_c.mutation.SetUnitID(id)
	return _c
}

// SetNillableUnitID sets the "unit" edge to the ShelfUnit entity by ID if the given value is not nil.
func (_c *GoodsPackageCreate) SetNillableUnitID(id *int) *GoodsPackageCreate {
	if id != nil {
		_c = _c.SetUnitID(*id)
	}
	return _c
}

// SetUnit sets the "unit" edge to the ShelfUnit entity.
func (_c *GoodsPackageCreate) SetUnit(v *ShelfUnit) *GoodsPackageCreate {
	return _c.SetUnitID(v.ID)
}

// SetProduct sets the "product" edge to the Product entity.
func (_c *GoodsPackageCreate) SetProduct(v *Product) *GoodsPackageCreate {
	return _c.SetProductID(v.ID)
}

// Mutation returns the GoodsPackageMutation object of the builder.
func (_c *GoodsPackageCreate) Mutation() *GoodsPackageMutation {
	return _c.mutation
}

// Save creates the GoodsPackage in the database.
func (_c *GoodsPackageCreate) Save(ctx context.Context) (*GoodsPackage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GoodsPackageCreate) SaveX(ctx context.Context) *GoodsPackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoodsPackageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoodsPackageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GoodsPackageCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := goodspackage.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := goodspackage.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Note(); !ok {
		v := goodspackage.DefaultNote
		_c.mutation.SetNote(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GoodsPackageCreate) check() error {
	if _, ok := _c.mutation.PackageID(); !ok {
		return &ValidationError{Name: "package_id", err: errors.New(`ent: missing required field "GoodsPackage.package_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "GoodsPackage.status"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "GoodsPackage.priority"`)}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "GoodsPackage.note"`)}
	}
	return nil
}

func (_c *GoodsPackageCreate) sqlSave(ctx context.Context) (*GoodsPackage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GoodsPackageCreate) createSpec() (*GoodsPackage, *sqlgraph.CreateSpec) {
	var (
		_node = &GoodsPackage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(goodspackage.Table, sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PackageID(); ok {
		_spec.SetField(goodspackage.FieldPackageID, field.TypeString, value)
		_node.PackageID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(goodspackage.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(goodspackage.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(goodspackage.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if nodes := _c.mutation.ShelfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.ShelfTable,
			Columns: []string{goodspackage.ShelfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.shelf_packages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UnitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.UnitTable,
			Columns: []string{goodspackage.UnitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.shelf_unit_packages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.ProductTable,
			Columns: []string{goodspackage.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GoodsPackage.Create().
//		SetPackageID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GoodsPackageUpsert) {
//			SetPackageID(v+v).
//		}).
//		Exec(ctx)
func (_c *GoodsPackageCreate) OnConflict(opts ...sql.ConflictOption) *GoodsPackageUpsertOne {
	_c.conflict = opts
	return &GoodsPackageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GoodsPackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GoodsPackageCreate) OnConflictColumns(columns ...string) *GoodsPackageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GoodsPackageUpsertOne{
		create: _c,
	}
}

type (
	// GoodsPackageUpsertOne is the builder for "upsert"-ing
	//  one GoodsPackage node.
	GoodsPackageUpsertOne struct {
		create *GoodsPackageCreate
	}

	// GoodsPackageUpsert is the "OnConflict" setter.
	GoodsPackageUpsert struct {
		*sql.UpdateSet
	}
)

// SetPackageID sets the "package_id" field.
func (u *GoodsPackageUpsert) SetPackageID(v string) *GoodsPackageUpsert {
	u.Set(goodspackage.FieldPackageID, v)
	return u
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *GoodsPackageUpsert) UpdatePackageID() *GoodsPackageUpsert {
	u.SetExcluded(goodspackage.FieldPackageID)
	return u
}

// SetStatus sets the "status" field.
func (u *GoodsPackageUpsert) SetStatus(v string) *GoodsPackageUpsert {
	u.Set(goodspackage.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GoodsPackageUpsert) UpdateStatus() *GoodsPackageUpsert {
	u.SetExcluded(goodspackage.FieldStatus)
	return u
}

// SetPriority sets the "priority" field.
func (u *GoodsPackageUpsert) SetPriority(v int) *GoodsPackageUpsert {
	u.Set(goodspackage.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *GoodsPackageUpsert) UpdatePriority() *GoodsPackageUpsert {
	u.SetExcluded(goodspackage.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *GoodsPackageUpsert) AddPriority(v int) *GoodsPackageUpsert {
	u.Add(goodspackage.FieldPriority, v)
	return u
}

// SetNote sets the "note" field.
func (u *GoodsPackageUpsert) SetNote(v string) *GoodsPackageUpsert {
	u.Set(goodspackage.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *GoodsPackageUpsert) UpdateNote() *GoodsPackageUpsert {
	u.SetExcluded(goodspackage.FieldNote)
	return u
}

// SetProductID sets the "product_id" field.
func (u *GoodsPackageUpsert) SetProductID(v int) *GoodsPackageUpsert {
	u.Set(goodspackage.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *GoodsPackageUpsert) UpdateProductID() *GoodsPackageUpsert {
	u.SetExcluded(goodspackage.FieldProductID)
	return u
}

// ClearProductID clears the value of the "product_id" field.
func (u *GoodsPackageUpsert) ClearProductID() *GoodsPackageUpsert {
	u.SetNull(goodspackage.FieldProductID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GoodsPackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GoodsPackageUpsertOne) UpdateNewValues() *GoodsPackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GoodsPackage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GoodsPackageUpsertOne) Ignore() *GoodsPackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GoodsPackageUpsertOne) DoNothing() *GoodsPackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GoodsPackageCreate.OnConflict
// documentation for more info.
func (u *GoodsPackageUpsertOne) Update(set func(*GoodsPackageUpsert)) *GoodsPackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GoodsPackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetPackageID sets the "package_id" field.
func (u *GoodsPackageUpsertOne) SetPackageID(v string) *GoodsPackageUpsertOne {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.SetPackageID(v)
	})
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *GoodsPackageUpsertOne) UpdatePackageID() *GoodsPackageUpsertOne {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.UpdatePackageID()
	})
}

// SetStatus sets the "status" field.
func (u *GoodsPackageUpsertOne) SetStatus(v string) *GoodsPackageUpsertOne {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GoodsPackageUpsertOne) UpdateStatus() *GoodsPackageUpsertOne {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.UpdateStatus()
	})
}

// SetPriority sets the "priority" field.
func (u *GoodsPackageUpsertOne) SetPriority(v int) *GoodsPackageUpsertOne {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *GoodsPackageUpsertOne) AddPriority(v int) *GoodsPackageUpsertOne {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *GoodsPackageUpsertOne) UpdatePriority() *GoodsPackageUpsertOne {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.UpdatePriority()
	})
}

// SetNote sets the "note" field.
func (u *GoodsPackageUpsertOne) SetNote(v string) *GoodsPackageUpsertOne {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *GoodsPackageUpsertOne) UpdateNote() *GoodsPackageUpsertOne {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.UpdateNote()
	})
}

// SetProductID sets the "product_id" field.
func (u *GoodsPackageUpsertOne) SetProductID(v int) *GoodsPackageUpsertOne {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *GoodsPackageUpsertOne) UpdateProductID() *GoodsPackageUpsertOne {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.UpdateProductID()
	})
}

// ClearProductID clears the value of the "product_id" field.
func (u *GoodsPackageUpsertOne) ClearProductID() *GoodsPackageUpsertOne {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.ClearProductID()
	})
}

// Exec executes the query.
func (u *GoodsPackageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GoodsPackageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GoodsPackageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GoodsPackageUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GoodsPackageUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GoodsPackageCreateBulk is the builder for creating many GoodsPackage entities in bulk.
type GoodsPackageCreateBulk struct {
	config
	err      error
	builders []*GoodsPackageCreate
	conflict []sql.ConflictOption
}

// Save creates the GoodsPackage entities in the database.
func (_c *GoodsPackageCreateBulk) Save(ctx context.Context) ([]*GoodsPackage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GoodsPackage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GoodsPackageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GoodsPackageCreateBulk) SaveX(ctx context.Context) []*GoodsPackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoodsPackageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoodsPackageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GoodsPackage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GoodsPackageUpsert) {
//			SetPackageID(v+v).
//		}).
//		Exec(ctx)
func (_c *GoodsPackageCreateBulk) OnConflict(opts ...sql.ConflictOption) *GoodsPackageUpsertBulk {
	_c.conflict = opts
	return &GoodsPackageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GoodsPackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GoodsPackageCreateBulk) OnConflictColumns(columns ...string) *GoodsPackageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GoodsPackageUpsertBulk{
		create: _c,
	}
}

// GoodsPackageUpsertBulk is the builder for "upsert"-ing
// a bulk of GoodsPackage nodes.
type GoodsPackageUpsertBulk struct {
	create *GoodsPackageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GoodsPackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GoodsPackageUpsertBulk) UpdateNewValues() *GoodsPackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GoodsPackage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GoodsPackageUpsertBulk) Ignore() *GoodsPackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GoodsPackageUpsertBulk) DoNothing() *GoodsPackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GoodsPackageCreateBulk.OnConflict
// documentation for more info.
func (u *GoodsPackageUpsertBulk) Update(set func(*GoodsPackageUpsert)) *GoodsPackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GoodsPackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetPackageID sets the "package_id" field.
func (u *GoodsPackageUpsertBulk) SetPackageID(v string) *GoodsPackageUpsertBulk {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.SetPackageID(v)
	})
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *GoodsPackageUpsertBulk) UpdatePackageID() *GoodsPackageUpsertBulk {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.UpdatePackageID()
	})
}

// SetStatus sets the "status" field.
func (u *GoodsPackageUpsertBulk) SetStatus(v string) *GoodsPackageUpsertBulk {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GoodsPackageUpsertBulk) UpdateStatus() *GoodsPackageUpsertBulk {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.UpdateStatus()
	})
}

// SetPriority sets the "priority" field.
func (u *GoodsPackageUpsertBulk) SetPriority(v int) *GoodsPackageUpsertBulk {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *GoodsPackageUpsertBulk) AddPriority(v int) *GoodsPackageUpsertBulk {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *GoodsPackageUpsertBulk) UpdatePriority() *GoodsPackageUpsertBulk {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.UpdatePriority()
	})
}

// SetNote sets the "note" field.
func (u *GoodsPackageUpsertBulk) SetNote(v string) *GoodsPackageUpsertBulk {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *GoodsPackageUpsertBulk) UpdateNote() *GoodsPackageUpsertBulk {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.UpdateNote()
	})
}

// SetProductID sets the "product_id" field.
func (u *GoodsPackageUpsertBulk) SetProductID(v int) *GoodsPackageUpsertBulk {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *GoodsPackageUpsertBulk) UpdateProductID() *GoodsPackageUpsertBulk {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.UpdateProductID()
	})
}

// ClearProductID clears the value of the "product_id" field.
func (u *GoodsPackageUpsertBulk) ClearProductID() *GoodsPackageUpsertBulk {
	return u.Update(func(s *GoodsPackageUpsert) {
		s.ClearProductID()
	})
}

// Exec executes the query.
func (u *GoodsPackageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GoodsPackageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GoodsPackageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GoodsPackageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
