// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"warehouse/ent/goodspackage"
	"warehouse/ent/product"
	"warehouse/ent/shelf"
	"warehouse/ent/shelfunit"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GoodsPackage is the model entity for the GoodsPackage schema.
type GoodsPackage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 包裹业务编号
	PackageID string `json:"package_id,omitempty"`
	// pending/placed/delivered
	Status string `json:"status,omitempty"`
	// 优先级
	Priority int `json:"priority,omitempty"`
	// 备注
	Note string `json:"note,omitempty"`
	// 包裹内商品ID
	ProductID int `json:"product_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GoodsPackageQuery when eager-loading is set.
	Edges               GoodsPackageEdges `json:"edges"`
	shelf_packages      *int
	shelf_unit_packages *int
	selectValues        sql.SelectValues
}

// GoodsPackageEdges holds the relations/edges for other nodes in the graph.
type GoodsPackageEdges struct {
	// 目标货架
	Shelf *Shelf `json:"shelf,omitempty"`
	// 目标单元
	Unit *ShelfUnit `json:"unit,omitempty"`
	// 包裹内商品
	Product *Product `json:"product,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ShelfOrErr returns the Shelf value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GoodsPackageEdges) ShelfOrErr() (*Shelf, error) {
	if e.Shelf != nil {
		return e.Shelf, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: shelf.Label}
	}
	return nil, &NotLoadedError{edge: "shelf"}
}

// UnitOrErr returns the Unit value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GoodsPackageEdges) UnitOrErr() (*ShelfUnit, error) {
	if e.Unit != nil {
		return e.Unit, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: shelfunit.Label}
	}
	return nil, &NotLoadedError{edge: "unit"}
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GoodsPackageEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GoodsPackage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case goodspackage.FieldID, goodspackage.FieldPriority, goodspackage.FieldProductID:
			values[i] = new(sql.NullInt64)
		case goodspackage.FieldPackageID, goodspackage.FieldStatus, goodspackage.FieldNote:
			values[i] = new(sql.NullString)
		case goodspackage.ForeignKeys[0]: // shelf_packages
			values[i] = new(sql.NullInt64)
		case goodspackage.ForeignKeys[1]: // shelf_unit_packages
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GoodsPackage fields.
func (_m *GoodsPackage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case goodspackage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case goodspackage.FieldPackageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field package_id", values[i])
			} else if value.Valid {
				_m.PackageID = value.String
			}
		case goodspackage.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case goodspackage.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case goodspackage.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case goodspackage.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = int(value.Int64)
			}
		case goodspackage.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field shelf_packages", value)
			} else if value.Valid {
				_m.shelf_packages = new(int)
				*_m.shelf_packages = int(value.Int64)
			}
		case goodspackage.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field shelf_unit_packages", value)
			} else if value.Valid {
				_m.shelf_unit_packages = new(int)
				*_m.shelf_unit_packages = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GoodsPackage.
// This includes values selected through modifiers, order, etc.
func (_m *GoodsPackage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryShelf queries the "shelf" edge of the GoodsPackage entity.
func (_m *GoodsPackage) QueryShelf() *ShelfQuery {
	return NewGoodsPackageClient(_m.config).QueryShelf(_m)
}

// QueryUnit queries the "unit" edge of the GoodsPackage entity.
func (_m *GoodsPackage) QueryUnit() *ShelfUnitQuery {
	return NewGoodsPackageClient(_m.config).QueryUnit(_m)
}

// QueryProduct queries the "product" edge of the GoodsPackage entity.
func (_m *GoodsPackage) QueryProduct() *ProductQuery {
	return NewGoodsPackageClient(_m.config).QueryProduct(_m)
}

// Update returns a builder for updating this GoodsPackage.
// Note that you need to call GoodsPackage.Unwrap() before calling this method if this GoodsPackage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GoodsPackage) Update() *GoodsPackageUpdateOne {
	return NewGoodsPackageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GoodsPackage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GoodsPackage) Unwrap() *GoodsPackage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GoodsPackage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GoodsPackage) String() string {
	var builder strings.Builder
	builder.WriteString("GoodsPackage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("package_id=")
	builder.WriteString(_m.PackageID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductID))
	builder.WriteByte(')')
	return builder.String()
}

// GoodsPackages is a parsable slice of GoodsPackage.
type GoodsPackages []*GoodsPackage
