// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"warehouse/ent/goodspackage"
	"warehouse/ent/predicate"
	"warehouse/ent/product"
	"warehouse/ent/shelf"
	"warehouse/ent/shelfunit"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoodsPackageUpdate is the builder for updating GoodsPackage entities.
type GoodsPackageUpdate struct {
	config
	hooks    []Hook
	mutation *GoodsPackageMutation
}

// Where appends a list predicates to the GoodsPackageUpdate builder.
func (_u *GoodsPackageUpdate) Where(ps ...predicate.GoodsPackage) *GoodsPackageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *GoodsPackageUpdate) SetPackageID(v string) *GoodsPackageUpdate {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *GoodsPackageUpdate) SetNillablePackageID(v *string) *GoodsPackageUpdate {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GoodsPackageUpdate) SetStatus(v string) *GoodsPackageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GoodsPackageUpdate) SetNillableStatus(v *string) *GoodsPackageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *GoodsPackageUpdate) SetPriority(v int) *GoodsPackageUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *GoodsPackageUpdate) SetNillablePriority(v *int) *GoodsPackageUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *GoodsPackageUpdate) AddPriority(v int) *GoodsPackageUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *GoodsPackageUpdate) SetNote(v string) *GoodsPackageUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *GoodsPackageUpdate) SetNillableNote(v *string) *GoodsPackageUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *GoodsPackageUpdate) SetProductID(v int) *GoodsPackageUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *GoodsPackageUpdate) SetNillableProductID(v *int) *GoodsPackageUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// ClearProductID clears the value of the "product_id" field.
func (_u *GoodsPackageUpdate) ClearProductID() *GoodsPackageUpdate {
	_u.mutation.ClearProductID()
	return _u
}

// SetShelfID sets the "shelf" edge to the Shelf entity by ID.
func (_u *GoodsPackageUpdate) SetShelfID(id int) *GoodsPackageUpdate {
	_u.mutation.SetShelfID(id)
	return _u
}

// SetNillableShelfID sets the "shelf" edge to the Shelf entity by ID if the given value is not nil.
func (_u *GoodsPackageUpdate) SetNillableShelfID(id *int) *GoodsPackageUpdate {
	if id != nil {
		_u = _u.SetShelfID(*id)
	}
	return _u
}

// SetShelf sets the "shelf" edge to the Shelf entity.
func (_u *GoodsPackageUpdate) SetShelf(v *Shelf) *GoodsPackageUpdate {
	return _u.SetShelfID(v.ID)
}

// SetUnitID sets the "unit" edge to the ShelfUnit entity by ID.
func (_u *GoodsPackageUpdate) SetUnitID(id int) *GoodsPackageUpdate {
	_u.mutation.SetUnitID(id)
	return _u
}

// SetNillableUnitID sets the "unit" edge to the ShelfUnit entity by ID if the given value is not nil.
func (_u *GoodsPackageUpdate) SetNillableUnitID(id *int) *GoodsPackageUpdate {
	if id != nil {
		_u = _u.SetUnitID(*id)
	}
	return _u
}

// SetUnit sets the "unit" edge to the ShelfUnit entity.
func (_u *GoodsPackageUpdate) SetUnit(v *ShelfUnit) *GoodsPackageUpdate {
	return _u.SetUnitID(v.ID)
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *GoodsPackageUpdate) SetProduct(v *Product) *GoodsPackageUpdate {
	return _u.SetProductID(v.ID)
}

// Mutation returns the GoodsPackageMutation object of the builder.
func (_u *GoodsPackageUpdate) Mutation() *GoodsPackageMutation {
	return _u.mutation
}

// ClearShelf clears the "shelf" edge to the Shelf entity.
func (_u *GoodsPackageUpdate) ClearShelf() *GoodsPackageUpdate {
	_u.mutation.ClearShelf()
	return _u
}

// ClearUnit clears the "unit" edge to the ShelfUnit entity.
func (_u *GoodsPackageUpdate) ClearUnit() *GoodsPackageUpdate {
	_u.mutation.ClearUnit()
	return _u
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *GoodsPackageUpdate) ClearProduct() *GoodsPackageUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GoodsPackageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoodsPackageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GoodsPackageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoodsPackageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GoodsPackageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(goodspackage.Table, goodspackage.Columns, sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(goodspackage.FieldPackageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(goodspackage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(goodspackage.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(goodspackage.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(goodspackage.FieldNote, field.TypeString, value)
	}
	if _u.mutation.ShelfCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.ShelfTable,
			Columns: []string{goodspackage.ShelfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShelfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.ShelfTable,
			Columns: []string{goodspackage.ShelfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UnitCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.UnitTable,
			Columns: []string{goodspackage.UnitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UnitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.UnitTable,
			Columns: []string{goodspackage.UnitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.ProductTable,
			Columns: []string{goodspackage.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.ProductTable,
			Columns: []string{goodspackage.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goodspackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GoodsPackageUpdateOne is the builder for updating a single GoodsPackage entity.
type GoodsPackageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GoodsPackageMutation
}

// SetPackageID sets the "package_id" field.
func (_u *GoodsPackageUpdateOne) SetPackageID(v string) *GoodsPackageUpdateOne {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *GoodsPackageUpdateOne) SetNillablePackageID(v *string) *GoodsPackageUpdateOne {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GoodsPackageUpdateOne) SetStatus(v string) *GoodsPackageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GoodsPackageUpdateOne) SetNillableStatus(v *string) *GoodsPackageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *GoodsPackageUpdateOne) SetPriority(v int) *GoodsPackageUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *GoodsPackageUpdateOne) SetNillablePriority(v *int) *GoodsPackageUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *GoodsPackageUpdateOne) AddPriority(v int) *GoodsPackageUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *GoodsPackageUpdateOne) SetNote(v string) *GoodsPackageUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *GoodsPackageUpdateOne) SetNillableNote(v *string) *GoodsPackageUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *GoodsPackageUpdateOne) SetProductID(v int) *GoodsPackageUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *GoodsPackageUpdateOne) SetNillableProductID(v *int) *GoodsPackageUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// ClearProductID clears the value of the "product_id" field.
func (_u *GoodsPackageUpdateOne) ClearProductID() *GoodsPackageUpdateOne {
	_u.mutation.ClearProductID()
	return _u
}

// SetShelfID sets the "shelf" edge to the Shelf entity by ID.
func (_u *GoodsPackageUpdateOne) SetShelfID(id int) *GoodsPackageUpdateOne {
	_u.mutation.SetShelfID(id)
	return _u
}

// SetNillableShelfID sets the "shelf" edge to the Shelf entity by ID if the given value is not nil.
func (_u *GoodsPackageUpdateOne) SetNillableShelfID(id *int) *GoodsPackageUpdateOne {
	if id != nil {
		_u = _u.SetShelfID(*id)
	}
	return _u
}

// SetShelf sets the "shelf" edge to the Shelf entity.
func (_u *GoodsPackageUpdateOne) SetShelf(v *Shelf) *GoodsPackageUpdateOne {
	return _u.SetShelfID(v.ID)
}

// SetUnitID sets the "unit" edge to the ShelfUnit entity by ID.
func (_u *GoodsPackageUpdateOne) SetUnitID(id int) *GoodsPackageUpdateOne {
	_u.mutation.SetUnitID(id)
	return _u
}

// SetNillableUnitID sets the "unit" edge to the ShelfUnit entity by ID if the given value is not nil.
func (_u *GoodsPackageUpdateOne) SetNillableUnitID(id *int) *GoodsPackageUpdateOne {
	if id != nil {
		_u = _u.SetUnitID(*id)
	}
	return _u
}

// SetUnit sets the "unit" edge to the ShelfUnit entity.
func (_u *GoodsPackageUpdateOne) SetUnit(v *ShelfUnit) *GoodsPackageUpdateOne {
	return _u.SetUnitID(v.ID)
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *GoodsPackageUpdateOne) SetProduct(v *Product) *GoodsPackageUpdateOne {
	return _u.SetProductID(v.ID)
}

// Mutation returns the GoodsPackageMutation object of the builder.
func (_u *GoodsPackageUpdateOne) Mutation() *GoodsPackageMutation {
	return _u.mutation
}

// ClearShelf clears the "shelf" edge to the Shelf entity.
func (_u *GoodsPackageUpdateOne) ClearShelf() *GoodsPackageUpdateOne {
	_u.mutation.ClearShelf()
	return _u
}

// ClearUnit clears the "unit" edge to the ShelfUnit entity.
func (_u *GoodsPackageUpdateOne) ClearUnit() *GoodsPackageUpdateOne {
	_u.mutation.ClearUnit()
	return _u
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *GoodsPackageUpdateOne) ClearProduct() *GoodsPackageUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// Where appends a list predicates to the GoodsPackageUpdate builder.
func (_u *GoodsPackageUpdateOne) Where(ps ...predicate.GoodsPackage) *GoodsPackageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GoodsPackageUpdateOne) Select(field string, fields ...string) *GoodsPackageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GoodsPackage entity.
func (_u *GoodsPackageUpdateOne) Save(ctx context.Context) (*GoodsPackage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoodsPackageUpdateOne) SaveX(ctx context.Context) *GoodsPackage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GoodsPackageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoodsPackageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GoodsPackageUpdateOne) sqlSave(ctx context.Context) (_node *GoodsPackage, err error) {
	_spec := sqlgraph.NewUpdateSpec(goodspackage.Table, goodspackage.Columns, sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GoodsPackage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goodspackage.FieldID)
		for _, f := range fields {
			if !goodspackage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != goodspackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(goodspackage.FieldPackageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(goodspackage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(goodspackage.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(goodspackage.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(goodspackage.FieldNote, field.TypeString, value)
	}
	if _u.mutation.ShelfCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.ShelfTable,
			Columns: []string{goodspackage.ShelfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShelfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.ShelfTable,
			Columns: []string{goodspackage.ShelfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UnitCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.UnitTable,
			Columns: []string{goodspackage.UnitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UnitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.UnitTable,
			Columns: []string{goodspackage.UnitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.ProductTable,
			Columns: []string{goodspackage.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goodspackage.ProductTable,
			Columns: []string{goodspackage.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GoodsPackage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goodspackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
