// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"warehouse/ent/landmark"
	"warehouse/ent/predicate"
	"warehouse/ent/warehouse"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LandmarkUpdate is the builder for updating Landmark entities.
type LandmarkUpdate struct {
	config
	hooks    []Hook
	mutation *LandmarkMutation
}

// Where appends a list predicates to the LandmarkUpdate builder.
func (_u *LandmarkUpdate) Where(ps ...predicate.Landmark) *LandmarkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *LandmarkUpdate) SetCode(v string) *LandmarkUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *LandmarkUpdate) SetNillableCode(v *string) *LandmarkUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *LandmarkUpdate) SetName(v string) *LandmarkUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LandmarkUpdate) SetNillableName(v *string) *LandmarkUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *LandmarkUpdate) SetKind(v string) *LandmarkUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *LandmarkUpdate) SetNillableKind(v *string) *LandmarkUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetCol sets the "col" field.
func (_u *LandmarkUpdate) SetCol(v int) *LandmarkUpdate {
	_u.mutation.ResetCol()
	_u.mutation.SetCol(v)
	return _u
}

// SetNillableCol sets the "col" field if the given value is not nil.
func (_u *LandmarkUpdate) SetNillableCol(v *int) *LandmarkUpdate {
	if v != nil {
		_u.SetCol(*v)
	}
	return _u
}

// AddCol adds value to the "col" field.
func (_u *LandmarkUpdate) AddCol(v int) *LandmarkUpdate {
	_u.mutation.AddCol(v)
	return _u
}

// SetRow sets the "row" field.
func (_u *LandmarkUpdate) SetRow(v int) *LandmarkUpdate {
	_u.mutation.ResetRow()
	_u.mutation.SetRow(v)
	return _u
}

// SetNillableRow sets the "row" field if the given value is not nil.
func (_u *LandmarkUpdate) SetNillableRow(v *int) *LandmarkUpdate {
	if v != nil {
		_u.SetRow(*v)
	}
	return _u
}

// AddRow adds value to the "row" field.
func (_u *LandmarkUpdate) AddRow(v int) *LandmarkUpdate {
	_u.mutation.AddRow(v)
	return _u
}

// SetIsMovable sets the "is_movable" field.
func (_u *LandmarkUpdate) SetIsMovable(v bool) *LandmarkUpdate {
	_u.mutation.SetIsMovable(v)
	return _u
}

// SetNillableIsMovable sets the "is_movable" field if the given value is not nil.
func (_u *LandmarkUpdate) SetNillableIsMovable(v *bool) *LandmarkUpdate {
	if v != nil {
		_u.SetIsMovable(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *LandmarkUpdate) SetNote(v string) *LandmarkUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *LandmarkUpdate) SetNillableNote(v *string) *LandmarkUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetWarehouseID sets the "warehouse_id" field.
func (_u *LandmarkUpdate) SetWarehouseID(v int) *LandmarkUpdate {
	_u.mutation.SetWarehouseID(v)
	return _u
}

// SetNillableWarehouseID sets the "warehouse_id" field if the given value is not nil.
func (_u *LandmarkUpdate) SetNillableWarehouseID(v *int) *LandmarkUpdate {
	if v != nil {
		_u.SetWarehouseID(*v)
	}
	return _u
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (_u *LandmarkUpdate) ClearWarehouseID() *LandmarkUpdate {
	_u.mutation.ClearWarehouseID()
	return _u
}

// SetWarehouse sets the "warehouse" edge to the Warehouse entity.
func (_u *LandmarkUpdate) SetWarehouse(v *Warehouse) *LandmarkUpdate {
	return _u.SetWarehouseID(v.ID)
}

// Mutation returns the LandmarkMutation object of the builder.
func (_u *LandmarkUpdate) Mutation() *LandmarkMutation {
	return _u.mutation
}

// ClearWarehouse clears the "warehouse" edge to the Warehouse entity.
func (_u *LandmarkUpdate) ClearWarehouse() *LandmarkUpdate {
	_u.mutation.ClearWarehouse()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LandmarkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LandmarkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LandmarkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LandmarkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LandmarkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(landmark.Table, landmark.Columns, sqlgraph.NewFieldSpec(landmark.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(landmark.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(landmark.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(landmark.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Col(); ok {
		_spec.SetField(landmark.FieldCol, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCol(); ok {
		_spec.AddField(landmark.FieldCol, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Row(); ok {
		_spec.SetField(landmark.FieldRow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRow(); ok {
		_spec.AddField(landmark.FieldRow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsMovable(); ok {
		_spec.SetField(landmark.FieldIsMovable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(landmark.FieldNote, field.TypeString, value)
	}
	if _u.mutation.WarehouseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   landmark.WarehouseTable,
			Columns: []string{landmark.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WarehouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   landmark.WarehouseTable,
			Columns: []string{landmark.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{landmark.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LandmarkUpdateOne is the builder for updating a single Landmark entity.
type LandmarkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LandmarkMutation
}

// SetCode sets the "code" field.
func (_u *LandmarkUpdateOne) SetCode(v string) *LandmarkUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *LandmarkUpdateOne) SetNillableCode(v *string) *LandmarkUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *LandmarkUpdateOne) SetName(v string) *LandmarkUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LandmarkUpdateOne) SetNillableName(v *string) *LandmarkUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *LandmarkUpdateOne) SetKind(v string) *LandmarkUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *LandmarkUpdateOne) SetNillableKind(v *string) *LandmarkUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetCol sets the "col" field.
func (_u *LandmarkUpdateOne) SetCol(v int) *LandmarkUpdateOne {
	_u.mutation.ResetCol()
	_u.mutation.SetCol(v)
	return _u
}

// SetNillableCol sets the "col" field if the given value is not nil.
func (_u *LandmarkUpdateOne) SetNillableCol(v *int) *LandmarkUpdateOne {
	if v != nil {
		_u.SetCol(*v)
	}
	return _u
}

// AddCol adds value to the "col" field.
func (_u *LandmarkUpdateOne) AddCol(v int) *LandmarkUpdateOne {
	_u.mutation.AddCol(v)
	return _u
}

// SetRow sets the "row" field.
func (_u *LandmarkUpdateOne) SetRow(v int) *LandmarkUpdateOne {
	_u.mutation.ResetRow()
	_u.mutation.SetRow(v)
	return _u
}

// SetNillableRow sets the "row" field if the given value is not nil.
func (_u *LandmarkUpdateOne) SetNillableRow(v *int) *LandmarkUpdateOne {
	if v != nil {
		_u.SetRow(*v)
	}
	return _u
}

// AddRow adds value to the "row" field.
func (_u *LandmarkUpdateOne) AddRow(v int) *LandmarkUpdateOne {
	_u.mutation.AddRow(v)
	return _u
}

// SetIsMovable sets the "is_movable" field.
func (_u *LandmarkUpdateOne) SetIsMovable(v bool) *LandmarkUpdateOne {
	_u.mutation.SetIsMovable(v)
	return _u
}

// SetNillableIsMovable sets the "is_movable" field if the given value is not nil.
func (_u *LandmarkUpdateOne) SetNillableIsMovable(v *bool) *LandmarkUpdateOne {
	if v != nil {
		_u.SetIsMovable(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *LandmarkUpdateOne) SetNote(v string) *LandmarkUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *LandmarkUpdateOne) SetNillableNote(v *string) *LandmarkUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetWarehouseID sets the "warehouse_id" field.
func (_u *LandmarkUpdateOne) SetWarehouseID(v int) *LandmarkUpdateOne {
	_u.mutation.SetWarehouseID(v)
	return _u
}

// SetNillableWarehouseID sets the "warehouse_id" field if the given value is not nil.
func (_u *LandmarkUpdateOne) SetNillableWarehouseID(v *int) *LandmarkUpdateOne {
	if v != nil {
		_u.SetWarehouseID(*v)
	}
	return _u
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (_u *LandmarkUpdateOne) ClearWarehouseID() *LandmarkUpdateOne {
	_u.mutation.ClearWarehouseID()
	return _u
}

// SetWarehouse sets the "warehouse" edge to the Warehouse entity.
func (_u *LandmarkUpdateOne) SetWarehouse(v *Warehouse) *LandmarkUpdateOne {
	return _u.SetWarehouseID(v.ID)
}

// Mutation returns the LandmarkMutation object of the builder.
func (_u *LandmarkUpdateOne) Mutation() *LandmarkMutation {
	return _u.mutation
}

// ClearWarehouse clears the "warehouse" edge to the Warehouse entity.
func (_u *LandmarkUpdateOne) ClearWarehouse() *LandmarkUpdateOne {
	_u.mutation.ClearWarehouse()
	return _u
}

// Where appends a list predicates to the LandmarkUpdate builder.
func (_u *LandmarkUpdateOne) Where(ps ...predicate.Landmark) *LandmarkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LandmarkUpdateOne) Select(field string, fields ...string) *LandmarkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Landmark entity.
func (_u *LandmarkUpdateOne) Save(ctx context.Context) (*Landmark, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LandmarkUpdateOne) SaveX(ctx context.Context) *Landmark {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LandmarkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LandmarkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LandmarkUpdateOne) sqlSave(ctx context.Context) (_node *Landmark, err error) {
	_spec := sqlgraph.NewUpdateSpec(landmark.Table, landmark.Columns, sqlgraph.NewFieldSpec(landmark.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Landmark.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, landmark.FieldID)
		for _, f := range fields {
			if !landmark.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != landmark.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(landmark.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(landmark.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(landmark.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Col(); ok {
		_spec.SetField(landmark.FieldCol, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCol(); ok {
		_spec.AddField(landmark.FieldCol, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Row(); ok {
		_spec.SetField(landmark.FieldRow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRow(); ok {
		_spec.AddField(landmark.FieldRow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsMovable(); ok {
		_spec.SetField(landmark.FieldIsMovable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(landmark.FieldNote, field.TypeString, value)
	}
	if _u.mutation.WarehouseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   landmark.WarehouseTable,
			Columns: []string{landmark.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WarehouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   landmark.WarehouseTable,
			Columns: []string{landmark.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Landmark{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{landmark.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
