// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"warehouse/ent/pathplan"
	"warehouse/ent/predicate"
	"warehouse/ent/warehouse"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PathPlanQuery is the builder for querying PathPlan entities.
type PathPlanQuery struct {
	config
	ctx           *QueryContext
	order         []pathplan.OrderOption
	inters        []Interceptor
	predicates    []predicate.PathPlan
	withWarehouse *WarehouseQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PathPlanQuery builder.
func (_q *PathPlanQuery) Where(ps ...predicate.PathPlan) *PathPlanQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PathPlanQuery) Limit(limit int) *PathPlanQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PathPlanQuery) Offset(offset int) *PathPlanQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PathPlanQuery) Unique(unique bool) *PathPlanQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PathPlanQuery) Order(o ...pathplan.OrderOption) *PathPlanQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryWarehouse chains the current query on the "warehouse" edge.
func (_q *PathPlanQuery) QueryWarehouse() *WarehouseQuery {
	query := (&WarehouseClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pathplan.Table, pathplan.FieldID, selector),
			sqlgraph.To(warehouse.Table, warehouse.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pathplan.WarehouseTable, pathplan.WarehouseColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PathPlan entity from the query.
// Returns a *NotFoundError when no PathPlan was found.
func (_q *PathPlanQuery) First(ctx context.Context) (*PathPlan, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pathplan.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PathPlanQuery) FirstX(ctx context.Context) *PathPlan {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PathPlan ID from the query.
// Returns a *NotFoundError when no PathPlan ID was found.
func (_q *PathPlanQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pathplan.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PathPlanQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PathPlan entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PathPlan entity is found.
// Returns a *NotFoundError when no PathPlan entities are found.
func (_q *PathPlanQuery) Only(ctx context.Context) (*PathPlan, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pathplan.Label}
	default:
		return nil, &NotSingularError{pathplan.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PathPlanQuery) OnlyX(ctx context.Context) *PathPlan {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PathPlan ID in the query.
// Returns a *NotSingularError when more than one PathPlan ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PathPlanQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pathplan.Label}
	default:
		err = &NotSingularError{pathplan.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PathPlanQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PathPlans.
func (_q *PathPlanQuery) All(ctx context.Context) ([]*PathPlan, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PathPlan, *PathPlanQuery]()
	return withInterceptors[[]*PathPlan](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PathPlanQuery) AllX(ctx context.Context) []*PathPlan {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PathPlan IDs.
func (_q *PathPlanQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(pathplan.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PathPlanQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PathPlanQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PathPlanQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PathPlanQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PathPlanQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PathPlanQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PathPlanQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PathPlanQuery) Clone() *PathPlanQuery {
	if _q == nil {
		return nil
	}
	return &PathPlanQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]pathplan.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.PathPlan{}, _q.predicates...),
		withWarehouse: _q.withWarehouse.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithWarehouse tells the query-builder to eager-load the nodes that are connected to
// the "warehouse" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PathPlanQuery) WithWarehouse(opts ...func(*WarehouseQuery)) *PathPlanQuery {
	query := (&WarehouseClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWarehouse = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PlanKey string `json:"plan_key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PathPlan.Query().
//		GroupBy(pathplan.FieldPlanKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PathPlanQuery) GroupBy(field string, fields ...string) *PathPlanGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PathPlanGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = pathplan.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PlanKey string `json:"plan_key,omitempty"`
//	}
//
//	client.PathPlan.Query().
//		Select(pathplan.FieldPlanKey).
//		Scan(ctx, &v)
func (_q *PathPlanQuery) Select(fields ...string) *PathPlanSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PathPlanSelect{PathPlanQuery: _q}
	sbuild.label = pathplan.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PathPlanSelect configured with the given aggregations.
func (_q *PathPlanQuery) Aggregate(fns ...AggregateFunc) *PathPlanSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PathPlanQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !pathplan.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PathPlanQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PathPlan, error) {
	var (
		nodes       = []*PathPlan{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withWarehouse != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PathPlan).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PathPlan{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withWarehouse; query != nil {
		if err := _q.loadWarehouse(ctx, query, nodes, nil,
			func(n *PathPlan, e *Warehouse) { n.Edges.Warehouse = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PathPlanQuery) loadWarehouse(ctx context.Context, query *WarehouseQuery, nodes []*PathPlan, init func(*PathPlan), assign func(*PathPlan, *Warehouse)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PathPlan)
	for i := range nodes {
		fk := nodes[i].WarehouseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(warehouse.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "warehouse_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PathPlanQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PathPlanQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pathplan.Table, pathplan.Columns, sqlgraph.NewFieldSpec(pathplan.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pathplan.FieldID)
		for i := range fields {
			if fields[i] != pathplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withWarehouse != nil {
			_spec.Node.AddColumnOnce(pathplan.FieldWarehouseID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PathPlanQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(pathplan.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = pathplan.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PathPlanGroupBy is the group-by builder for PathPlan entities.
type PathPlanGroupBy struct {
	selector
	build *PathPlanQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PathPlanGroupBy) Aggregate(fns ...AggregateFunc) *PathPlanGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PathPlanGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PathPlanQuery, *PathPlanGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PathPlanGroupBy) sqlScan(ctx context.Context, root *PathPlanQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PathPlanSelect is the builder for selecting fields of PathPlan entities.
type PathPlanSelect struct {
	*PathPlanQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PathPlanSelect) Aggregate(fns ...AggregateFunc) *PathPlanSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PathPlanSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PathPlanQuery, *PathPlanSelect](ctx, _s.PathPlanQuery, _s, _s.inters, v)
}

func (_s *PathPlanSelect) sqlScan(ctx context.Context, root *PathPlanQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
