// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"warehouse/ent/pathplan"
	"warehouse/ent/warehouse"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PathPlanCreate is the builder for creating a PathPlan entity.
type PathPlanCreate struct {
	config
	mutation *PathPlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlanKey sets the "plan_key" field.
func (_c *PathPlanCreate) SetPlanKey(v string) *PathPlanCreate {
	_c.mutation.SetPlanKey(v)
	return _c
}

// SetTotalDist sets the "total_dist" field.
func (_c *PathPlanCreate) SetTotalDist(v int) *PathPlanCreate {
	_c.mutation.SetTotalDist(v)
	return _c
}

// SetNillableTotalDist sets the "total_dist" field if the given value is not nil.
func (_c *PathPlanCreate) SetNillableTotalDist(v *int) *PathPlanCreate {
	if v != nil {
		_c.SetTotalDist(*v)
	}
	return _c
}

// SetOrderJSON sets the "order_json" field.
func (_c *PathPlanCreate) SetOrderJSON(v string) *PathPlanCreate {
	_c.mutation.SetOrderJSON(v)
	return _c
}

// SetNillableOrderJSON sets the "order_json" field if the given value is not nil.
func (_c *PathPlanCreate) SetNillableOrderJSON(v *string) *PathPlanCreate {
	if v != nil {
		_c.SetOrderJSON(*v)
	}
	return _c
}

// SetSegmentsJSON sets the "segments_json" field.
func (_c *PathPlanCreate) SetSegmentsJSON(v string) *PathPlanCreate {
	_c.mutation.SetSegmentsJSON(v)
	return _c
}

// SetNillableSegmentsJSON sets the "segments_json" field if the given value is not nil.
func (_c *PathPlanCreate) SetNillableSegmentsJSON(v *string) *PathPlanCreate {
	if v != nil {
		_c.SetSegmentsJSON(*v)
	}
	return _c
}

// SetWarehouseID sets the "warehouse_id" field.
func (_c *PathPlanCreate) SetWarehouseID(v int) *PathPlanCreate {
	_c.mutation.SetWarehouseID(v)
	return _c
}

// SetNillableWarehouseID sets the "warehouse_id" field if the given value is not nil.
func (_c *PathPlanCreate) SetNillableWarehouseID(v *int) *PathPlanCreate {
	if v != nil {
		_c.SetWarehouseID(*v)
	}
	return _c
}

// SetWarehouse sets the "warehouse" edge to the Warehouse entity.
func (_c *PathPlanCreate) SetWarehouse(v *Warehouse) *PathPlanCreate {
	return _c.SetWarehouseID(v.ID)
}

// Mutation returns the PathPlanMutation object of the builder.
func (_c *PathPlanCreate) Mutation() *PathPlanMutation {
	return _c.mutation
}

// Save creates the PathPlan in the database.
func (_c *PathPlanCreate) Save(ctx context.Context) (*PathPlan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PathPlanCreate) SaveX(ctx context.Context) *PathPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PathPlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PathPlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PathPlanCreate) defaults() {
	if _, ok := _c.mutation.TotalDist(); !ok {
		v := pathplan.DefaultTotalDist
		_c.mutation.SetTotalDist(v)
	}
	if _, ok := _c.mutation.OrderJSON(); !ok {
		v := pathplan.DefaultOrderJSON
		_c.mutation.SetOrderJSON(v)
	}
	if _, ok := _c.mutation.SegmentsJSON(); !ok {
		v := pathplan.DefaultSegmentsJSON
		_c.mutation.SetSegmentsJSON(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PathPlanCreate) check() error {
	if _, ok := _c.mutation.PlanKey(); !ok {
		return &ValidationError{Name: "plan_key", err: errors.New(`ent: missing required field "PathPlan.plan_key"`)}
	}
	if _, ok := _c.mutation.TotalDist(); !ok {
		return &ValidationError{Name: "total_dist", err: errors.New(`ent: missing required field "PathPlan.total_dist"`)}
	}
	if _, ok := _c.mutation.OrderJSON(); !ok {
		return &ValidationError{Name: "order_json", err: errors.New(`ent: missing required field "PathPlan.order_json"`)}
	}
	if _, ok := _c.mutation.SegmentsJSON(); !ok {
		return &ValidationError{Name: "segments_json", err: errors.New(`ent: missing required field "PathPlan.segments_json"`)}
	}
	return nil
}

func (_c *PathPlanCreate) sqlSave(ctx context.Context) (*PathPlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PathPlanCreate) createSpec() (*PathPlan, *sqlgraph.CreateSpec) {
	var (
		_node = &PathPlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pathplan.Table, sqlgraph.NewFieldSpec(pathplan.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PlanKey(); ok {
		_spec.SetField(pathplan.FieldPlanKey, field.TypeString, value)
		_node.PlanKey = value
	}
	if value, ok := _c.mutation.TotalDist(); ok {
		_spec.SetField(pathplan.FieldTotalDist, field.TypeInt, value)
		_node.TotalDist = value
	}
	if value, ok := _c.mutation.OrderJSON(); ok {
		_spec.SetField(pathplan.FieldOrderJSON, field.TypeString, value)
		_node.OrderJSON = value
	}
	if value, ok := _c.mutation.SegmentsJSON(); ok {
		_spec.SetField(pathplan.FieldSegmentsJSON, field.TypeString, value)
		_node.SegmentsJSON = value
	}
	if nodes := _c.mutation.WarehouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pathplan.WarehouseTable,
			Columns: []string{pathplan.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WarehouseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PathPlan.Create().
//		SetPlanKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PathPlanUpsert) {
//			SetPlanKey(v+v).
//		}).
//		Exec(ctx)
func (_c *PathPlanCreate) OnConflict(opts ...sql.ConflictOption) *PathPlanUpsertOne {
	_c.conflict = opts
	return &PathPlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PathPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PathPlanCreate) OnConflictColumns(columns ...string) *PathPlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PathPlanUpsertOne{
		create: _c,
	}
}

type (
	// PathPlanUpsertOne is the builder for "upsert"-ing
	//  one PathPlan node.
	PathPlanUpsertOne struct {
		create *PathPlanCreate
	}

	// PathPlanUpsert is the "OnConflict" setter.
	PathPlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetPlanKey sets the "plan_key" field.
func (u *PathPlanUpsert) SetPlanKey(v string) *PathPlanUpsert {
	u.Set(pathplan.FieldPlanKey, v)
	return u
}

// UpdatePlanKey sets the "plan_key" field to the value that was provided on create.
func (u *PathPlanUpsert) UpdatePlanKey() *PathPlanUpsert {
	u.SetExcluded(pathplan.FieldPlanKey)
	return u
}

// SetTotalDist sets the "total_dist" field.
func (u *PathPlanUpsert) SetTotalDist(v int) *PathPlanUpsert {
	u.Set(pathplan.FieldTotalDist, v)
	return u
}

// UpdateTotalDist sets the "total_dist" field to the value that was provided on create.
func (u *PathPlanUpsert) UpdateTotalDist() *PathPlanUpsert {
	u.SetExcluded(pathplan.FieldTotalDist)
	return u
}

// AddTotalDist adds v to the "total_dist" field.
func (u *PathPlanUpsert) AddTotalDist(v int) *PathPlanUpsert {
	u.Add(pathplan.FieldTotalDist, v)
	return u
}

// SetOrderJSON sets the "order_json" field.
func (u *PathPlanUpsert) SetOrderJSON(v string) *PathPlanUpsert {
	u.Set(pathplan.FieldOrderJSON, v)
	return u
}

// UpdateOrderJSON sets the "order_json" field to the value that was provided on create.
func (u *PathPlanUpsert) UpdateOrderJSON() *PathPlanUpsert {
	u.SetExcluded(pathplan.FieldOrderJSON)
	return u
}

// SetSegmentsJSON sets the "segments_json" field.
func (u *PathPlanUpsert) SetSegmentsJSON(v string) *PathPlanUpsert {
	u.Set(pathplan.FieldSegmentsJSON, v)
	return u
}

// UpdateSegmentsJSON sets the "segments_json" field to the value that was provided on create.
func (u *PathPlanUpsert) UpdateSegmentsJSON() *PathPlanUpsert {
	u.SetExcluded(pathplan.FieldSegmentsJSON)
	return u
}

// SetWarehouseID sets the "warehouse_id" field.
func (u *PathPlanUpsert) SetWarehouseID(v int) *PathPlanUpsert {
	u.Set(pathplan.FieldWarehouseID, v)
	return u
}

// UpdateWarehouseID sets the "warehouse_id" field to the value that was provided on create.
func (u *PathPlanUpsert) UpdateWarehouseID() *PathPlanUpsert {
	u.SetExcluded(pathplan.FieldWarehouseID)
	return u
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (u *PathPlanUpsert) ClearWarehouseID() *PathPlanUpsert {
	u.SetNull(pathplan.FieldWarehouseID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PathPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PathPlanUpsertOne) UpdateNewValues() *PathPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PathPlan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PathPlanUpsertOne) Ignore() *PathPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PathPlanUpsertOne) DoNothing() *PathPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PathPlanCreate.OnConflict
// documentation for more info.
func (u *PathPlanUpsertOne) Update(set func(*PathPlanUpsert)) *PathPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PathPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlanKey sets the "plan_key" field.
func (u *PathPlanUpsertOne) SetPlanKey(v string) *PathPlanUpsertOne {
	return u.Update(func(s *PathPlanUpsert) {
		s.SetPlanKey(v)
	})
}

// UpdatePlanKey sets the "plan_key" field to the value that was provided on create.
func (u *PathPlanUpsertOne) UpdatePlanKey() *PathPlanUpsertOne {
	return u.Update(func(s *PathPlanUpsert) {
		s.UpdatePlanKey()
	})
}

// SetTotalDist sets the "total_dist" field.
func (u *PathPlanUpsertOne) SetTotalDist(v int) *PathPlanUpsertOne {
	return u.Update(func(s *PathPlanUpsert) {
		s.SetTotalDist(v)
	})
}

// AddTotalDist adds v to the "total_dist" field.
func (u *PathPlanUpsertOne) AddTotalDist(v int) *PathPlanUpsertOne {
	return u.Update(func(s *PathPlanUpsert) {
		s.AddTotalDist(v)
	})
}

// UpdateTotalDist sets the "total_dist" field to the value that was provided on create.
func (u *PathPlanUpsertOne) UpdateTotalDist() *PathPlanUpsertOne {
	return u.Update(func(s *PathPlanUpsert) {
		s.UpdateTotalDist()
	})
}

// SetOrderJSON sets the "order_json" field.
func (u *PathPlanUpsertOne) SetOrderJSON(v string) *PathPlanUpsertOne {
	return u.Update(func(s *PathPlanUpsert) {
		s.SetOrderJSON(v)
	})
}

// UpdateOrderJSON sets the "order_json" field to the value that was provided on create.
func (u *PathPlanUpsertOne) UpdateOrderJSON() *PathPlanUpsertOne {
	return u.Update(func(s *PathPlanUpsert) {
		s.UpdateOrderJSON()
	})
}

// SetSegmentsJSON sets the "segments_json" field.
func (u *PathPlanUpsertOne) SetSegmentsJSON(v string) *PathPlanUpsertOne {
	return u.Update(func(s *PathPlanUpsert) {
		s.SetSegmentsJSON(v)
	})
}

// UpdateSegmentsJSON sets the "segments_json" field to the value that was provided on create.
func (u *PathPlanUpsertOne) UpdateSegmentsJSON() *PathPlanUpsertOne {
	return u.Update(func(s *PathPlanUpsert) {
		s.UpdateSegmentsJSON()
	})
}

// SetWarehouseID sets the "warehouse_id" field.
func (u *PathPlanUpsertOne) SetWarehouseID(v int) *PathPlanUpsertOne {
	return u.Update(func(s *PathPlanUpsert) {
		s.SetWarehouseID(v)
	})
}

// UpdateWarehouseID sets the "warehouse_id" field to the value that was provided on create.
func (u *PathPlanUpsertOne) UpdateWarehouseID() *PathPlanUpsertOne {
	return u.Update(func(s *PathPlanUpsert) {
		s.UpdateWarehouseID()
	})
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (u *PathPlanUpsertOne) ClearWarehouseID() *PathPlanUpsertOne {
	return u.Update(func(s *PathPlanUpsert) {
		s.ClearWarehouseID()
	})
}

// Exec executes the query.
func (u *PathPlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PathPlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PathPlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PathPlanUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PathPlanUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PathPlanCreateBulk is the builder for creating many PathPlan entities in bulk.
type PathPlanCreateBulk struct {
	config
	err      error
	builders []*PathPlanCreate
	conflict []sql.ConflictOption
}

// Save creates the PathPlan entities in the database.
func (_c *PathPlanCreateBulk) Save(ctx context.Context) ([]*PathPlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PathPlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PathPlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PathPlanCreateBulk) SaveX(ctx context.Context) []*PathPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PathPlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PathPlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PathPlan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PathPlanUpsert) {
//			SetPlanKey(v+v).
//		}).
//		Exec(ctx)
func (_c *PathPlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *PathPlanUpsertBulk {
	_c.conflict = opts
	return &PathPlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PathPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PathPlanCreateBulk) OnConflictColumns(columns ...string) *PathPlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PathPlanUpsertBulk{
		create: _c,
	}
}

// PathPlanUpsertBulk is the builder for "upsert"-ing
// a bulk of PathPlan nodes.
type PathPlanUpsertBulk struct {
	create *PathPlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PathPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PathPlanUpsertBulk) UpdateNewValues() *PathPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PathPlan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PathPlanUpsertBulk) Ignore() *PathPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PathPlanUpsertBulk) DoNothing() *PathPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PathPlanCreateBulk.OnConflict
// documentation for more info.
func (u *PathPlanUpsertBulk) Update(set func(*PathPlanUpsert)) *PathPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PathPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlanKey sets the "plan_key" field.
func (u *PathPlanUpsertBulk) SetPlanKey(v string) *PathPlanUpsertBulk {
	return u.Update(func(s *PathPlanUpsert) {
		s.SetPlanKey(v)
	})
}

// UpdatePlanKey sets the "plan_key" field to the value that was provided on create.
func (u *PathPlanUpsertBulk) UpdatePlanKey() *PathPlanUpsertBulk {
	return u.Update(func(s *PathPlanUpsert) {
		s.UpdatePlanKey()
	})
}

// SetTotalDist sets the "total_dist" field.
func (u *PathPlanUpsertBulk) SetTotalDist(v int) *PathPlanUpsertBulk {
	return u.Update(func(s *PathPlanUpsert) {
		s.SetTotalDist(v)
	})
}

// AddTotalDist adds v to the "total_dist" field.
func (u *PathPlanUpsertBulk) AddTotalDist(v int) *PathPlanUpsertBulk {
	return u.Update(func(s *PathPlanUpsert) {
		s.AddTotalDist(v)
	})
}

// UpdateTotalDist sets the "total_dist" field to the value that was provided on create.
func (u *PathPlanUpsertBulk) UpdateTotalDist() *PathPlanUpsertBulk {
	return u.Update(func(s *PathPlanUpsert) {
		s.UpdateTotalDist()
	})
}

// SetOrderJSON sets the "order_json" field.
func (u *PathPlanUpsertBulk) SetOrderJSON(v string) *PathPlanUpsertBulk {
	return u.Update(func(s *PathPlanUpsert) {
		s.SetOrderJSON(v)
	})
}

// UpdateOrderJSON sets the "order_json" field to the value that was provided on create.
func (u *PathPlanUpsertBulk) UpdateOrderJSON() *PathPlanUpsertBulk {
	return u.Update(func(s *PathPlanUpsert) {
		s.UpdateOrderJSON()
	})
}

// SetSegmentsJSON sets the "segments_json" field.
func (u *PathPlanUpsertBulk) SetSegmentsJSON(v string) *PathPlanUpsertBulk {
	return u.Update(func(s *PathPlanUpsert) {
		s.SetSegmentsJSON(v)
	})
}

// UpdateSegmentsJSON sets the "segments_json" field to the value that was provided on create.
func (u *PathPlanUpsertBulk) UpdateSegmentsJSON() *PathPlanUpsertBulk {
	return u.Update(func(s *PathPlanUpsert) {
		s.UpdateSegmentsJSON()
	})
}

// SetWarehouseID sets the "warehouse_id" field.
func (u *PathPlanUpsertBulk) SetWarehouseID(v int) *PathPlanUpsertBulk {
	return u.Update(func(s *PathPlanUpsert) {
		s.SetWarehouseID(v)
	})
}

// UpdateWarehouseID sets the "warehouse_id" field to the value that was provided on create.
func (u *PathPlanUpsertBulk) UpdateWarehouseID() *PathPlanUpsertBulk {
	return u.Update(func(s *PathPlanUpsert) {
		s.UpdateWarehouseID()
	})
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (u *PathPlanUpsertBulk) ClearWarehouseID() *PathPlanUpsertBulk {
	return u.Update(func(s *PathPlanUpsert) {
		s.ClearWarehouseID()
	})
}

// Exec executes the query.
func (u *PathPlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PathPlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PathPlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PathPlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
