// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"warehouse/ent/pathplan"
	"warehouse/ent/predicate"
	"warehouse/ent/warehouse"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PathPlanUpdate is the builder for updating PathPlan entities.
type PathPlanUpdate struct {
	config
	hooks    []Hook
	mutation *PathPlanMutation
}

// Where appends a list predicates to the PathPlanUpdate builder.
func (_u *PathPlanUpdate) Where(ps ...predicate.PathPlan) *PathPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlanKey sets the "plan_key" field.
func (_u *PathPlanUpdate) SetPlanKey(v string) *PathPlanUpdate {
	_u.mutation.SetPlanKey(v)
	return _u
}

// SetNillablePlanKey sets the "plan_key" field if the given value is not nil.
func (_u *PathPlanUpdate) SetNillablePlanKey(v *string) *PathPlanUpdate {
	if v != nil {
		_u.SetPlanKey(*v)
	}
	return _u
}

// SetTotalDist sets the "total_dist" field.
func (_u *PathPlanUpdate) SetTotalDist(v int) *PathPlanUpdate {
	_u.mutation.ResetTotalDist()
	_u.mutation.SetTotalDist(v)
	return _u
}

// SetNillableTotalDist sets the "total_dist" field if the given value is not nil.
func (_u *PathPlanUpdate) SetNillableTotalDist(v *int) *PathPlanUpdate {
	if v != nil {
		_u.SetTotalDist(*v)
	}
	return _u
}

// AddTotalDist adds value to the "total_dist" field.
func (_u *PathPlanUpdate) AddTotalDist(v int) *PathPlanUpdate {
	_u.mutation.AddTotalDist(v)
	return _u
}

// SetOrderJSON sets the "order_json" field.
func (_u *PathPlanUpdate) SetOrderJSON(v string) *PathPlanUpdate {
	_u.mutation.SetOrderJSON(v)
	return _u
}

// SetNillableOrderJSON sets the "order_json" field if the given value is not nil.
func (_u *PathPlanUpdate) SetNillableOrderJSON(v *string) *PathPlanUpdate {
	if v != nil {
		_u.SetOrderJSON(*v)
	}
	return _u
}

// SetSegmentsJSON sets the "segments_json" field.
func (_u *PathPlanUpdate) SetSegmentsJSON(v string) *PathPlanUpdate {
	_u.mutation.SetSegmentsJSON(v)
	return _u
}

// SetNillableSegmentsJSON sets the "segments_json" field if the given value is not nil.
func (_u *PathPlanUpdate) SetNillableSegmentsJSON(v *string) *PathPlanUpdate {
	if v != nil {
		_u.SetSegmentsJSON(*v)
	}
	return _u
}

// SetWarehouseID sets the "warehouse_id" field.
func (_u *PathPlanUpdate) SetWarehouseID(v int) *PathPlanUpdate {
	_u.mutation.SetWarehouseID(v)
	return _u
}

// SetNillableWarehouseID sets the "warehouse_id" field if the given value is not nil.
func (_u *PathPlanUpdate) SetNillableWarehouseID(v *int) *PathPlanUpdate {
	if v != nil {
		_u.SetWarehouseID(*v)
	}
	return _u
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (_u *PathPlanUpdate) ClearWarehouseID() *PathPlanUpdate {
	_u.mutation.ClearWarehouseID()
	return _u
}

// SetWarehouse sets the "warehouse" edge to the Warehouse entity.
func (_u *PathPlanUpdate) SetWarehouse(v *Warehouse) *PathPlanUpdate {
	return _u.SetWarehouseID(v.ID)
}

// Mutation returns the PathPlanMutation object of the builder.
func (_u *PathPlanUpdate) Mutation() *PathPlanMutation {
	return _u.mutation
}

// ClearWarehouse clears the "warehouse" edge to the Warehouse entity.
func (_u *PathPlanUpdate) ClearWarehouse() *PathPlanUpdate {
	_u.mutation.ClearWarehouse()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PathPlanUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PathPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PathPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PathPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PathPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pathplan.Table, pathplan.Columns, sqlgraph.NewFieldSpec(pathplan.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PlanKey(); ok {
		_spec.SetField(pathplan.FieldPlanKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalDist(); ok {
		_spec.SetField(pathplan.FieldTotalDist, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalDist(); ok {
		_spec.AddField(pathplan.FieldTotalDist, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OrderJSON(); ok {
		_spec.SetField(pathplan.FieldOrderJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.SegmentsJSON(); ok {
		_spec.SetField(pathplan.FieldSegmentsJSON, field.TypeString, value)
	}
	if _u.mutation.WarehouseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pathplan.WarehouseTable,
			Columns: []string{pathplan.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WarehouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pathplan.WarehouseTable,
			Columns: []string{pathplan.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pathplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PathPlanUpdateOne is the builder for updating a single PathPlan entity.
type PathPlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PathPlanMutation
}

// SetPlanKey sets the "plan_key" field.
func (_u *PathPlanUpdateOne) SetPlanKey(v string) *PathPlanUpdateOne {
	_u.mutation.SetPlanKey(v)
	return _u
}

// SetNillablePlanKey sets the "plan_key" field if the given value is not nil.
func (_u *PathPlanUpdateOne) SetNillablePlanKey(v *string) *PathPlanUpdateOne {
	if v != nil {
		_u.SetPlanKey(*v)
	}
	return _u
}

// SetTotalDist sets the "total_dist" field.
func (_u *PathPlanUpdateOne) SetTotalDist(v int) *PathPlanUpdateOne {
	_u.mutation.ResetTotalDist()
	_u.mutation.SetTotalDist(v)
	return _u
}

// SetNillableTotalDist sets the "total_dist" field if the given value is not nil.
func (_u *PathPlanUpdateOne) SetNillableTotalDist(v *int) *PathPlanUpdateOne {
	if v != nil {
		_u.SetTotalDist(*v)
	}
	return _u
}

// AddTotalDist adds value to the "total_dist" field.
func (_u *PathPlanUpdateOne) AddTotalDist(v int) *PathPlanUpdateOne {
	_u.mutation.AddTotalDist(v)
	return _u
}

// SetOrderJSON sets the "order_json" field.
func (_u *PathPlanUpdateOne) SetOrderJSON(v string) *PathPlanUpdateOne {
	_u.mutation.SetOrderJSON(v)
	return _u
}

// SetNillableOrderJSON sets the "order_json" field if the given value is not nil.
func (_u *PathPlanUpdateOne) SetNillableOrderJSON(v *string) *PathPlanUpdateOne {
	if v != nil {
		_u.SetOrderJSON(*v)
	}
	return _u
}

// SetSegmentsJSON sets the "segments_json" field.
func (_u *PathPlanUpdateOne) SetSegmentsJSON(v string) *PathPlanUpdateOne {
	_u.mutation.SetSegmentsJSON(v)
	return _u
}

// SetNillableSegmentsJSON sets the "segments_json" field if the given value is not nil.
func (_u *PathPlanUpdateOne) SetNillableSegmentsJSON(v *string) *PathPlanUpdateOne {
	if v != nil {
		_u.SetSegmentsJSON(*v)
	}
	return _u
}

// SetWarehouseID sets the "warehouse_id" field.
func (_u *PathPlanUpdateOne) SetWarehouseID(v int) *PathPlanUpdateOne {
	_u.mutation.SetWarehouseID(v)
	return _u
}

// SetNillableWarehouseID sets the "warehouse_id" field if the given value is not nil.
func (_u *PathPlanUpdateOne) SetNillableWarehouseID(v *int) *PathPlanUpdateOne {
	if v != nil {
		_u.SetWarehouseID(*v)
	}
	return _u
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (_u *PathPlanUpdateOne) ClearWarehouseID() *PathPlanUpdateOne {
	_u.mutation.ClearWarehouseID()
	return _u
}

// SetWarehouse sets the "warehouse" edge to the Warehouse entity.
func (_u *PathPlanUpdateOne) SetWarehouse(v *Warehouse) *PathPlanUpdateOne {
	return _u.SetWarehouseID(v.ID)
}

// Mutation returns the PathPlanMutation object of the builder.
func (_u *PathPlanUpdateOne) Mutation() *PathPlanMutation {
	return _u.mutation
}

// ClearWarehouse clears the "warehouse" edge to the Warehouse entity.
func (_u *PathPlanUpdateOne) ClearWarehouse() *PathPlanUpdateOne {
	_u.mutation.ClearWarehouse()
	return _u
}

// Where appends a list predicates to the PathPlanUpdate builder.
func (_u *PathPlanUpdateOne) Where(ps ...predicate.PathPlan) *PathPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PathPlanUpdateOne) Select(field string, fields ...string) *PathPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PathPlan entity.
func (_u *PathPlanUpdateOne) Save(ctx context.Context) (*PathPlan, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PathPlanUpdateOne) SaveX(ctx context.Context) *PathPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PathPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PathPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PathPlanUpdateOne) sqlSave(ctx context.Context) (_node *PathPlan, err error) {
	_spec := sqlgraph.NewUpdateSpec(pathplan.Table, pathplan.Columns, sqlgraph.NewFieldSpec(pathplan.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PathPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pathplan.FieldID)
		for _, f := range fields {
			if !pathplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pathplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PlanKey(); ok {
		_spec.SetField(pathplan.FieldPlanKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalDist(); ok {
		_spec.SetField(pathplan.FieldTotalDist, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalDist(); ok {
		_spec.AddField(pathplan.FieldTotalDist, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OrderJSON(); ok {
		_spec.SetField(pathplan.FieldOrderJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.SegmentsJSON(); ok {
		_spec.SetField(pathplan.FieldSegmentsJSON, field.TypeString, value)
	}
	if _u.mutation.WarehouseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pathplan.WarehouseTable,
			Columns: []string{pathplan.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WarehouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pathplan.WarehouseTable,
			Columns: []string{pathplan.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PathPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pathplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
