// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"warehouse/ent/goodspackage"
	"warehouse/ent/predicate"
	"warehouse/ent/product"
	"warehouse/ent/shelfunit"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks    []Hook
	mutation *ProductMutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ProductUpdate) SetName(v string) *ProductUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableName(v *string) *ProductUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEan13 sets the "ean13" field.
func (_u *ProductUpdate) SetEan13(v string) *ProductUpdate {
	_u.mutation.SetEan13(v)
	return _u
}

// SetNillableEan13 sets the "ean13" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableEan13(v *string) *ProductUpdate {
	if v != nil {
		_u.SetEan13(*v)
	}
	return _u
}

// ClearEan13 clears the value of the "ean13" field.
func (_u *ProductUpdate) ClearEan13() *ProductUpdate {
	_u.mutation.ClearEan13()
	return _u
}

// SetEan8 sets the "ean8" field.
func (_u *ProductUpdate) SetEan8(v string) *ProductUpdate {
	_u.mutation.SetEan8(v)
	return _u
}

// SetNillableEan8 sets the "ean8" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableEan8(v *string) *ProductUpdate {
	if v != nil {
		_u.SetEan8(*v)
	}
	return _u
}

// ClearEan8 clears the value of the "ean8" field.
func (_u *ProductUpdate) ClearEan8() *ProductUpdate {
	_u.mutation.ClearEan8()
	return _u
}

// SetQrCode sets the "qr_code" field.
func (_u *ProductUpdate) SetQrCode(v string) *ProductUpdate {
	_u.mutation.SetQrCode(v)
	return _u
}

// SetNillableQrCode sets the "qr_code" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableQrCode(v *string) *ProductUpdate {
	if v != nil {
		_u.SetQrCode(*v)
	}
	return _u
}

// ClearQrCode clears the value of the "qr_code" field.
func (_u *ProductUpdate) ClearQrCode() *ProductUpdate {
	_u.mutation.ClearQrCode()
	return _u
}

// AddUnitIDs adds the "units" edge to the ShelfUnit entity by IDs.
func (_u *ProductUpdate) AddUnitIDs(ids ...int) *ProductUpdate {
	_u.mutation.AddUnitIDs(ids...)
	return _u
}

// AddUnits adds the "units" edges to the ShelfUnit entity.
func (_u *ProductUpdate) AddUnits(v ...*ShelfUnit) *ProductUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUnitIDs(ids...)
}

// AddPackageIDs adds the "packages" edge to the GoodsPackage entity by IDs.
func (_u *ProductUpdate) AddPackageIDs(ids ...int) *ProductUpdate {
	_u.mutation.AddPackageIDs(ids...)
	return _u
}

// AddPackages adds the "packages" edges to the GoodsPackage entity.
func (_u *ProductUpdate) AddPackages(v ...*GoodsPackage) *ProductUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPackageIDs(ids...)
}

// Mutation returns the ProductMutation object of the builder.
func (_u *ProductUpdate) Mutation() *ProductMutation {
	return _u.mutation
}

// ClearUnits clears all "units" edges to the ShelfUnit entity.
func (_u *ProductUpdate) ClearUnits() *ProductUpdate {
	_u.mutation.ClearUnits()
	return _u
}

// RemoveUnitIDs removes the "units" edge to ShelfUnit entities by IDs.
func (_u *ProductUpdate) RemoveUnitIDs(ids ...int) *ProductUpdate {
	_u.mutation.RemoveUnitIDs(ids...)
	return _u
}

// RemoveUnits removes "units" edges to ShelfUnit entities.
func (_u *ProductUpdate) RemoveUnits(v ...*ShelfUnit) *ProductUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUnitIDs(ids...)
}

// ClearPackages clears all "packages" edges to the GoodsPackage entity.
func (_u *ProductUpdate) ClearPackages() *ProductUpdate {
	_u.mutation.ClearPackages()
	return _u
}

// RemovePackageIDs removes the "packages" edge to GoodsPackage entities by IDs.
func (_u *ProductUpdate) RemovePackageIDs(ids ...int) *ProductUpdate {
	_u.mutation.RemovePackageIDs(ids...)
	return _u
}

// RemovePackages removes "packages" edges to GoodsPackage entities.
func (_u *ProductUpdate) RemovePackages(v ...*GoodsPackage) *ProductUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePackageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ean13(); ok {
		_spec.SetField(product.FieldEan13, field.TypeString, value)
	}
	if _u.mutation.Ean13Cleared() {
		_spec.ClearField(product.FieldEan13, field.TypeString)
	}
	if value, ok := _u.mutation.Ean8(); ok {
		_spec.SetField(product.FieldEan8, field.TypeString, value)
	}
	if _u.mutation.Ean8Cleared() {
		_spec.ClearField(product.FieldEan8, field.TypeString)
	}
	if value, ok := _u.mutation.QrCode(); ok {
		_spec.SetField(product.FieldQrCode, field.TypeString, value)
	}
	if _u.mutation.QrCodeCleared() {
		_spec.ClearField(product.FieldQrCode, field.TypeString)
	}
	if _u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   product.UnitsTable,
			Columns: []string{product.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUnitsIDs(); len(nodes) > 0 && !_u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   product.UnitsTable,
			Columns: []string{product.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   product.UnitsTable,
			Columns: []string{product.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PackagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.PackagesTable,
			Columns: []string{product.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPackagesIDs(); len(nodes) > 0 && !_u.mutation.PackagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.PackagesTable,
			Columns: []string{product.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PackagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.PackagesTable,
			Columns: []string{product.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductMutation
}

// SetName sets the "name" field.
func (_u *ProductUpdateOne) SetName(v string) *ProductUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableName(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEan13 sets the "ean13" field.
func (_u *ProductUpdateOne) SetEan13(v string) *ProductUpdateOne {
	_u.mutation.SetEan13(v)
	return _u
}

// SetNillableEan13 sets the "ean13" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableEan13(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetEan13(*v)
	}
	return _u
}

// ClearEan13 clears the value of the "ean13" field.
func (_u *ProductUpdateOne) ClearEan13() *ProductUpdateOne {
	_u.mutation.ClearEan13()
	return _u
}

// SetEan8 sets the "ean8" field.
func (_u *ProductUpdateOne) SetEan8(v string) *ProductUpdateOne {
	_u.mutation.SetEan8(v)
	return _u
}

// SetNillableEan8 sets the "ean8" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableEan8(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetEan8(*v)
	}
	return _u
}

// ClearEan8 clears the value of the "ean8" field.
func (_u *ProductUpdateOne) ClearEan8() *ProductUpdateOne {
	_u.mutation.ClearEan8()
	return _u
}

// SetQrCode sets the "qr_code" field.
func (_u *ProductUpdateOne) SetQrCode(v string) *ProductUpdateOne {
	_u.mutation.SetQrCode(v)
	return _u
}

// SetNillableQrCode sets the "qr_code" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableQrCode(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetQrCode(*v)
	}
	return _u
}

// ClearQrCode clears the value of the "qr_code" field.
func (_u *ProductUpdateOne) ClearQrCode() *ProductUpdateOne {
	_u.mutation.ClearQrCode()
	return _u
}

// AddUnitIDs adds the "units" edge to the ShelfUnit entity by IDs.
func (_u *ProductUpdateOne) AddUnitIDs(ids ...int) *ProductUpdateOne {
	_u.mutation.AddUnitIDs(ids...)
	return _u
}

// AddUnits adds the "units" edges to the ShelfUnit entity.
func (_u *ProductUpdateOne) AddUnits(v ...*ShelfUnit) *ProductUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUnitIDs(ids...)
}

// AddPackageIDs adds the "packages" edge to the GoodsPackage entity by IDs.
func (_u *ProductUpdateOne) AddPackageIDs(ids ...int) *ProductUpdateOne {
	_u.mutation.AddPackageIDs(ids...)
	return _u
}

// AddPackages adds the "packages" edges to the GoodsPackage entity.
func (_u *ProductUpdateOne) AddPackages(v ...*GoodsPackage) *ProductUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPackageIDs(ids...)
}

// Mutation returns the ProductMutation object of the builder.
func (_u *ProductUpdateOne) Mutation() *ProductMutation {
	return _u.mutation
}

// ClearUnits clears all "units" edges to the ShelfUnit entity.
func (_u *ProductUpdateOne) ClearUnits() *ProductUpdateOne {
	_u.mutation.ClearUnits()
	return _u
}

// RemoveUnitIDs removes the "units" edge to ShelfUnit entities by IDs.
func (_u *ProductUpdateOne) RemoveUnitIDs(ids ...int) *ProductUpdateOne {
	_u.mutation.RemoveUnitIDs(ids...)
	return _u
}

// RemoveUnits removes "units" edges to ShelfUnit entities.
func (_u *ProductUpdateOne) RemoveUnits(v ...*ShelfUnit) *ProductUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUnitIDs(ids...)
}

// ClearPackages clears all "packages" edges to the GoodsPackage entity.
func (_u *ProductUpdateOne) ClearPackages() *ProductUpdateOne {
	_u.mutation.ClearPackages()
	return _u
}

// RemovePackageIDs removes the "packages" edge to GoodsPackage entities by IDs.
func (_u *ProductUpdateOne) RemovePackageIDs(ids ...int) *ProductUpdateOne {
	_u.mutation.RemovePackageIDs(ids...)
	return _u
}

// RemovePackages removes "packages" edges to GoodsPackage entities.
func (_u *ProductUpdateOne) RemovePackages(v ...*GoodsPackage) *ProductUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePackageIDs(ids...)
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Product entity.
func (_u *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ean13(); ok {
		_spec.SetField(product.FieldEan13, field.TypeString, value)
	}
	if _u.mutation.Ean13Cleared() {
		_spec.ClearField(product.FieldEan13, field.TypeString)
	}
	if value, ok := _u.mutation.Ean8(); ok {
		_spec.SetField(product.FieldEan8, field.TypeString, value)
	}
	if _u.mutation.Ean8Cleared() {
		_spec.ClearField(product.FieldEan8, field.TypeString)
	}
	if value, ok := _u.mutation.QrCode(); ok {
		_spec.SetField(product.FieldQrCode, field.TypeString, value)
	}
	if _u.mutation.QrCodeCleared() {
		_spec.ClearField(product.FieldQrCode, field.TypeString)
	}
	if _u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   product.UnitsTable,
			Columns: []string{product.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUnitsIDs(); len(nodes) > 0 && !_u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   product.UnitsTable,
			Columns: []string{product.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   product.UnitsTable,
			Columns: []string{product.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PackagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.PackagesTable,
			Columns: []string{product.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPackagesIDs(); len(nodes) > 0 && !_u.mutation.PackagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.PackagesTable,
			Columns: []string{product.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PackagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.PackagesTable,
			Columns: []string{product.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Product{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
