// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"warehouse/ent/product"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Product is the model entity for the Product schema.
type Product struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 商品名称
	Name string `json:"name,omitempty"`
	// EAN-13 商品码
	Ean13 string `json:"ean13,omitempty"`
	// EAN-8 商品码
	Ean8 string `json:"ean8,omitempty"`
	// QR code 内容
	QrCode string `json:"qr_code,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProductQuery when eager-loading is set.
	Edges        ProductEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProductEdges holds the relations/edges for other nodes in the graph.
type ProductEdges struct {
	// 存放该商品的货架单元
	Units []*ShelfUnit `json:"units,omitempty"`
	// 该商品的包裹
	Packages []*GoodsPackage `json:"packages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UnitsOrErr returns the Units value or an error if the edge
// was not loaded in eager-loading.
func (e ProductEdges) UnitsOrErr() ([]*ShelfUnit, error) {
	if e.loadedTypes[0] {
		return e.Units, nil
	}
	return nil, &NotLoadedError{edge: "units"}
}

// PackagesOrErr returns the Packages value or an error if the edge
// was not loaded in eager-loading.
func (e ProductEdges) PackagesOrErr() ([]*GoodsPackage, error) {
	if e.loadedTypes[1] {
		return e.Packages, nil
	}
	return nil, &NotLoadedError{edge: "packages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Product) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case product.FieldID:
			values[i] = new(sql.NullInt64)
		case product.FieldName, product.FieldEan13, product.FieldEan8, product.FieldQrCode:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Product fields.
func (_m *Product) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case product.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case product.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case product.FieldEan13:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ean13", values[i])
			} else if value.Valid {
				_m.Ean13 = value.String
			}
		case product.FieldEan8:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ean8", values[i])
			} else if value.Valid {
				_m.Ean8 = value.String
			}
		case product.FieldQrCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field qr_code", values[i])
			} else if value.Valid {
				_m.QrCode = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Product.
// This includes values selected through modifiers, order, etc.
func (_m *Product) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUnits queries the "units" edge of the Product entity.
func (_m *Product) QueryUnits() *ShelfUnitQuery {
	return NewProductClient(_m.config).QueryUnits(_m)
}

// QueryPackages queries the "packages" edge of the Product entity.
func (_m *Product) QueryPackages() *GoodsPackageQuery {
	return NewProductClient(_m.config).QueryPackages(_m)
}

// Update returns a builder for updating this Product.
// Note that you need to call Product.Unwrap() before calling this method if this Product
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Product) Update() *ProductUpdateOne {
	return NewProductClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Product entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Product) Unwrap() *Product {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Product is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Product) String() string {
	var builder strings.Builder
	builder.WriteString("Product(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("ean13=")
	builder.WriteString(_m.Ean13)
	builder.WriteString(", ")
	builder.WriteString("ean8=")
	builder.WriteString(_m.Ean8)
	builder.WriteString(", ")
	builder.WriteString("qr_code=")
	builder.WriteString(_m.QrCode)
	builder.WriteByte(')')
	return builder.String()
}

// Products is a parsable slice of Product.
type Products []*Product
