// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"warehouse/ent/goodspackage"
	"warehouse/ent/shelf"
	"warehouse/ent/shelfunit"
	"warehouse/ent/warehouse"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShelfCreate is the builder for creating a Shelf entity.
type ShelfCreate struct {
	config
	mutation *ShelfMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetShelfNumber sets the "shelf_number" field.
func (_c *ShelfCreate) SetShelfNumber(v int) *ShelfCreate {
	_c.mutation.SetShelfNumber(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *ShelfCreate) SetLabel(v string) *ShelfCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *ShelfCreate) SetNillableLabel(v *string) *ShelfCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetBold sets the "bold" field.
func (_c *ShelfCreate) SetBold(v bool) *ShelfCreate {
	_c.mutation.SetBold(v)
	return _c
}

// SetNillableBold sets the "bold" field if the given value is not nil.
func (_c *ShelfCreate) SetNillableBold(v *bool) *ShelfCreate {
	if v != nil {
		_c.SetBold(*v)
	}
	return _c
}

// SetCol sets the "col" field.
func (_c *ShelfCreate) SetCol(v int) *ShelfCreate {
	_c.mutation.SetCol(v)
	return _c
}

// SetNillableCol sets the "col" field if the given value is not nil.
func (_c *ShelfCreate) SetNillableCol(v *int) *ShelfCreate {
	if v != nil {
		_c.SetCol(*v)
	}
	return _c
}

// SetRow sets the "row" field.
func (_c *ShelfCreate) SetRow(v int) *ShelfCreate {
	_c.mutation.SetRow(v)
	return _c
}

// SetNillableRow sets the "row" field if the given value is not nil.
func (_c *ShelfCreate) SetNillableRow(v *int) *ShelfCreate {
	if v != nil {
		_c.SetRow(*v)
	}
	return _c
}

// SetWidth sets the "width" field.
func (_c *ShelfCreate) SetWidth(v int) *ShelfCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *ShelfCreate) SetNillableWidth(v *int) *ShelfCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *ShelfCreate) SetHeight(v int) *ShelfCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *ShelfCreate) SetNillableHeight(v *int) *ShelfCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetIsHorizontal sets the "is_horizontal" field.
func (_c *ShelfCreate) SetIsHorizontal(v bool) *ShelfCreate {
	_c.mutation.SetIsHorizontal(v)
	return _c
}

// SetNillableIsHorizontal sets the "is_horizontal" field if the given value is not nil.
func (_c *ShelfCreate) SetNillableIsHorizontal(v *bool) *ShelfCreate {
	if v != nil {
		_c.SetIsHorizontal(*v)
	}
	return _c
}

// SetIsVerticalLong sets the "is_vertical_long" field.
func (_c *ShelfCreate) SetIsVerticalLong(v bool) *ShelfCreate {
	_c.mutation.SetIsVerticalLong(v)
	return _c
}

// SetNillableIsVerticalLong sets the "is_vertical_long" field if the given value is not nil.
func (_c *ShelfCreate) SetNillableIsVerticalLong(v *bool) *ShelfCreate {
	if v != nil {
		_c.SetIsVerticalLong(*v)
	}
	return _c
}

// SetWarehouseID sets the "warehouse_id" field.
func (_c *ShelfCreate) SetWarehouseID(v int) *ShelfCreate {
	_c.mutation.SetWarehouseID(v)
	return _c
}

// SetNillableWarehouseID sets the "warehouse_id" field if the given value is not nil.
func (_c *ShelfCreate) SetNillableWarehouseID(v *int) *ShelfCreate {
	if v != nil {
		_c.SetWarehouseID(*v)
	}
	return _c
}

// SetWarehouse sets the "warehouse" edge to the Warehouse entity.
func (_c *ShelfCreate) SetWarehouse(v *Warehouse) *ShelfCreate {
	return _c.SetWarehouseID(v.ID)
}

// AddUnitIDs adds the "units" edge to the ShelfUnit entity by IDs.
func (_c *ShelfCreate) AddUnitIDs(ids ...int) *ShelfCreate {
	_c.mutation.AddUnitIDs(ids...)
	return _c
}

// AddUnits adds the "units" edges to the ShelfUnit entity.
func (_c *ShelfCreate) AddUnits(v ...*ShelfUnit) *ShelfCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUnitIDs(ids...)
}

// AddPackageIDs adds the "packages" edge to the GoodsPackage entity by IDs.
func (_c *ShelfCreate) AddPackageIDs(ids ...int) *ShelfCreate {
	_c.mutation.AddPackageIDs(ids...)
	return _c
}

// AddPackages adds the "packages" edges to the GoodsPackage entity.
func (_c *ShelfCreate) AddPackages(v ...*GoodsPackage) *ShelfCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPackageIDs(ids...)
}

// Mutation returns the ShelfMutation object of the builder.
func (_c *ShelfCreate) Mutation() *ShelfMutation {
	return _c.mutation
}

// Save creates the Shelf in the database.
func (_c *ShelfCreate) Save(ctx context.Context) (*Shelf, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShelfCreate) SaveX(ctx context.Context) *Shelf {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShelfCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShelfCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShelfCreate) defaults() {
	if _, ok := _c.mutation.Label(); !ok {
		v := shelf.DefaultLabel
		_c.mutation.SetLabel(v)
	}
	if _, ok := _c.mutation.Bold(); !ok {
		v := shelf.DefaultBold
		_c.mutation.SetBold(v)
	}
	if _, ok := _c.mutation.Col(); !ok {
		v := shelf.DefaultCol
		_c.mutation.SetCol(v)
	}
	if _, ok := _c.mutation.Row(); !ok {
		v := shelf.DefaultRow
		_c.mutation.SetRow(v)
	}
	if _, ok := _c.mutation.Width(); !ok {
		v := shelf.DefaultWidth
		_c.mutation.SetWidth(v)
	}
	if _, ok := _c.mutation.Height(); !ok {
		v := shelf.DefaultHeight
		_c.mutation.SetHeight(v)
	}
	if _, ok := _c.mutation.IsHorizontal(); !ok {
		v := shelf.DefaultIsHorizontal
		_c.mutation.SetIsHorizontal(v)
	}
	if _, ok := _c.mutation.IsVerticalLong(); !ok {
		v := shelf.DefaultIsVerticalLong
		_c.mutation.SetIsVerticalLong(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShelfCreate) check() error {
	if _, ok := _c.mutation.ShelfNumber(); !ok {
		return &ValidationError{Name: "shelf_number", err: errors.New(`ent: missing required field "Shelf.shelf_number"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "Shelf.label"`)}
	}
	if _, ok := _c.mutation.Bold(); !ok {
		return &ValidationError{Name: "bold", err: errors.New(`ent: missing required field "Shelf.bold"`)}
	}
	if _, ok := _c.mutation.Col(); !ok {
		return &ValidationError{Name: "col", err: errors.New(`ent: missing required field "Shelf.col"`)}
	}
	if _, ok := _c.mutation.Row(); !ok {
		return &ValidationError{Name: "row", err: errors.New(`ent: missing required field "Shelf.row"`)}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "Shelf.width"`)}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "Shelf.height"`)}
	}
	if _, ok := _c.mutation.IsHorizontal(); !ok {
		return &ValidationError{Name: "is_horizontal", err: errors.New(`ent: missing required field "Shelf.is_horizontal"`)}
	}
	if _, ok := _c.mutation.IsVerticalLong(); !ok {
		return &ValidationError{Name: "is_vertical_long", err: errors.New(`ent: missing required field "Shelf.is_vertical_long"`)}
	}
	return nil
}

func (_c *ShelfCreate) sqlSave(ctx context.Context) (*Shelf, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShelfCreate) createSpec() (*Shelf, *sqlgraph.CreateSpec) {
	var (
		_node = &Shelf{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shelf.Table, sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ShelfNumber(); ok {
		_spec.SetField(shelf.FieldShelfNumber, field.TypeInt, value)
		_node.ShelfNumber = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(shelf.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Bold(); ok {
		_spec.SetField(shelf.FieldBold, field.TypeBool, value)
		_node.Bold = value
	}
	if value, ok := _c.mutation.Col(); ok {
		_spec.SetField(shelf.FieldCol, field.TypeInt, value)
		_node.Col = value
	}
	if value, ok := _c.mutation.Row(); ok {
		_spec.SetField(shelf.FieldRow, field.TypeInt, value)
		_node.Row = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(shelf.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(shelf.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.IsHorizontal(); ok {
		_spec.SetField(shelf.FieldIsHorizontal, field.TypeBool, value)
		_node.IsHorizontal = value
	}
	if value, ok := _c.mutation.IsVerticalLong(); ok {
		_spec.SetField(shelf.FieldIsVerticalLong, field.TypeBool, value)
		_node.IsVerticalLong = value
	}
	if nodes := _c.mutation.WarehouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shelf.WarehouseTable,
			Columns: []string{shelf.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WarehouseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.UnitsTable,
			Columns: []string{shelf.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PackagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.PackagesTable,
			Columns: []string{shelf.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Shelf.Create().
//		SetShelfNumber(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShelfUpsert) {
//			SetShelfNumber(v+v).
//		}).
//		Exec(ctx)
func (_c *ShelfCreate) OnConflict(opts ...sql.ConflictOption) *ShelfUpsertOne {
	_c.conflict = opts
	return &ShelfUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Shelf.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShelfCreate) OnConflictColumns(columns ...string) *ShelfUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShelfUpsertOne{
		create: _c,
	}
}

type (
	// ShelfUpsertOne is the builder for "upsert"-ing
	//  one Shelf node.
	ShelfUpsertOne struct {
		create *ShelfCreate
	}

	// ShelfUpsert is the "OnConflict" setter.
	ShelfUpsert struct {
		*sql.UpdateSet
	}
)

// SetShelfNumber sets the "shelf_number" field.
func (u *ShelfUpsert) SetShelfNumber(v int) *ShelfUpsert {
	u.Set(shelf.FieldShelfNumber, v)
	return u
}

// UpdateShelfNumber sets the "shelf_number" field to the value that was provided on create.
func (u *ShelfUpsert) UpdateShelfNumber() *ShelfUpsert {
	u.SetExcluded(shelf.FieldShelfNumber)
	return u
}

// AddShelfNumber adds v to the "shelf_number" field.
func (u *ShelfUpsert) AddShelfNumber(v int) *ShelfUpsert {
	u.Add(shelf.FieldShelfNumber, v)
	return u
}

// SetLabel sets the "label" field.
func (u *ShelfUpsert) SetLabel(v string) *ShelfUpsert {
	u.Set(shelf.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *ShelfUpsert) UpdateLabel() *ShelfUpsert {
	u.SetExcluded(shelf.FieldLabel)
	return u
}

// SetBold sets the "bold" field.
func (u *ShelfUpsert) SetBold(v bool) *ShelfUpsert {
	u.Set(shelf.FieldBold, v)
	return u
}

// UpdateBold sets the "bold" field to the value that was provided on create.
func (u *ShelfUpsert) UpdateBold() *ShelfUpsert {
	u.SetExcluded(shelf.FieldBold)
	return u
}

// SetCol sets the "col" field.
func (u *ShelfUpsert) SetCol(v int) *ShelfUpsert {
	u.Set(shelf.FieldCol, v)
	return u
}

// UpdateCol sets the "col" field to the value that was provided on create.
func (u *ShelfUpsert) UpdateCol() *ShelfUpsert {
	u.SetExcluded(shelf.FieldCol)
	return u
}

// AddCol adds v to the "col" field.
func (u *ShelfUpsert) AddCol(v int) *ShelfUpsert {
	u.Add(shelf.FieldCol, v)
	return u
}

// SetRow sets the "row" field.
func (u *ShelfUpsert) SetRow(v int) *ShelfUpsert {
	u.Set(shelf.FieldRow, v)
	return u
}

// UpdateRow sets the "row" field to the value that was provided on create.
func (u *ShelfUpsert) UpdateRow() *ShelfUpsert {
	u.SetExcluded(shelf.FieldRow)
	return u
}

// AddRow adds v to the "row" field.
func (u *ShelfUpsert) AddRow(v int) *ShelfUpsert {
	u.Add(shelf.FieldRow, v)
	return u
}

// SetWidth sets the "width" field.
func (u *ShelfUpsert) SetWidth(v int) *ShelfUpsert {
	u.Set(shelf.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ShelfUpsert) UpdateWidth() *ShelfUpsert {
	u.SetExcluded(shelf.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *ShelfUpsert) AddWidth(v int) *ShelfUpsert {
	u.Add(shelf.FieldWidth, v)
	return u
}

// SetHeight sets the "height" field.
func (u *ShelfUpsert) SetHeight(v int) *ShelfUpsert {
	u.Set(shelf.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ShelfUpsert) UpdateHeight() *ShelfUpsert {
	u.SetExcluded(shelf.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *ShelfUpsert) AddHeight(v int) *ShelfUpsert {
	u.Add(shelf.FieldHeight, v)
	return u
}

// SetIsHorizontal sets the "is_horizontal" field.
func (u *ShelfUpsert) SetIsHorizontal(v bool) *ShelfUpsert {
	u.Set(shelf.FieldIsHorizontal, v)
	return u
}

// UpdateIsHorizontal sets the "is_horizontal" field to the value that was provided on create.
func (u *ShelfUpsert) UpdateIsHorizontal() *ShelfUpsert {
	u.SetExcluded(shelf.FieldIsHorizontal)
	return u
}

// SetIsVerticalLong sets the "is_vertical_long" field.
func (u *ShelfUpsert) SetIsVerticalLong(v bool) *ShelfUpsert {
	u.Set(shelf.FieldIsVerticalLong, v)
	return u
}

// UpdateIsVerticalLong sets the "is_vertical_long" field to the value that was provided on create.
func (u *ShelfUpsert) UpdateIsVerticalLong() *ShelfUpsert {
	u.SetExcluded(shelf.FieldIsVerticalLong)
	return u
}

// SetWarehouseID sets the "warehouse_id" field.
func (u *ShelfUpsert) SetWarehouseID(v int) *ShelfUpsert {
	u.Set(shelf.FieldWarehouseID, v)
	return u
}

// UpdateWarehouseID sets the "warehouse_id" field to the value that was provided on create.
func (u *ShelfUpsert) UpdateWarehouseID() *ShelfUpsert {
	u.SetExcluded(shelf.FieldWarehouseID)
	return u
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (u *ShelfUpsert) ClearWarehouseID() *ShelfUpsert {
	u.SetNull(shelf.FieldWarehouseID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Shelf.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ShelfUpsertOne) UpdateNewValues() *ShelfUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Shelf.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ShelfUpsertOne) Ignore() *ShelfUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShelfUpsertOne) DoNothing() *ShelfUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShelfCreate.OnConflict
// documentation for more info.
func (u *ShelfUpsertOne) Update(set func(*ShelfUpsert)) *ShelfUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShelfUpsert{UpdateSet: update})
	}))
	return u
}

// SetShelfNumber sets the "shelf_number" field.
func (u *ShelfUpsertOne) SetShelfNumber(v int) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.SetShelfNumber(v)
	})
}

// AddShelfNumber adds v to the "shelf_number" field.
func (u *ShelfUpsertOne) AddShelfNumber(v int) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.AddShelfNumber(v)
	})
}

// UpdateShelfNumber sets the "shelf_number" field to the value that was provided on create.
func (u *ShelfUpsertOne) UpdateShelfNumber() *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateShelfNumber()
	})
}

// SetLabel sets the "label" field.
func (u *ShelfUpsertOne) SetLabel(v string) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *ShelfUpsertOne) UpdateLabel() *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateLabel()
	})
}

// SetBold sets the "bold" field.
func (u *ShelfUpsertOne) SetBold(v bool) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.SetBold(v)
	})
}

// UpdateBold sets the "bold" field to the value that was provided on create.
func (u *ShelfUpsertOne) UpdateBold() *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateBold()
	})
}

// SetCol sets the "col" field.
func (u *ShelfUpsertOne) SetCol(v int) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.SetCol(v)
	})
}

// AddCol adds v to the "col" field.
func (u *ShelfUpsertOne) AddCol(v int) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.AddCol(v)
	})
}

// UpdateCol sets the "col" field to the value that was provided on create.
func (u *ShelfUpsertOne) UpdateCol() *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateCol()
	})
}

// SetRow sets the "row" field.
func (u *ShelfUpsertOne) SetRow(v int) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.SetRow(v)
	})
}

// AddRow adds v to the "row" field.
func (u *ShelfUpsertOne) AddRow(v int) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.AddRow(v)
	})
}

// UpdateRow sets the "row" field to the value that was provided on create.
func (u *ShelfUpsertOne) UpdateRow() *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateRow()
	})
}

// SetWidth sets the "width" field.
func (u *ShelfUpsertOne) SetWidth(v int) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ShelfUpsertOne) AddWidth(v int) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ShelfUpsertOne) UpdateWidth() *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ShelfUpsertOne) SetHeight(v int) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ShelfUpsertOne) AddHeight(v int) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ShelfUpsertOne) UpdateHeight() *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateHeight()
	})
}

// SetIsHorizontal sets the "is_horizontal" field.
func (u *ShelfUpsertOne) SetIsHorizontal(v bool) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.SetIsHorizontal(v)
	})
}

// UpdateIsHorizontal sets the "is_horizontal" field to the value that was provided on create.
func (u *ShelfUpsertOne) UpdateIsHorizontal() *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateIsHorizontal()
	})
}

// SetIsVerticalLong sets the "is_vertical_long" field.
func (u *ShelfUpsertOne) SetIsVerticalLong(v bool) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.SetIsVerticalLong(v)
	})
}

// UpdateIsVerticalLong sets the "is_vertical_long" field to the value that was provided on create.
func (u *ShelfUpsertOne) UpdateIsVerticalLong() *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateIsVerticalLong()
	})
}

// SetWarehouseID sets the "warehouse_id" field.
func (u *ShelfUpsertOne) SetWarehouseID(v int) *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.SetWarehouseID(v)
	})
}

// UpdateWarehouseID sets the "warehouse_id" field to the value that was provided on create.
func (u *ShelfUpsertOne) UpdateWarehouseID() *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateWarehouseID()
	})
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (u *ShelfUpsertOne) ClearWarehouseID() *ShelfUpsertOne {
	return u.Update(func(s *ShelfUpsert) {
		s.ClearWarehouseID()
	})
}

// Exec executes the query.
func (u *ShelfUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShelfCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShelfUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ShelfUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ShelfUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ShelfCreateBulk is the builder for creating many Shelf entities in bulk.
type ShelfCreateBulk struct {
	config
	err      error
	builders []*ShelfCreate
	conflict []sql.ConflictOption
}

// Save creates the Shelf entities in the database.
func (_c *ShelfCreateBulk) Save(ctx context.Context) ([]*Shelf, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Shelf, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShelfMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShelfCreateBulk) SaveX(ctx context.Context) []*Shelf {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShelfCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShelfCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Shelf.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShelfUpsert) {
//			SetShelfNumber(v+v).
//		}).
//		Exec(ctx)
func (_c *ShelfCreateBulk) OnConflict(opts ...sql.ConflictOption) *ShelfUpsertBulk {
	_c.conflict = opts
	return &ShelfUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Shelf.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShelfCreateBulk) OnConflictColumns(columns ...string) *ShelfUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShelfUpsertBulk{
		create: _c,
	}
}

// ShelfUpsertBulk is the builder for "upsert"-ing
// a bulk of Shelf nodes.
type ShelfUpsertBulk struct {
	create *ShelfCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Shelf.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ShelfUpsertBulk) UpdateNewValues() *ShelfUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Shelf.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ShelfUpsertBulk) Ignore() *ShelfUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShelfUpsertBulk) DoNothing() *ShelfUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShelfCreateBulk.OnConflict
// documentation for more info.
func (u *ShelfUpsertBulk) Update(set func(*ShelfUpsert)) *ShelfUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShelfUpsert{UpdateSet: update})
	}))
	return u
}

// SetShelfNumber sets the "shelf_number" field.
func (u *ShelfUpsertBulk) SetShelfNumber(v int) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.SetShelfNumber(v)
	})
}

// AddShelfNumber adds v to the "shelf_number" field.
func (u *ShelfUpsertBulk) AddShelfNumber(v int) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.AddShelfNumber(v)
	})
}

// UpdateShelfNumber sets the "shelf_number" field to the value that was provided on create.
func (u *ShelfUpsertBulk) UpdateShelfNumber() *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateShelfNumber()
	})
}

// SetLabel sets the "label" field.
func (u *ShelfUpsertBulk) SetLabel(v string) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *ShelfUpsertBulk) UpdateLabel() *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateLabel()
	})
}

// SetBold sets the "bold" field.
func (u *ShelfUpsertBulk) SetBold(v bool) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.SetBold(v)
	})
}

// UpdateBold sets the "bold" field to the value that was provided on create.
func (u *ShelfUpsertBulk) UpdateBold() *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateBold()
	})
}

// SetCol sets the "col" field.
func (u *ShelfUpsertBulk) SetCol(v int) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.SetCol(v)
	})
}

// AddCol adds v to the "col" field.
func (u *ShelfUpsertBulk) AddCol(v int) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.AddCol(v)
	})
}

// UpdateCol sets the "col" field to the value that was provided on create.
func (u *ShelfUpsertBulk) UpdateCol() *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateCol()
	})
}

// SetRow sets the "row" field.
func (u *ShelfUpsertBulk) SetRow(v int) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.SetRow(v)
	})
}

// AddRow adds v to the "row" field.
func (u *ShelfUpsertBulk) AddRow(v int) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.AddRow(v)
	})
}

// UpdateRow sets the "row" field to the value that was provided on create.
func (u *ShelfUpsertBulk) UpdateRow() *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateRow()
	})
}

// SetWidth sets the "width" field.
func (u *ShelfUpsertBulk) SetWidth(v int) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ShelfUpsertBulk) AddWidth(v int) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ShelfUpsertBulk) UpdateWidth() *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ShelfUpsertBulk) SetHeight(v int) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ShelfUpsertBulk) AddHeight(v int) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ShelfUpsertBulk) UpdateHeight() *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateHeight()
	})
}

// SetIsHorizontal sets the "is_horizontal" field.
func (u *ShelfUpsertBulk) SetIsHorizontal(v bool) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.SetIsHorizontal(v)
	})
}

// UpdateIsHorizontal sets the "is_horizontal" field to the value that was provided on create.
func (u *ShelfUpsertBulk) UpdateIsHorizontal() *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateIsHorizontal()
	})
}

// SetIsVerticalLong sets the "is_vertical_long" field.
func (u *ShelfUpsertBulk) SetIsVerticalLong(v bool) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.SetIsVerticalLong(v)
	})
}

// UpdateIsVerticalLong sets the "is_vertical_long" field to the value that was provided on create.
func (u *ShelfUpsertBulk) UpdateIsVerticalLong() *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateIsVerticalLong()
	})
}

// SetWarehouseID sets the "warehouse_id" field.
func (u *ShelfUpsertBulk) SetWarehouseID(v int) *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.SetWarehouseID(v)
	})
}

// UpdateWarehouseID sets the "warehouse_id" field to the value that was provided on create.
func (u *ShelfUpsertBulk) UpdateWarehouseID() *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.UpdateWarehouseID()
	})
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (u *ShelfUpsertBulk) ClearWarehouseID() *ShelfUpsertBulk {
	return u.Update(func(s *ShelfUpsert) {
		s.ClearWarehouseID()
	})
}

// Exec executes the query.
func (u *ShelfUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ShelfCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShelfCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShelfUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
