// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"warehouse/ent/goodspackage"
	"warehouse/ent/predicate"
	"warehouse/ent/shelf"
	"warehouse/ent/shelfunit"
	"warehouse/ent/warehouse"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShelfUpdate is the builder for updating Shelf entities.
type ShelfUpdate struct {
	config
	hooks    []Hook
	mutation *ShelfMutation
}

// Where appends a list predicates to the ShelfUpdate builder.
func (_u *ShelfUpdate) Where(ps ...predicate.Shelf) *ShelfUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetShelfNumber sets the "shelf_number" field.
func (_u *ShelfUpdate) SetShelfNumber(v int) *ShelfUpdate {
	_u.mutation.ResetShelfNumber()
	_u.mutation.SetShelfNumber(v)
	return _u
}

// SetNillableShelfNumber sets the "shelf_number" field if the given value is not nil.
func (_u *ShelfUpdate) SetNillableShelfNumber(v *int) *ShelfUpdate {
	if v != nil {
		_u.SetShelfNumber(*v)
	}
	return _u
}

// AddShelfNumber adds value to the "shelf_number" field.
func (_u *ShelfUpdate) AddShelfNumber(v int) *ShelfUpdate {
	_u.mutation.AddShelfNumber(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *ShelfUpdate) SetLabel(v string) *ShelfUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *ShelfUpdate) SetNillableLabel(v *string) *ShelfUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetBold sets the "bold" field.
func (_u *ShelfUpdate) SetBold(v bool) *ShelfUpdate {
	_u.mutation.SetBold(v)
	return _u
}

// SetNillableBold sets the "bold" field if the given value is not nil.
func (_u *ShelfUpdate) SetNillableBold(v *bool) *ShelfUpdate {
	if v != nil {
		_u.SetBold(*v)
	}
	return _u
}

// SetCol sets the "col" field.
func (_u *ShelfUpdate) SetCol(v int) *ShelfUpdate {
	_u.mutation.ResetCol()
	_u.mutation.SetCol(v)
	return _u
}

// SetNillableCol sets the "col" field if the given value is not nil.
func (_u *ShelfUpdate) SetNillableCol(v *int) *ShelfUpdate {
	if v != nil {
		_u.SetCol(*v)
	}
	return _u
}

// AddCol adds value to the "col" field.
func (_u *ShelfUpdate) AddCol(v int) *ShelfUpdate {
	_u.mutation.AddCol(v)
	return _u
}

// SetRow sets the "row" field.
func (_u *ShelfUpdate) SetRow(v int) *ShelfUpdate {
	_u.mutation.ResetRow()
	_u.mutation.SetRow(v)
	return _u
}

// SetNillableRow sets the "row" field if the given value is not nil.
func (_u *ShelfUpdate) SetNillableRow(v *int) *ShelfUpdate {
	if v != nil {
		_u.SetRow(*v)
	}
	return _u
}

// AddRow adds value to the "row" field.
func (_u *ShelfUpdate) AddRow(v int) *ShelfUpdate {
	_u.mutation.AddRow(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *ShelfUpdate) SetWidth(v int) *ShelfUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ShelfUpdate) SetNillableWidth(v *int) *ShelfUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ShelfUpdate) AddWidth(v int) *ShelfUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *ShelfUpdate) SetHeight(v int) *ShelfUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ShelfUpdate) SetNillableHeight(v *int) *ShelfUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ShelfUpdate) AddHeight(v int) *ShelfUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// SetIsHorizontal sets the "is_horizontal" field.
func (_u *ShelfUpdate) SetIsHorizontal(v bool) *ShelfUpdate {
	_u.mutation.SetIsHorizontal(v)
	return _u
}

// SetNillableIsHorizontal sets the "is_horizontal" field if the given value is not nil.
func (_u *ShelfUpdate) SetNillableIsHorizontal(v *bool) *ShelfUpdate {
	if v != nil {
		_u.SetIsHorizontal(*v)
	}
	return _u
}

// SetIsVerticalLong sets the "is_vertical_long" field.
func (_u *ShelfUpdate) SetIsVerticalLong(v bool) *ShelfUpdate {
	_u.mutation.SetIsVerticalLong(v)
	return _u
}

// SetNillableIsVerticalLong sets the "is_vertical_long" field if the given value is not nil.
func (_u *ShelfUpdate) SetNillableIsVerticalLong(v *bool) *ShelfUpdate {
	if v != nil {
		_u.SetIsVerticalLong(*v)
	}
	return _u
}

// SetWarehouseID sets the "warehouse_id" field.
func (_u *ShelfUpdate) SetWarehouseID(v int) *ShelfUpdate {
	_u.mutation.SetWarehouseID(v)
	return _u
}

// SetNillableWarehouseID sets the "warehouse_id" field if the given value is not nil.
func (_u *ShelfUpdate) SetNillableWarehouseID(v *int) *ShelfUpdate {
	if v != nil {
		_u.SetWarehouseID(*v)
	}
	return _u
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (_u *ShelfUpdate) ClearWarehouseID() *ShelfUpdate {
	_u.mutation.ClearWarehouseID()
	return _u
}

// SetWarehouse sets the "warehouse" edge to the Warehouse entity.
func (_u *ShelfUpdate) SetWarehouse(v *Warehouse) *ShelfUpdate {
	return _u.SetWarehouseID(v.ID)
}

// AddUnitIDs adds the "units" edge to the ShelfUnit entity by IDs.
func (_u *ShelfUpdate) AddUnitIDs(ids ...int) *ShelfUpdate {
	_u.mutation.AddUnitIDs(ids...)
	return _u
}

// AddUnits adds the "units" edges to the ShelfUnit entity.
func (_u *ShelfUpdate) AddUnits(v ...*ShelfUnit) *ShelfUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUnitIDs(ids...)
}

// AddPackageIDs adds the "packages" edge to the GoodsPackage entity by IDs.
func (_u *ShelfUpdate) AddPackageIDs(ids ...int) *ShelfUpdate {
	_u.mutation.AddPackageIDs(ids...)
	return _u
}

// AddPackages adds the "packages" edges to the GoodsPackage entity.
func (_u *ShelfUpdate) AddPackages(v ...*GoodsPackage) *ShelfUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPackageIDs(ids...)
}

// Mutation returns the ShelfMutation object of the builder.
func (_u *ShelfUpdate) Mutation() *ShelfMutation {
	return _u.mutation
}

// ClearWarehouse clears the "warehouse" edge to the Warehouse entity.
func (_u *ShelfUpdate) ClearWarehouse() *ShelfUpdate {
	_u.mutation.ClearWarehouse()
	return _u
}

// ClearUnits clears all "units" edges to the ShelfUnit entity.
func (_u *ShelfUpdate) ClearUnits() *ShelfUpdate {
	_u.mutation.ClearUnits()
	return _u
}

// RemoveUnitIDs removes the "units" edge to ShelfUnit entities by IDs.
func (_u *ShelfUpdate) RemoveUnitIDs(ids ...int) *ShelfUpdate {
	_u.mutation.RemoveUnitIDs(ids...)
	return _u
}

// RemoveUnits removes "units" edges to ShelfUnit entities.
func (_u *ShelfUpdate) RemoveUnits(v ...*ShelfUnit) *ShelfUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUnitIDs(ids...)
}

// ClearPackages clears all "packages" edges to the GoodsPackage entity.
func (_u *ShelfUpdate) ClearPackages() *ShelfUpdate {
	_u.mutation.ClearPackages()
	return _u
}

// RemovePackageIDs removes the "packages" edge to GoodsPackage entities by IDs.
func (_u *ShelfUpdate) RemovePackageIDs(ids ...int) *ShelfUpdate {
	_u.mutation.RemovePackageIDs(ids...)
	return _u
}

// RemovePackages removes "packages" edges to GoodsPackage entities.
func (_u *ShelfUpdate) RemovePackages(v ...*GoodsPackage) *ShelfUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePackageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ShelfUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShelfUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ShelfUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShelfUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ShelfUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(shelf.Table, shelf.Columns, sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ShelfNumber(); ok {
		_spec.SetField(shelf.FieldShelfNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedShelfNumber(); ok {
		_spec.AddField(shelf.FieldShelfNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(shelf.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bold(); ok {
		_spec.SetField(shelf.FieldBold, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Col(); ok {
		_spec.SetField(shelf.FieldCol, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCol(); ok {
		_spec.AddField(shelf.FieldCol, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Row(); ok {
		_spec.SetField(shelf.FieldRow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRow(); ok {
		_spec.AddField(shelf.FieldRow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(shelf.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(shelf.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(shelf.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(shelf.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsHorizontal(); ok {
		_spec.SetField(shelf.FieldIsHorizontal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsVerticalLong(); ok {
		_spec.SetField(shelf.FieldIsVerticalLong, field.TypeBool, value)
	}
	if _u.mutation.WarehouseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shelf.WarehouseTable,
			Columns: []string{shelf.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WarehouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shelf.WarehouseTable,
			Columns: []string{shelf.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.UnitsTable,
			Columns: []string{shelf.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUnitsIDs(); len(nodes) > 0 && !_u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.UnitsTable,
			Columns: []string{shelf.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.UnitsTable,
			Columns: []string{shelf.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PackagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.PackagesTable,
			Columns: []string{shelf.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPackagesIDs(); len(nodes) > 0 && !_u.mutation.PackagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.PackagesTable,
			Columns: []string{shelf.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PackagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.PackagesTable,
			Columns: []string{shelf.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shelf.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ShelfUpdateOne is the builder for updating a single Shelf entity.
type ShelfUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShelfMutation
}

// SetShelfNumber sets the "shelf_number" field.
func (_u *ShelfUpdateOne) SetShelfNumber(v int) *ShelfUpdateOne {
	_u.mutation.ResetShelfNumber()
	_u.mutation.SetShelfNumber(v)
	return _u
}

// SetNillableShelfNumber sets the "shelf_number" field if the given value is not nil.
func (_u *ShelfUpdateOne) SetNillableShelfNumber(v *int) *ShelfUpdateOne {
	if v != nil {
		_u.SetShelfNumber(*v)
	}
	return _u
}

// AddShelfNumber adds value to the "shelf_number" field.
func (_u *ShelfUpdateOne) AddShelfNumber(v int) *ShelfUpdateOne {
	_u.mutation.AddShelfNumber(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *ShelfUpdateOne) SetLabel(v string) *ShelfUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *ShelfUpdateOne) SetNillableLabel(v *string) *ShelfUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetBold sets the "bold" field.
func (_u *ShelfUpdateOne) SetBold(v bool) *ShelfUpdateOne {
	_u.mutation.SetBold(v)
	return _u
}

// SetNillableBold sets the "bold" field if the given value is not nil.
func (_u *ShelfUpdateOne) SetNillableBold(v *bool) *ShelfUpdateOne {
	if v != nil {
		_u.SetBold(*v)
	}
	return _u
}

// SetCol sets the "col" field.
func (_u *ShelfUpdateOne) SetCol(v int) *ShelfUpdateOne {
	_u.mutation.ResetCol()
	_u.mutation.SetCol(v)
	return _u
}

// SetNillableCol sets the "col" field if the given value is not nil.
func (_u *ShelfUpdateOne) SetNillableCol(v *int) *ShelfUpdateOne {
	if v != nil {
		_u.SetCol(*v)
	}
	return _u
}

// AddCol adds value to the "col" field.
func (_u *ShelfUpdateOne) AddCol(v int) *ShelfUpdateOne {
	_u.mutation.AddCol(v)
	return _u
}

// SetRow sets the "row" field.
func (_u *ShelfUpdateOne) SetRow(v int) *ShelfUpdateOne {
	_u.mutation.ResetRow()
	_u.mutation.SetRow(v)
	return _u
}

// SetNillableRow sets the "row" field if the given value is not nil.
func (_u *ShelfUpdateOne) SetNillableRow(v *int) *ShelfUpdateOne {
	if v != nil {
		_u.SetRow(*v)
	}
	return _u
}

// AddRow adds value to the "row" field.
func (_u *ShelfUpdateOne) AddRow(v int) *ShelfUpdateOne {
	_u.mutation.AddRow(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *ShelfUpdateOne) SetWidth(v int) *ShelfUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ShelfUpdateOne) SetNillableWidth(v *int) *ShelfUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ShelfUpdateOne) AddWidth(v int) *ShelfUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *ShelfUpdateOne) SetHeight(v int) *ShelfUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ShelfUpdateOne) SetNillableHeight(v *int) *ShelfUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ShelfUpdateOne) AddHeight(v int) *ShelfUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// SetIsHorizontal sets the "is_horizontal" field.
func (_u *ShelfUpdateOne) SetIsHorizontal(v bool) *ShelfUpdateOne {
	_u.mutation.SetIsHorizontal(v)
	return _u
}

// SetNillableIsHorizontal sets the "is_horizontal" field if the given value is not nil.
func (_u *ShelfUpdateOne) SetNillableIsHorizontal(v *bool) *ShelfUpdateOne {
	if v != nil {
		_u.SetIsHorizontal(*v)
	}
	return _u
}

// SetIsVerticalLong sets the "is_vertical_long" field.
func (_u *ShelfUpdateOne) SetIsVerticalLong(v bool) *ShelfUpdateOne {
	_u.mutation.SetIsVerticalLong(v)
	return _u
}

// SetNillableIsVerticalLong sets the "is_vertical_long" field if the given value is not nil.
func (_u *ShelfUpdateOne) SetNillableIsVerticalLong(v *bool) *ShelfUpdateOne {
	if v != nil {
		_u.SetIsVerticalLong(*v)
	}
	return _u
}

// SetWarehouseID sets the "warehouse_id" field.
func (_u *ShelfUpdateOne) SetWarehouseID(v int) *ShelfUpdateOne {
	_u.mutation.SetWarehouseID(v)
	return _u
}

// SetNillableWarehouseID sets the "warehouse_id" field if the given value is not nil.
func (_u *ShelfUpdateOne) SetNillableWarehouseID(v *int) *ShelfUpdateOne {
	if v != nil {
		_u.SetWarehouseID(*v)
	}
	return _u
}

// ClearWarehouseID clears the value of the "warehouse_id" field.
func (_u *ShelfUpdateOne) ClearWarehouseID() *ShelfUpdateOne {
	_u.mutation.ClearWarehouseID()
	return _u
}

// SetWarehouse sets the "warehouse" edge to the Warehouse entity.
func (_u *ShelfUpdateOne) SetWarehouse(v *Warehouse) *ShelfUpdateOne {
	return _u.SetWarehouseID(v.ID)
}

// AddUnitIDs adds the "units" edge to the ShelfUnit entity by IDs.
func (_u *ShelfUpdateOne) AddUnitIDs(ids ...int) *ShelfUpdateOne {
	_u.mutation.AddUnitIDs(ids...)
	return _u
}

// AddUnits adds the "units" edges to the ShelfUnit entity.
func (_u *ShelfUpdateOne) AddUnits(v ...*ShelfUnit) *ShelfUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUnitIDs(ids...)
}

// AddPackageIDs adds the "packages" edge to the GoodsPackage entity by IDs.
func (_u *ShelfUpdateOne) AddPackageIDs(ids ...int) *ShelfUpdateOne {
	_u.mutation.AddPackageIDs(ids...)
	return _u
}

// AddPackages adds the "packages" edges to the GoodsPackage entity.
func (_u *ShelfUpdateOne) AddPackages(v ...*GoodsPackage) *ShelfUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPackageIDs(ids...)
}

// Mutation returns the ShelfMutation object of the builder.
func (_u *ShelfUpdateOne) Mutation() *ShelfMutation {
	return _u.mutation
}

// ClearWarehouse clears the "warehouse" edge to the Warehouse entity.
func (_u *ShelfUpdateOne) ClearWarehouse() *ShelfUpdateOne {
	_u.mutation.ClearWarehouse()
	return _u
}

// ClearUnits clears all "units" edges to the ShelfUnit entity.
func (_u *ShelfUpdateOne) ClearUnits() *ShelfUpdateOne {
	_u.mutation.ClearUnits()
	return _u
}

// RemoveUnitIDs removes the "units" edge to ShelfUnit entities by IDs.
func (_u *ShelfUpdateOne) RemoveUnitIDs(ids ...int) *ShelfUpdateOne {
	_u.mutation.RemoveUnitIDs(ids...)
	return _u
}

// RemoveUnits removes "units" edges to ShelfUnit entities.
func (_u *ShelfUpdateOne) RemoveUnits(v ...*ShelfUnit) *ShelfUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUnitIDs(ids...)
}

// ClearPackages clears all "packages" edges to the GoodsPackage entity.
func (_u *ShelfUpdateOne) ClearPackages() *ShelfUpdateOne {
	_u.mutation.ClearPackages()
	return _u
}

// RemovePackageIDs removes the "packages" edge to GoodsPackage entities by IDs.
func (_u *ShelfUpdateOne) RemovePackageIDs(ids ...int) *ShelfUpdateOne {
	_u.mutation.RemovePackageIDs(ids...)
	return _u
}

// RemovePackages removes "packages" edges to GoodsPackage entities.
func (_u *ShelfUpdateOne) RemovePackages(v ...*GoodsPackage) *ShelfUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePackageIDs(ids...)
}

// Where appends a list predicates to the ShelfUpdate builder.
func (_u *ShelfUpdateOne) Where(ps ...predicate.Shelf) *ShelfUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ShelfUpdateOne) Select(field string, fields ...string) *ShelfUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Shelf entity.
func (_u *ShelfUpdateOne) Save(ctx context.Context) (*Shelf, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShelfUpdateOne) SaveX(ctx context.Context) *Shelf {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ShelfUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShelfUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ShelfUpdateOne) sqlSave(ctx context.Context) (_node *Shelf, err error) {
	_spec := sqlgraph.NewUpdateSpec(shelf.Table, shelf.Columns, sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Shelf.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shelf.FieldID)
		for _, f := range fields {
			if !shelf.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != shelf.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ShelfNumber(); ok {
		_spec.SetField(shelf.FieldShelfNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedShelfNumber(); ok {
		_spec.AddField(shelf.FieldShelfNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(shelf.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bold(); ok {
		_spec.SetField(shelf.FieldBold, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Col(); ok {
		_spec.SetField(shelf.FieldCol, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCol(); ok {
		_spec.AddField(shelf.FieldCol, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Row(); ok {
		_spec.SetField(shelf.FieldRow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRow(); ok {
		_spec.AddField(shelf.FieldRow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(shelf.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(shelf.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(shelf.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(shelf.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsHorizontal(); ok {
		_spec.SetField(shelf.FieldIsHorizontal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsVerticalLong(); ok {
		_spec.SetField(shelf.FieldIsVerticalLong, field.TypeBool, value)
	}
	if _u.mutation.WarehouseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shelf.WarehouseTable,
			Columns: []string{shelf.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WarehouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shelf.WarehouseTable,
			Columns: []string{shelf.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.UnitsTable,
			Columns: []string{shelf.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUnitsIDs(); len(nodes) > 0 && !_u.mutation.UnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.UnitsTable,
			Columns: []string{shelf.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.UnitsTable,
			Columns: []string{shelf.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PackagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.PackagesTable,
			Columns: []string{shelf.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPackagesIDs(); len(nodes) > 0 && !_u.mutation.PackagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.PackagesTable,
			Columns: []string{shelf.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PackagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelf.PackagesTable,
			Columns: []string{shelf.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Shelf{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shelf.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
