// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"warehouse/ent/goodspackage"
	"warehouse/ent/predicate"
	"warehouse/ent/product"
	"warehouse/ent/shelf"
	"warehouse/ent/shelfunit"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShelfUnitUpdate is the builder for updating ShelfUnit entities.
type ShelfUnitUpdate struct {
	config
	hooks    []Hook
	mutation *ShelfUnitMutation
}

// Where appends a list predicates to the ShelfUnitUpdate builder.
func (_u *ShelfUnitUpdate) Where(ps ...predicate.ShelfUnit) *ShelfUnitUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUnitNumber sets the "unit_number" field.
func (_u *ShelfUnitUpdate) SetUnitNumber(v int) *ShelfUnitUpdate {
	_u.mutation.ResetUnitNumber()
	_u.mutation.SetUnitNumber(v)
	return _u
}

// SetNillableUnitNumber sets the "unit_number" field if the given value is not nil.
func (_u *ShelfUnitUpdate) SetNillableUnitNumber(v *int) *ShelfUnitUpdate {
	if v != nil {
		_u.SetUnitNumber(*v)
	}
	return _u
}

// AddUnitNumber adds value to the "unit_number" field.
func (_u *ShelfUnitUpdate) AddUnitNumber(v int) *ShelfUnitUpdate {
	_u.mutation.AddUnitNumber(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *ShelfUnitUpdate) SetLabel(v string) *ShelfUnitUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *ShelfUnitUpdate) SetNillableLabel(v *string) *ShelfUnitUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetPositionFrac sets the "position_frac" field.
func (_u *ShelfUnitUpdate) SetPositionFrac(v float64) *ShelfUnitUpdate {
	_u.mutation.ResetPositionFrac()
	_u.mutation.SetPositionFrac(v)
	return _u
}

// SetNillablePositionFrac sets the "position_frac" field if the given value is not nil.
func (_u *ShelfUnitUpdate) SetNillablePositionFrac(v *float64) *ShelfUnitUpdate {
	if v != nil {
		_u.SetPositionFrac(*v)
	}
	return _u
}

// AddPositionFrac adds value to the "position_frac" field.
func (_u *ShelfUnitUpdate) AddPositionFrac(v float64) *ShelfUnitUpdate {
	_u.mutation.AddPositionFrac(v)
	return _u
}

// SetAccessCol sets the "access_col" field.
func (_u *ShelfUnitUpdate) SetAccessCol(v int) *ShelfUnitUpdate {
	_u.mutation.ResetAccessCol()
	_u.mutation.SetAccessCol(v)
	return _u
}

// SetNillableAccessCol sets the "access_col" field if the given value is not nil.
func (_u *ShelfUnitUpdate) SetNillableAccessCol(v *int) *ShelfUnitUpdate {
	if v != nil {
		_u.SetAccessCol(*v)
	}
	return _u
}

// AddAccessCol adds value to the "access_col" field.
func (_u *ShelfUnitUpdate) AddAccessCol(v int) *ShelfUnitUpdate {
	_u.mutation.AddAccessCol(v)
	return _u
}

// SetAccessRow sets the "access_row" field.
func (_u *ShelfUnitUpdate) SetAccessRow(v int) *ShelfUnitUpdate {
	_u.mutation.ResetAccessRow()
	_u.mutation.SetAccessRow(v)
	return _u
}

// SetNillableAccessRow sets the "access_row" field if the given value is not nil.
func (_u *ShelfUnitUpdate) SetNillableAccessRow(v *int) *ShelfUnitUpdate {
	if v != nil {
		_u.SetAccessRow(*v)
	}
	return _u
}

// AddAccessRow adds value to the "access_row" field.
func (_u *ShelfUnitUpdate) AddAccessRow(v int) *ShelfUnitUpdate {
	_u.mutation.AddAccessRow(v)
	return _u
}

// SetCapacity sets the "capacity" field.
func (_u *ShelfUnitUpdate) SetCapacity(v int) *ShelfUnitUpdate {
	_u.mutation.ResetCapacity()
	_u.mutation.SetCapacity(v)
	return _u
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (_u *ShelfUnitUpdate) SetNillableCapacity(v *int) *ShelfUnitUpdate {
	if v != nil {
		_u.SetCapacity(*v)
	}
	return _u
}

// AddCapacity adds value to the "capacity" field.
func (_u *ShelfUnitUpdate) AddCapacity(v int) *ShelfUnitUpdate {
	_u.mutation.AddCapacity(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ShelfUnitUpdate) SetProductID(v int) *ShelfUnitUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ShelfUnitUpdate) SetNillableProductID(v *int) *ShelfUnitUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// ClearProductID clears the value of the "product_id" field.
func (_u *ShelfUnitUpdate) ClearProductID() *ShelfUnitUpdate {
	_u.mutation.ClearProductID()
	return _u
}

// SetShelfID sets the "shelf" edge to the Shelf entity by ID.
func (_u *ShelfUnitUpdate) SetShelfID(id int) *ShelfUnitUpdate {
	_u.mutation.SetShelfID(id)
	return _u
}

// SetShelf sets the "shelf" edge to the Shelf entity.
func (_u *ShelfUnitUpdate) SetShelf(v *Shelf) *ShelfUnitUpdate {
	return _u.SetShelfID(v.ID)
}

// AddPackageIDs adds the "packages" edge to the GoodsPackage entity by IDs.
func (_u *ShelfUnitUpdate) AddPackageIDs(ids ...int) *ShelfUnitUpdate {
	_u.mutation.AddPackageIDs(ids...)
	return _u
}

// AddPackages adds the "packages" edges to the GoodsPackage entity.
func (_u *ShelfUnitUpdate) AddPackages(v ...*GoodsPackage) *ShelfUnitUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPackageIDs(ids...)
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *ShelfUnitUpdate) SetProduct(v *Product) *ShelfUnitUpdate {
	return _u.SetProductID(v.ID)
}

// Mutation returns the ShelfUnitMutation object of the builder.
func (_u *ShelfUnitUpdate) Mutation() *ShelfUnitMutation {
	return _u.mutation
}

// ClearShelf clears the "shelf" edge to the Shelf entity.
func (_u *ShelfUnitUpdate) ClearShelf() *ShelfUnitUpdate {
	_u.mutation.ClearShelf()
	return _u
}

// ClearPackages clears all "packages" edges to the GoodsPackage entity.
func (_u *ShelfUnitUpdate) ClearPackages() *ShelfUnitUpdate {
	_u.mutation.ClearPackages()
	return _u
}

// RemovePackageIDs removes the "packages" edge to GoodsPackage entities by IDs.
func (_u *ShelfUnitUpdate) RemovePackageIDs(ids ...int) *ShelfUnitUpdate {
	_u.mutation.RemovePackageIDs(ids...)
	return _u
}

// RemovePackages removes "packages" edges to GoodsPackage entities.
func (_u *ShelfUnitUpdate) RemovePackages(v ...*GoodsPackage) *ShelfUnitUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePackageIDs(ids...)
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *ShelfUnitUpdate) ClearProduct() *ShelfUnitUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ShelfUnitUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShelfUnitUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ShelfUnitUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShelfUnitUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShelfUnitUpdate) check() error {
	if _u.mutation.ShelfCleared() && len(_u.mutation.ShelfIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ShelfUnit.shelf"`)
	}
	return nil
}

func (_u *ShelfUnitUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(shelfunit.Table, shelfunit.Columns, sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UnitNumber(); ok {
		_spec.SetField(shelfunit.FieldUnitNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUnitNumber(); ok {
		_spec.AddField(shelfunit.FieldUnitNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(shelfunit.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PositionFrac(); ok {
		_spec.SetField(shelfunit.FieldPositionFrac, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPositionFrac(); ok {
		_spec.AddField(shelfunit.FieldPositionFrac, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AccessCol(); ok {
		_spec.SetField(shelfunit.FieldAccessCol, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccessCol(); ok {
		_spec.AddField(shelfunit.FieldAccessCol, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccessRow(); ok {
		_spec.SetField(shelfunit.FieldAccessRow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccessRow(); ok {
		_spec.AddField(shelfunit.FieldAccessRow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Capacity(); ok {
		_spec.SetField(shelfunit.FieldCapacity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapacity(); ok {
		_spec.AddField(shelfunit.FieldCapacity, field.TypeInt, value)
	}
	if _u.mutation.ShelfCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shelfunit.ShelfTable,
			Columns: []string{shelfunit.ShelfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShelfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shelfunit.ShelfTable,
			Columns: []string{shelfunit.ShelfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PackagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelfunit.PackagesTable,
			Columns: []string{shelfunit.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPackagesIDs(); len(nodes) > 0 && !_u.mutation.PackagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelfunit.PackagesTable,
			Columns: []string{shelfunit.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PackagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelfunit.PackagesTable,
			Columns: []string{shelfunit.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   shelfunit.ProductTable,
			Columns: []string{shelfunit.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   shelfunit.ProductTable,
			Columns: []string{shelfunit.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shelfunit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ShelfUnitUpdateOne is the builder for updating a single ShelfUnit entity.
type ShelfUnitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShelfUnitMutation
}

// SetUnitNumber sets the "unit_number" field.
func (_u *ShelfUnitUpdateOne) SetUnitNumber(v int) *ShelfUnitUpdateOne {
	_u.mutation.ResetUnitNumber()
	_u.mutation.SetUnitNumber(v)
	return _u
}

// SetNillableUnitNumber sets the "unit_number" field if the given value is not nil.
func (_u *ShelfUnitUpdateOne) SetNillableUnitNumber(v *int) *ShelfUnitUpdateOne {
	if v != nil {
		_u.SetUnitNumber(*v)
	}
	return _u
}

// AddUnitNumber adds value to the "unit_number" field.
func (_u *ShelfUnitUpdateOne) AddUnitNumber(v int) *ShelfUnitUpdateOne {
	_u.mutation.AddUnitNumber(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *ShelfUnitUpdateOne) SetLabel(v string) *ShelfUnitUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *ShelfUnitUpdateOne) SetNillableLabel(v *string) *ShelfUnitUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetPositionFrac sets the "position_frac" field.
func (_u *ShelfUnitUpdateOne) SetPositionFrac(v float64) *ShelfUnitUpdateOne {
	_u.mutation.ResetPositionFrac()
	_u.mutation.SetPositionFrac(v)
	return _u
}

// SetNillablePositionFrac sets the "position_frac" field if the given value is not nil.
func (_u *ShelfUnitUpdateOne) SetNillablePositionFrac(v *float64) *ShelfUnitUpdateOne {
	if v != nil {
		_u.SetPositionFrac(*v)
	}
	return _u
}

// AddPositionFrac adds value to the "position_frac" field.
func (_u *ShelfUnitUpdateOne) AddPositionFrac(v float64) *ShelfUnitUpdateOne {
	_u.mutation.AddPositionFrac(v)
	return _u
}

// SetAccessCol sets the "access_col" field.
func (_u *ShelfUnitUpdateOne) SetAccessCol(v int) *ShelfUnitUpdateOne {
	_u.mutation.ResetAccessCol()
	_u.mutation.SetAccessCol(v)
	return _u
}

// SetNillableAccessCol sets the "access_col" field if the given value is not nil.
func (_u *ShelfUnitUpdateOne) SetNillableAccessCol(v *int) *ShelfUnitUpdateOne {
	if v != nil {
		_u.SetAccessCol(*v)
	}
	return _u
}

// AddAccessCol adds value to the "access_col" field.
func (_u *ShelfUnitUpdateOne) AddAccessCol(v int) *ShelfUnitUpdateOne {
	_u.mutation.AddAccessCol(v)
	return _u
}

// SetAccessRow sets the "access_row" field.
func (_u *ShelfUnitUpdateOne) SetAccessRow(v int) *ShelfUnitUpdateOne {
	_u.mutation.ResetAccessRow()
	_u.mutation.SetAccessRow(v)
	return _u
}

// SetNillableAccessRow sets the "access_row" field if the given value is not nil.
func (_u *ShelfUnitUpdateOne) SetNillableAccessRow(v *int) *ShelfUnitUpdateOne {
	if v != nil {
		_u.SetAccessRow(*v)
	}
	return _u
}

// AddAccessRow adds value to the "access_row" field.
func (_u *ShelfUnitUpdateOne) AddAccessRow(v int) *ShelfUnitUpdateOne {
	_u.mutation.AddAccessRow(v)
	return _u
}

// SetCapacity sets the "capacity" field.
func (_u *ShelfUnitUpdateOne) SetCapacity(v int) *ShelfUnitUpdateOne {
	_u.mutation.ResetCapacity()
	_u.mutation.SetCapacity(v)
	return _u
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (_u *ShelfUnitUpdateOne) SetNillableCapacity(v *int) *ShelfUnitUpdateOne {
	if v != nil {
		_u.SetCapacity(*v)
	}
	return _u
}

// AddCapacity adds value to the "capacity" field.
func (_u *ShelfUnitUpdateOne) AddCapacity(v int) *ShelfUnitUpdateOne {
	_u.mutation.AddCapacity(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ShelfUnitUpdateOne) SetProductID(v int) *ShelfUnitUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ShelfUnitUpdateOne) SetNillableProductID(v *int) *ShelfUnitUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// ClearProductID clears the value of the "product_id" field.
func (_u *ShelfUnitUpdateOne) ClearProductID() *ShelfUnitUpdateOne {
	_u.mutation.ClearProductID()
	return _u
}

// SetShelfID sets the "shelf" edge to the Shelf entity by ID.
func (_u *ShelfUnitUpdateOne) SetShelfID(id int) *ShelfUnitUpdateOne {
	_u.mutation.SetShelfID(id)
	return _u
}

// SetShelf sets the "shelf" edge to the Shelf entity.
func (_u *ShelfUnitUpdateOne) SetShelf(v *Shelf) *ShelfUnitUpdateOne {
	return _u.SetShelfID(v.ID)
}

// AddPackageIDs adds the "packages" edge to the GoodsPackage entity by IDs.
func (_u *ShelfUnitUpdateOne) AddPackageIDs(ids ...int) *ShelfUnitUpdateOne {
	_u.mutation.AddPackageIDs(ids...)
	return _u
}

// AddPackages adds the "packages" edges to the GoodsPackage entity.
func (_u *ShelfUnitUpdateOne) AddPackages(v ...*GoodsPackage) *ShelfUnitUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPackageIDs(ids...)
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *ShelfUnitUpdateOne) SetProduct(v *Product) *ShelfUnitUpdateOne {
	return _u.SetProductID(v.ID)
}

// Mutation returns the ShelfUnitMutation object of the builder.
func (_u *ShelfUnitUpdateOne) Mutation() *ShelfUnitMutation {
	return _u.mutation
}

// ClearShelf clears the "shelf" edge to the Shelf entity.
func (_u *ShelfUnitUpdateOne) ClearShelf() *ShelfUnitUpdateOne {
	_u.mutation.ClearShelf()
	return _u
}

// ClearPackages clears all "packages" edges to the GoodsPackage entity.
func (_u *ShelfUnitUpdateOne) ClearPackages() *ShelfUnitUpdateOne {
	_u.mutation.ClearPackages()
	return _u
}

// RemovePackageIDs removes the "packages" edge to GoodsPackage entities by IDs.
func (_u *ShelfUnitUpdateOne) RemovePackageIDs(ids ...int) *ShelfUnitUpdateOne {
	_u.mutation.RemovePackageIDs(ids...)
	return _u
}

// RemovePackages removes "packages" edges to GoodsPackage entities.
func (_u *ShelfUnitUpdateOne) RemovePackages(v ...*GoodsPackage) *ShelfUnitUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePackageIDs(ids...)
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *ShelfUnitUpdateOne) ClearProduct() *ShelfUnitUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// Where appends a list predicates to the ShelfUnitUpdate builder.
func (_u *ShelfUnitUpdateOne) Where(ps ...predicate.ShelfUnit) *ShelfUnitUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ShelfUnitUpdateOne) Select(field string, fields ...string) *ShelfUnitUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ShelfUnit entity.
func (_u *ShelfUnitUpdateOne) Save(ctx context.Context) (*ShelfUnit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShelfUnitUpdateOne) SaveX(ctx context.Context) *ShelfUnit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ShelfUnitUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShelfUnitUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShelfUnitUpdateOne) check() error {
	if _u.mutation.ShelfCleared() && len(_u.mutation.ShelfIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ShelfUnit.shelf"`)
	}
	return nil
}

func (_u *ShelfUnitUpdateOne) sqlSave(ctx context.Context) (_node *ShelfUnit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(shelfunit.Table, shelfunit.Columns, sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ShelfUnit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shelfunit.FieldID)
		for _, f := range fields {
			if !shelfunit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != shelfunit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UnitNumber(); ok {
		_spec.SetField(shelfunit.FieldUnitNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUnitNumber(); ok {
		_spec.AddField(shelfunit.FieldUnitNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(shelfunit.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PositionFrac(); ok {
		_spec.SetField(shelfunit.FieldPositionFrac, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPositionFrac(); ok {
		_spec.AddField(shelfunit.FieldPositionFrac, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AccessCol(); ok {
		_spec.SetField(shelfunit.FieldAccessCol, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccessCol(); ok {
		_spec.AddField(shelfunit.FieldAccessCol, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccessRow(); ok {
		_spec.SetField(shelfunit.FieldAccessRow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccessRow(); ok {
		_spec.AddField(shelfunit.FieldAccessRow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Capacity(); ok {
		_spec.SetField(shelfunit.FieldCapacity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapacity(); ok {
		_spec.AddField(shelfunit.FieldCapacity, field.TypeInt, value)
	}
	if _u.mutation.ShelfCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shelfunit.ShelfTable,
			Columns: []string{shelfunit.ShelfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShelfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shelfunit.ShelfTable,
			Columns: []string{shelfunit.ShelfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PackagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelfunit.PackagesTable,
			Columns: []string{shelfunit.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPackagesIDs(); len(nodes) > 0 && !_u.mutation.PackagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelfunit.PackagesTable,
			Columns: []string{shelfunit.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PackagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelfunit.PackagesTable,
			Columns: []string{shelfunit.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   shelfunit.ProductTable,
			Columns: []string{shelfunit.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   shelfunit.ProductTable,
			Columns: []string{shelfunit.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ShelfUnit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shelfunit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
