// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"warehouse/ent/goodspackage"
	"warehouse/ent/product"
	"warehouse/ent/shelf"
	"warehouse/ent/shelfunit"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShelfUnitCreate is the builder for creating a ShelfUnit entity.
type ShelfUnitCreate struct {
	config
	mutation *ShelfUnitMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUnitNumber sets the "unit_number" field.
func (_c *ShelfUnitCreate) SetUnitNumber(v int) *ShelfUnitCreate {
	_c.mutation.SetUnitNumber(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *ShelfUnitCreate) SetLabel(v string) *ShelfUnitCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *ShelfUnitCreate) SetNillableLabel(v *string) *ShelfUnitCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetPositionFrac sets the "position_frac" field.
func (_c *ShelfUnitCreate) SetPositionFrac(v float64) *ShelfUnitCreate {
	_c.mutation.SetPositionFrac(v)
	return _c
}

// SetNillablePositionFrac sets the "position_frac" field if the given value is not nil.
func (_c *ShelfUnitCreate) SetNillablePositionFrac(v *float64) *ShelfUnitCreate {
	if v != nil {
		_c.SetPositionFrac(*v)
	}
	return _c
}

// SetAccessCol sets the "access_col" field.
func (_c *ShelfUnitCreate) SetAccessCol(v int) *ShelfUnitCreate {
	_c.mutation.SetAccessCol(v)
	return _c
}

// SetNillableAccessCol sets the "access_col" field if the given value is not nil.
func (_c *ShelfUnitCreate) SetNillableAccessCol(v *int) *ShelfUnitCreate {
	if v != nil {
		_c.SetAccessCol(*v)
	}
	return _c
}

// SetAccessRow sets the "access_row" field.
func (_c *ShelfUnitCreate) SetAccessRow(v int) *ShelfUnitCreate {
	_c.mutation.SetAccessRow(v)
	return _c
}

// SetNillableAccessRow sets the "access_row" field if the given value is not nil.
func (_c *ShelfUnitCreate) SetNillableAccessRow(v *int) *ShelfUnitCreate {
	if v != nil {
		_c.SetAccessRow(*v)
	}
	return _c
}

// SetCapacity sets the "capacity" field.
func (_c *ShelfUnitCreate) SetCapacity(v int) *ShelfUnitCreate {
	_c.mutation.SetCapacity(v)
	return _c
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (_c *ShelfUnitCreate) SetNillableCapacity(v *int) *ShelfUnitCreate {
	if v != nil {
		_c.SetCapacity(*v)
	}
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *ShelfUnitCreate) SetProductID(v int) *ShelfUnitCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_c *ShelfUnitCreate) SetNillableProductID(v *int) *ShelfUnitCreate {
	if v != nil {
		_c.SetProductID(*v)
	}
	return _c
}

// SetShelfID sets the "shelf" edge to the Shelf entity by ID.
func (_c *ShelfUnitCreate) SetShelfID(id int) *ShelfUnitCreate {
	_c.mutation.SetShelfID(id)
	return _c
}

// SetShelf sets the "shelf" edge to the Shelf entity.
func (_c *ShelfUnitCreate) SetShelf(v *Shelf) *ShelfUnitCreate {
	return _c.SetShelfID(v.ID)
}

// AddPackageIDs adds the "packages" edge to the GoodsPackage entity by IDs.
func (_c *ShelfUnitCreate) AddPackageIDs(ids ...int) *ShelfUnitCreate {
	_c.mutation.AddPackageIDs(ids...)
	return _c
}

// AddPackages adds the "packages" edges to the GoodsPackage entity.
func (_c *ShelfUnitCreate) AddPackages(v ...*GoodsPackage) *ShelfUnitCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPackageIDs(ids...)
}

// SetProduct sets the "product" edge to the Product entity.
func (_c *ShelfUnitCreate) SetProduct(v *Product) *ShelfUnitCreate {
	return _c.SetProductID(v.ID)
}

// Mutation returns the ShelfUnitMutation object of the builder.
func (_c *ShelfUnitCreate) Mutation() *ShelfUnitMutation {
	return _c.mutation
}

// Save creates the ShelfUnit in the database.
func (_c *ShelfUnitCreate) Save(ctx context.Context) (*ShelfUnit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShelfUnitCreate) SaveX(ctx context.Context) *ShelfUnit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShelfUnitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShelfUnitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShelfUnitCreate) defaults() {
	if _, ok := _c.mutation.Label(); !ok {
		v := shelfunit.DefaultLabel
		_c.mutation.SetLabel(v)
	}
	if _, ok := _c.mutation.PositionFrac(); !ok {
		v := shelfunit.DefaultPositionFrac
		_c.mutation.SetPositionFrac(v)
	}
	if _, ok := _c.mutation.AccessCol(); !ok {
		v := shelfunit.DefaultAccessCol
		_c.mutation.SetAccessCol(v)
	}
	if _, ok := _c.mutation.AccessRow(); !ok {
		v := shelfunit.DefaultAccessRow
		_c.mutation.SetAccessRow(v)
	}
	if _, ok := _c.mutation.Capacity(); !ok {
		v := shelfunit.DefaultCapacity
		_c.mutation.SetCapacity(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShelfUnitCreate) check() error {
	if _, ok := _c.mutation.UnitNumber(); !ok {
		return &ValidationError{Name: "unit_number", err: errors.New(`ent: missing required field "ShelfUnit.unit_number"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "ShelfUnit.label"`)}
	}
	if _, ok := _c.mutation.PositionFrac(); !ok {
		return &ValidationError{Name: "position_frac", err: errors.New(`ent: missing required field "ShelfUnit.position_frac"`)}
	}
	if _, ok := _c.mutation.AccessCol(); !ok {
		return &ValidationError{Name: "access_col", err: errors.New(`ent: missing required field "ShelfUnit.access_col"`)}
	}
	if _, ok := _c.mutation.AccessRow(); !ok {
		return &ValidationError{Name: "access_row", err: errors.New(`ent: missing required field "ShelfUnit.access_row"`)}
	}
	if _, ok := _c.mutation.Capacity(); !ok {
		return &ValidationError{Name: "capacity", err: errors.New(`ent: missing required field "ShelfUnit.capacity"`)}
	}
	if len(_c.mutation.ShelfIDs()) == 0 {
		return &ValidationError{Name: "shelf", err: errors.New(`ent: missing required edge "ShelfUnit.shelf"`)}
	}
	return nil
}

func (_c *ShelfUnitCreate) sqlSave(ctx context.Context) (*ShelfUnit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShelfUnitCreate) createSpec() (*ShelfUnit, *sqlgraph.CreateSpec) {
	var (
		_node = &ShelfUnit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shelfunit.Table, sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UnitNumber(); ok {
		_spec.SetField(shelfunit.FieldUnitNumber, field.TypeInt, value)
		_node.UnitNumber = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(shelfunit.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.PositionFrac(); ok {
		_spec.SetField(shelfunit.FieldPositionFrac, field.TypeFloat64, value)
		_node.PositionFrac = value
	}
	if value, ok := _c.mutation.AccessCol(); ok {
		_spec.SetField(shelfunit.FieldAccessCol, field.TypeInt, value)
		_node.AccessCol = value
	}
	if value, ok := _c.mutation.AccessRow(); ok {
		_spec.SetField(shelfunit.FieldAccessRow, field.TypeInt, value)
		_node.AccessRow = value
	}
	if value, ok := _c.mutation.Capacity(); ok {
		_spec.SetField(shelfunit.FieldCapacity, field.TypeInt, value)
		_node.Capacity = value
	}
	if nodes := _c.mutation.ShelfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shelfunit.ShelfTable,
			Columns: []string{shelfunit.ShelfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.shelf_units = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PackagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shelfunit.PackagesTable,
			Columns: []string{shelfunit.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goodspackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   shelfunit.ProductTable,
			Columns: []string{shelfunit.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ShelfUnit.Create().
//		SetUnitNumber(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShelfUnitUpsert) {
//			SetUnitNumber(v+v).
//		}).
//		Exec(ctx)
func (_c *ShelfUnitCreate) OnConflict(opts ...sql.ConflictOption) *ShelfUnitUpsertOne {
	_c.conflict = opts
	return &ShelfUnitUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ShelfUnit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShelfUnitCreate) OnConflictColumns(columns ...string) *ShelfUnitUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShelfUnitUpsertOne{
		create: _c,
	}
}

type (
	// ShelfUnitUpsertOne is the builder for "upsert"-ing
	//  one ShelfUnit node.
	ShelfUnitUpsertOne struct {
		create *ShelfUnitCreate
	}

	// ShelfUnitUpsert is the "OnConflict" setter.
	ShelfUnitUpsert struct {
		*sql.UpdateSet
	}
)

// SetUnitNumber sets the "unit_number" field.
func (u *ShelfUnitUpsert) SetUnitNumber(v int) *ShelfUnitUpsert {
	u.Set(shelfunit.FieldUnitNumber, v)
	return u
}

// UpdateUnitNumber sets the "unit_number" field to the value that was provided on create.
func (u *ShelfUnitUpsert) UpdateUnitNumber() *ShelfUnitUpsert {
	u.SetExcluded(shelfunit.FieldUnitNumber)
	return u
}

// AddUnitNumber adds v to the "unit_number" field.
func (u *ShelfUnitUpsert) AddUnitNumber(v int) *ShelfUnitUpsert {
	u.Add(shelfunit.FieldUnitNumber, v)
	return u
}

// SetLabel sets the "label" field.
func (u *ShelfUnitUpsert) SetLabel(v string) *ShelfUnitUpsert {
	u.Set(shelfunit.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *ShelfUnitUpsert) UpdateLabel() *ShelfUnitUpsert {
	u.SetExcluded(shelfunit.FieldLabel)
	return u
}

// SetPositionFrac sets the "position_frac" field.
func (u *ShelfUnitUpsert) SetPositionFrac(v float64) *ShelfUnitUpsert {
	u.Set(shelfunit.FieldPositionFrac, v)
	return u
}

// UpdatePositionFrac sets the "position_frac" field to the value that was provided on create.
func (u *ShelfUnitUpsert) UpdatePositionFrac() *ShelfUnitUpsert {
	u.SetExcluded(shelfunit.FieldPositionFrac)
	return u
}

// AddPositionFrac adds v to the "position_frac" field.
func (u *ShelfUnitUpsert) AddPositionFrac(v float64) *ShelfUnitUpsert {
	u.Add(shelfunit.FieldPositionFrac, v)
	return u
}

// SetAccessCol sets the "access_col" field.
func (u *ShelfUnitUpsert) SetAccessCol(v int) *ShelfUnitUpsert {
	u.Set(shelfunit.FieldAccessCol, v)
	return u
}

// UpdateAccessCol sets the "access_col" field to the value that was provided on create.
func (u *ShelfUnitUpsert) UpdateAccessCol() *ShelfUnitUpsert {
	u.SetExcluded(shelfunit.FieldAccessCol)
	return u
}

// AddAccessCol adds v to the "access_col" field.
func (u *ShelfUnitUpsert) AddAccessCol(v int) *ShelfUnitUpsert {
	u.Add(shelfunit.FieldAccessCol, v)
	return u
}

// SetAccessRow sets the "access_row" field.
func (u *ShelfUnitUpsert) SetAccessRow(v int) *ShelfUnitUpsert {
	u.Set(shelfunit.FieldAccessRow, v)
	return u
}

// UpdateAccessRow sets the "access_row" field to the value that was provided on create.
func (u *ShelfUnitUpsert) UpdateAccessRow() *ShelfUnitUpsert {
	u.SetExcluded(shelfunit.FieldAccessRow)
	return u
}

// AddAccessRow adds v to the "access_row" field.
func (u *ShelfUnitUpsert) AddAccessRow(v int) *ShelfUnitUpsert {
	u.Add(shelfunit.FieldAccessRow, v)
	return u
}

// SetCapacity sets the "capacity" field.
func (u *ShelfUnitUpsert) SetCapacity(v int) *ShelfUnitUpsert {
	u.Set(shelfunit.FieldCapacity, v)
	return u
}

// UpdateCapacity sets the "capacity" field to the value that was provided on create.
func (u *ShelfUnitUpsert) UpdateCapacity() *ShelfUnitUpsert {
	u.SetExcluded(shelfunit.FieldCapacity)
	return u
}

// AddCapacity adds v to the "capacity" field.
func (u *ShelfUnitUpsert) AddCapacity(v int) *ShelfUnitUpsert {
	u.Add(shelfunit.FieldCapacity, v)
	return u
}

// SetProductID sets the "product_id" field.
func (u *ShelfUnitUpsert) SetProductID(v int) *ShelfUnitUpsert {
	u.Set(shelfunit.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ShelfUnitUpsert) UpdateProductID() *ShelfUnitUpsert {
	u.SetExcluded(shelfunit.FieldProductID)
	return u
}

// ClearProductID clears the value of the "product_id" field.
func (u *ShelfUnitUpsert) ClearProductID() *ShelfUnitUpsert {
	u.SetNull(shelfunit.FieldProductID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ShelfUnit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ShelfUnitUpsertOne) UpdateNewValues() *ShelfUnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ShelfUnit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ShelfUnitUpsertOne) Ignore() *ShelfUnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShelfUnitUpsertOne) DoNothing() *ShelfUnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShelfUnitCreate.OnConflict
// documentation for more info.
func (u *ShelfUnitUpsertOne) Update(set func(*ShelfUnitUpsert)) *ShelfUnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShelfUnitUpsert{UpdateSet: update})
	}))
	return u
}

// SetUnitNumber sets the "unit_number" field.
func (u *ShelfUnitUpsertOne) SetUnitNumber(v int) *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetUnitNumber(v)
	})
}

// AddUnitNumber adds v to the "unit_number" field.
func (u *ShelfUnitUpsertOne) AddUnitNumber(v int) *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.AddUnitNumber(v)
	})
}

// UpdateUnitNumber sets the "unit_number" field to the value that was provided on create.
func (u *ShelfUnitUpsertOne) UpdateUnitNumber() *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdateUnitNumber()
	})
}

// SetLabel sets the "label" field.
func (u *ShelfUnitUpsertOne) SetLabel(v string) *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *ShelfUnitUpsertOne) UpdateLabel() *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdateLabel()
	})
}

// SetPositionFrac sets the "position_frac" field.
func (u *ShelfUnitUpsertOne) SetPositionFrac(v float64) *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetPositionFrac(v)
	})
}

// AddPositionFrac adds v to the "position_frac" field.
func (u *ShelfUnitUpsertOne) AddPositionFrac(v float64) *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.AddPositionFrac(v)
	})
}

// UpdatePositionFrac sets the "position_frac" field to the value that was provided on create.
func (u *ShelfUnitUpsertOne) UpdatePositionFrac() *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdatePositionFrac()
	})
}

// SetAccessCol sets the "access_col" field.
func (u *ShelfUnitUpsertOne) SetAccessCol(v int) *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetAccessCol(v)
	})
}

// AddAccessCol adds v to the "access_col" field.
func (u *ShelfUnitUpsertOne) AddAccessCol(v int) *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.AddAccessCol(v)
	})
}

// UpdateAccessCol sets the "access_col" field to the value that was provided on create.
func (u *ShelfUnitUpsertOne) UpdateAccessCol() *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdateAccessCol()
	})
}

// SetAccessRow sets the "access_row" field.
func (u *ShelfUnitUpsertOne) SetAccessRow(v int) *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetAccessRow(v)
	})
}

// AddAccessRow adds v to the "access_row" field.
func (u *ShelfUnitUpsertOne) AddAccessRow(v int) *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.AddAccessRow(v)
	})
}

// UpdateAccessRow sets the "access_row" field to the value that was provided on create.
func (u *ShelfUnitUpsertOne) UpdateAccessRow() *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdateAccessRow()
	})
}

// SetCapacity sets the "capacity" field.
func (u *ShelfUnitUpsertOne) SetCapacity(v int) *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetCapacity(v)
	})
}

// AddCapacity adds v to the "capacity" field.
func (u *ShelfUnitUpsertOne) AddCapacity(v int) *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.AddCapacity(v)
	})
}

// UpdateCapacity sets the "capacity" field to the value that was provided on create.
func (u *ShelfUnitUpsertOne) UpdateCapacity() *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdateCapacity()
	})
}

// SetProductID sets the "product_id" field.
func (u *ShelfUnitUpsertOne) SetProductID(v int) *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ShelfUnitUpsertOne) UpdateProductID() *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdateProductID()
	})
}

// ClearProductID clears the value of the "product_id" field.
func (u *ShelfUnitUpsertOne) ClearProductID() *ShelfUnitUpsertOne {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.ClearProductID()
	})
}

// Exec executes the query.
func (u *ShelfUnitUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShelfUnitCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShelfUnitUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ShelfUnitUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ShelfUnitUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ShelfUnitCreateBulk is the builder for creating many ShelfUnit entities in bulk.
type ShelfUnitCreateBulk struct {
	config
	err      error
	builders []*ShelfUnitCreate
	conflict []sql.ConflictOption
}

// Save creates the ShelfUnit entities in the database.
func (_c *ShelfUnitCreateBulk) Save(ctx context.Context) ([]*ShelfUnit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ShelfUnit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShelfUnitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShelfUnitCreateBulk) SaveX(ctx context.Context) []*ShelfUnit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShelfUnitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShelfUnitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ShelfUnit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShelfUnitUpsert) {
//			SetUnitNumber(v+v).
//		}).
//		Exec(ctx)
func (_c *ShelfUnitCreateBulk) OnConflict(opts ...sql.ConflictOption) *ShelfUnitUpsertBulk {
	_c.conflict = opts
	return &ShelfUnitUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ShelfUnit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShelfUnitCreateBulk) OnConflictColumns(columns ...string) *ShelfUnitUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShelfUnitUpsertBulk{
		create: _c,
	}
}

// ShelfUnitUpsertBulk is the builder for "upsert"-ing
// a bulk of ShelfUnit nodes.
type ShelfUnitUpsertBulk struct {
	create *ShelfUnitCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ShelfUnit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ShelfUnitUpsertBulk) UpdateNewValues() *ShelfUnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ShelfUnit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ShelfUnitUpsertBulk) Ignore() *ShelfUnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShelfUnitUpsertBulk) DoNothing() *ShelfUnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShelfUnitCreateBulk.OnConflict
// documentation for more info.
func (u *ShelfUnitUpsertBulk) Update(set func(*ShelfUnitUpsert)) *ShelfUnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShelfUnitUpsert{UpdateSet: update})
	}))
	return u
}

// SetUnitNumber sets the "unit_number" field.
func (u *ShelfUnitUpsertBulk) SetUnitNumber(v int) *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetUnitNumber(v)
	})
}

// AddUnitNumber adds v to the "unit_number" field.
func (u *ShelfUnitUpsertBulk) AddUnitNumber(v int) *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.AddUnitNumber(v)
	})
}

// UpdateUnitNumber sets the "unit_number" field to the value that was provided on create.
func (u *ShelfUnitUpsertBulk) UpdateUnitNumber() *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdateUnitNumber()
	})
}

// SetLabel sets the "label" field.
func (u *ShelfUnitUpsertBulk) SetLabel(v string) *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *ShelfUnitUpsertBulk) UpdateLabel() *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdateLabel()
	})
}

// SetPositionFrac sets the "position_frac" field.
func (u *ShelfUnitUpsertBulk) SetPositionFrac(v float64) *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetPositionFrac(v)
	})
}

// AddPositionFrac adds v to the "position_frac" field.
func (u *ShelfUnitUpsertBulk) AddPositionFrac(v float64) *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.AddPositionFrac(v)
	})
}

// UpdatePositionFrac sets the "position_frac" field to the value that was provided on create.
func (u *ShelfUnitUpsertBulk) UpdatePositionFrac() *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdatePositionFrac()
	})
}

// SetAccessCol sets the "access_col" field.
func (u *ShelfUnitUpsertBulk) SetAccessCol(v int) *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetAccessCol(v)
	})
}

// AddAccessCol adds v to the "access_col" field.
func (u *ShelfUnitUpsertBulk) AddAccessCol(v int) *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.AddAccessCol(v)
	})
}

// UpdateAccessCol sets the "access_col" field to the value that was provided on create.
func (u *ShelfUnitUpsertBulk) UpdateAccessCol() *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdateAccessCol()
	})
}

// SetAccessRow sets the "access_row" field.
func (u *ShelfUnitUpsertBulk) SetAccessRow(v int) *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetAccessRow(v)
	})
}

// AddAccessRow adds v to the "access_row" field.
func (u *ShelfUnitUpsertBulk) AddAccessRow(v int) *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.AddAccessRow(v)
	})
}

// UpdateAccessRow sets the "access_row" field to the value that was provided on create.
func (u *ShelfUnitUpsertBulk) UpdateAccessRow() *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdateAccessRow()
	})
}

// SetCapacity sets the "capacity" field.
func (u *ShelfUnitUpsertBulk) SetCapacity(v int) *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetCapacity(v)
	})
}

// AddCapacity adds v to the "capacity" field.
func (u *ShelfUnitUpsertBulk) AddCapacity(v int) *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.AddCapacity(v)
	})
}

// UpdateCapacity sets the "capacity" field to the value that was provided on create.
func (u *ShelfUnitUpsertBulk) UpdateCapacity() *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdateCapacity()
	})
}

// SetProductID sets the "product_id" field.
func (u *ShelfUnitUpsertBulk) SetProductID(v int) *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ShelfUnitUpsertBulk) UpdateProductID() *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.UpdateProductID()
	})
}

// ClearProductID clears the value of the "product_id" field.
func (u *ShelfUnitUpsertBulk) ClearProductID() *ShelfUnitUpsertBulk {
	return u.Update(func(s *ShelfUnitUpsert) {
		s.ClearProductID()
	})
}

// Exec executes the query.
func (u *ShelfUnitUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ShelfUnitCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShelfUnitCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShelfUnitUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
