// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"warehouse/ent/goodspackage"
	"warehouse/ent/predicate"
	"warehouse/ent/shelf"
	"warehouse/ent/shelfunit"
	"warehouse/ent/warehouse"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShelfQuery is the builder for querying Shelf entities.
type ShelfQuery struct {
	config
	ctx           *QueryContext
	order         []shelf.OrderOption
	inters        []Interceptor
	predicates    []predicate.Shelf
	withWarehouse *WarehouseQuery
	withUnits     *ShelfUnitQuery
	withPackages  *GoodsPackageQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ShelfQuery builder.
func (_q *ShelfQuery) Where(ps ...predicate.Shelf) *ShelfQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ShelfQuery) Limit(limit int) *ShelfQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ShelfQuery) Offset(offset int) *ShelfQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ShelfQuery) Unique(unique bool) *ShelfQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ShelfQuery) Order(o ...shelf.OrderOption) *ShelfQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryWarehouse chains the current query on the "warehouse" edge.
func (_q *ShelfQuery) QueryWarehouse() *WarehouseQuery {
	query := (&WarehouseClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(shelf.Table, shelf.FieldID, selector),
			sqlgraph.To(warehouse.Table, warehouse.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, shelf.WarehouseTable, shelf.WarehouseColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUnits chains the current query on the "units" edge.
func (_q *ShelfQuery) QueryUnits() *ShelfUnitQuery {
	query := (&ShelfUnitClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(shelf.Table, shelf.FieldID, selector),
			sqlgraph.To(shelfunit.Table, shelfunit.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, shelf.UnitsTable, shelf.UnitsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPackages chains the current query on the "packages" edge.
func (_q *ShelfQuery) QueryPackages() *GoodsPackageQuery {
	query := (&GoodsPackageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(shelf.Table, shelf.FieldID, selector),
			sqlgraph.To(goodspackage.Table, goodspackage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, shelf.PackagesTable, shelf.PackagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Shelf entity from the query.
// Returns a *NotFoundError when no Shelf was found.
func (_q *ShelfQuery) First(ctx context.Context) (*Shelf, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{shelf.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ShelfQuery) FirstX(ctx context.Context) *Shelf {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Shelf ID from the query.
// Returns a *NotFoundError when no Shelf ID was found.
func (_q *ShelfQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{shelf.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ShelfQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Shelf entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Shelf entity is found.
// Returns a *NotFoundError when no Shelf entities are found.
func (_q *ShelfQuery) Only(ctx context.Context) (*Shelf, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{shelf.Label}
	default:
		return nil, &NotSingularError{shelf.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ShelfQuery) OnlyX(ctx context.Context) *Shelf {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Shelf ID in the query.
// Returns a *NotSingularError when more than one Shelf ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ShelfQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{shelf.Label}
	default:
		err = &NotSingularError{shelf.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ShelfQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Shelves.
func (_q *ShelfQuery) All(ctx context.Context) ([]*Shelf, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Shelf, *ShelfQuery]()
	return withInterceptors[[]*Shelf](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ShelfQuery) AllX(ctx context.Context) []*Shelf {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Shelf IDs.
func (_q *ShelfQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(shelf.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ShelfQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ShelfQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ShelfQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ShelfQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ShelfQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ShelfQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ShelfQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ShelfQuery) Clone() *ShelfQuery {
	if _q == nil {
		return nil
	}
	return &ShelfQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]shelf.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.Shelf{}, _q.predicates...),
		withWarehouse: _q.withWarehouse.Clone(),
		withUnits:     _q.withUnits.Clone(),
		withPackages:  _q.withPackages.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithWarehouse tells the query-builder to eager-load the nodes that are connected to
// the "warehouse" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ShelfQuery) WithWarehouse(opts ...func(*WarehouseQuery)) *ShelfQuery {
	query := (&WarehouseClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWarehouse = query
	return _q
}

// WithUnits tells the query-builder to eager-load the nodes that are connected to
// the "units" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ShelfQuery) WithUnits(opts ...func(*ShelfUnitQuery)) *ShelfQuery {
	query := (&ShelfUnitClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUnits = query
	return _q
}

// WithPackages tells the query-builder to eager-load the nodes that are connected to
// the "packages" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ShelfQuery) WithPackages(opts ...func(*GoodsPackageQuery)) *ShelfQuery {
	query := (&GoodsPackageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPackages = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ShelfNumber int `json:"shelf_number,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Shelf.Query().
//		GroupBy(shelf.FieldShelfNumber).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ShelfQuery) GroupBy(field string, fields ...string) *ShelfGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ShelfGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = shelf.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ShelfNumber int `json:"shelf_number,omitempty"`
//	}
//
//	client.Shelf.Query().
//		Select(shelf.FieldShelfNumber).
//		Scan(ctx, &v)
func (_q *ShelfQuery) Select(fields ...string) *ShelfSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ShelfSelect{ShelfQuery: _q}
	sbuild.label = shelf.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ShelfSelect configured with the given aggregations.
func (_q *ShelfQuery) Aggregate(fns ...AggregateFunc) *ShelfSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ShelfQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !shelf.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ShelfQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Shelf, error) {
	var (
		nodes       = []*Shelf{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withWarehouse != nil,
			_q.withUnits != nil,
			_q.withPackages != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Shelf).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Shelf{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withWarehouse; query != nil {
		if err := _q.loadWarehouse(ctx, query, nodes, nil,
			func(n *Shelf, e *Warehouse) { n.Edges.Warehouse = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUnits; query != nil {
		if err := _q.loadUnits(ctx, query, nodes,
			func(n *Shelf) { n.Edges.Units = []*ShelfUnit{} },
			func(n *Shelf, e *ShelfUnit) { n.Edges.Units = append(n.Edges.Units, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPackages; query != nil {
		if err := _q.loadPackages(ctx, query, nodes,
			func(n *Shelf) { n.Edges.Packages = []*GoodsPackage{} },
			func(n *Shelf, e *GoodsPackage) { n.Edges.Packages = append(n.Edges.Packages, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ShelfQuery) loadWarehouse(ctx context.Context, query *WarehouseQuery, nodes []*Shelf, init func(*Shelf), assign func(*Shelf, *Warehouse)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Shelf)
	for i := range nodes {
		fk := nodes[i].WarehouseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(warehouse.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "warehouse_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ShelfQuery) loadUnits(ctx context.Context, query *ShelfUnitQuery, nodes []*Shelf, init func(*Shelf), assign func(*Shelf, *ShelfUnit)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Shelf)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ShelfUnit(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(shelf.UnitsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.shelf_units
		if fk == nil {
			return fmt.Errorf(`foreign-key "shelf_units" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "shelf_units" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ShelfQuery) loadPackages(ctx context.Context, query *GoodsPackageQuery, nodes []*Shelf, init func(*Shelf), assign func(*Shelf, *GoodsPackage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Shelf)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.GoodsPackage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(shelf.PackagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.shelf_packages
		if fk == nil {
			return fmt.Errorf(`foreign-key "shelf_packages" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "shelf_packages" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ShelfQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ShelfQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(shelf.Table, shelf.Columns, sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shelf.FieldID)
		for i := range fields {
			if fields[i] != shelf.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withWarehouse != nil {
			_spec.Node.AddColumnOnce(shelf.FieldWarehouseID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ShelfQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(shelf.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = shelf.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ShelfGroupBy is the group-by builder for Shelf entities.
type ShelfGroupBy struct {
	selector
	build *ShelfQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ShelfGroupBy) Aggregate(fns ...AggregateFunc) *ShelfGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ShelfGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShelfQuery, *ShelfGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ShelfGroupBy) sqlScan(ctx context.Context, root *ShelfQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ShelfSelect is the builder for selecting fields of Shelf entities.
type ShelfSelect struct {
	*ShelfQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ShelfSelect) Aggregate(fns ...AggregateFunc) *ShelfSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ShelfSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShelfQuery, *ShelfSelect](ctx, _s.ShelfQuery, _s, _s.inters, v)
}

func (_s *ShelfSelect) sqlScan(ctx context.Context, root *ShelfQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
