// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"warehouse/ent/predicate"
	"warehouse/ent/shelfunit"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShelfUnitDelete is the builder for deleting a ShelfUnit entity.
type ShelfUnitDelete struct {
	config
	hooks    []Hook
	mutation *ShelfUnitMutation
}

// Where appends a list predicates to the ShelfUnitDelete builder.
func (_d *ShelfUnitDelete) Where(ps ...predicate.ShelfUnit) *ShelfUnitDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ShelfUnitDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ShelfUnitDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ShelfUnitDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(shelfunit.Table, sqlgraph.NewFieldSpec(shelfunit.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ShelfUnitDeleteOne is the builder for deleting a single ShelfUnit entity.
type ShelfUnitDeleteOne struct {
	_d *ShelfUnitDelete
}

// Where appends a list predicates to the ShelfUnitDelete builder.
func (_d *ShelfUnitDeleteOne) Where(ps ...predicate.ShelfUnit) *ShelfUnitDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ShelfUnitDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shelfunit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ShelfUnitDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
