// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"warehouse/ent/store"
	"warehouse/ent/warehouse"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Warehouse is the model entity for the Warehouse schema.
type Warehouse struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 仓库名称
	Name string `json:"name,omitempty"`
	// 仓库编码
	Code string `json:"code,omitempty"`
	// 所属门店ID
	StoreID int `json:"store_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WarehouseQuery when eager-loading is set.
	Edges        WarehouseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WarehouseEdges holds the relations/edges for other nodes in the graph.
type WarehouseEdges struct {
	// 所属门店
	Store *Store `json:"store,omitempty"`
	// 该仓库下的所有货架
	Shelves []*Shelf `json:"shelves,omitempty"`
	// 该仓库下的路径规划记录
	PathPlans []*PathPlan `json:"path_plans,omitempty"`
	// 该仓库下的位置点（入口/出口/设备等）
	Landmarks []*Landmark `json:"landmarks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// StoreOrErr returns the Store value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WarehouseEdges) StoreOrErr() (*Store, error) {
	if e.Store != nil {
		return e.Store, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: store.Label}
	}
	return nil, &NotLoadedError{edge: "store"}
}

// ShelvesOrErr returns the Shelves value or an error if the edge
// was not loaded in eager-loading.
func (e WarehouseEdges) ShelvesOrErr() ([]*Shelf, error) {
	if e.loadedTypes[1] {
		return e.Shelves, nil
	}
	return nil, &NotLoadedError{edge: "shelves"}
}

// PathPlansOrErr returns the PathPlans value or an error if the edge
// was not loaded in eager-loading.
func (e WarehouseEdges) PathPlansOrErr() ([]*PathPlan, error) {
	if e.loadedTypes[2] {
		return e.PathPlans, nil
	}
	return nil, &NotLoadedError{edge: "path_plans"}
}

// LandmarksOrErr returns the Landmarks value or an error if the edge
// was not loaded in eager-loading.
func (e WarehouseEdges) LandmarksOrErr() ([]*Landmark, error) {
	if e.loadedTypes[3] {
		return e.Landmarks, nil
	}
	return nil, &NotLoadedError{edge: "landmarks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Warehouse) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case warehouse.FieldID, warehouse.FieldStoreID:
			values[i] = new(sql.NullInt64)
		case warehouse.FieldName, warehouse.FieldCode:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Warehouse fields.
func (_m *Warehouse) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case warehouse.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case warehouse.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case warehouse.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case warehouse.FieldStoreID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field store_id", values[i])
			} else if value.Valid {
				_m.StoreID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Warehouse.
// This includes values selected through modifiers, order, etc.
func (_m *Warehouse) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryStore queries the "store" edge of the Warehouse entity.
func (_m *Warehouse) QueryStore() *StoreQuery {
	return NewWarehouseClient(_m.config).QueryStore(_m)
}

// QueryShelves queries the "shelves" edge of the Warehouse entity.
func (_m *Warehouse) QueryShelves() *ShelfQuery {
	return NewWarehouseClient(_m.config).QueryShelves(_m)
}

// QueryPathPlans queries the "path_plans" edge of the Warehouse entity.
func (_m *Warehouse) QueryPathPlans() *PathPlanQuery {
	return NewWarehouseClient(_m.config).QueryPathPlans(_m)
}

// QueryLandmarks queries the "landmarks" edge of the Warehouse entity.
func (_m *Warehouse) QueryLandmarks() *LandmarkQuery {
	return NewWarehouseClient(_m.config).QueryLandmarks(_m)
}

// Update returns a builder for updating this Warehouse.
// Note that you need to call Warehouse.Unwrap() before calling this method if this Warehouse
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Warehouse) Update() *WarehouseUpdateOne {
	return NewWarehouseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Warehouse entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Warehouse) Unwrap() *Warehouse {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Warehouse is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Warehouse) String() string {
	var builder strings.Builder
	builder.WriteString("Warehouse(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("store_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StoreID))
	builder.WriteByte(')')
	return builder.String()
}

// Warehouses is a parsable slice of Warehouse.
type Warehouses []*Warehouse
