// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"warehouse/ent/landmark"
	"warehouse/ent/pathplan"
	"warehouse/ent/shelf"
	"warehouse/ent/store"
	"warehouse/ent/warehouse"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WarehouseCreate is the builder for creating a Warehouse entity.
type WarehouseCreate struct {
	config
	mutation *WarehouseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *WarehouseCreate) SetName(v string) *WarehouseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *WarehouseCreate) SetNillableName(v *string) *WarehouseCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *WarehouseCreate) SetCode(v string) *WarehouseCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *WarehouseCreate) SetNillableCode(v *string) *WarehouseCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetStoreID sets the "store_id" field.
func (_c *WarehouseCreate) SetStoreID(v int) *WarehouseCreate {
	_c.mutation.SetStoreID(v)
	return _c
}

// SetStore sets the "store" edge to the Store entity.
func (_c *WarehouseCreate) SetStore(v *Store) *WarehouseCreate {
	return _c.SetStoreID(v.ID)
}

// AddShelfIDs adds the "shelves" edge to the Shelf entity by IDs.
func (_c *WarehouseCreate) AddShelfIDs(ids ...int) *WarehouseCreate {
	_c.mutation.AddShelfIDs(ids...)
	return _c
}

// AddShelves adds the "shelves" edges to the Shelf entity.
func (_c *WarehouseCreate) AddShelves(v ...*Shelf) *WarehouseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddShelfIDs(ids...)
}

// AddPathPlanIDs adds the "path_plans" edge to the PathPlan entity by IDs.
func (_c *WarehouseCreate) AddPathPlanIDs(ids ...int) *WarehouseCreate {
	_c.mutation.AddPathPlanIDs(ids...)
	return _c
}

// AddPathPlans adds the "path_plans" edges to the PathPlan entity.
func (_c *WarehouseCreate) AddPathPlans(v ...*PathPlan) *WarehouseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPathPlanIDs(ids...)
}

// AddLandmarkIDs adds the "landmarks" edge to the Landmark entity by IDs.
func (_c *WarehouseCreate) AddLandmarkIDs(ids ...int) *WarehouseCreate {
	_c.mutation.AddLandmarkIDs(ids...)
	return _c
}

// AddLandmarks adds the "landmarks" edges to the Landmark entity.
func (_c *WarehouseCreate) AddLandmarks(v ...*Landmark) *WarehouseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLandmarkIDs(ids...)
}

// Mutation returns the WarehouseMutation object of the builder.
func (_c *WarehouseCreate) Mutation() *WarehouseMutation {
	return _c.mutation
}

// Save creates the Warehouse in the database.
func (_c *WarehouseCreate) Save(ctx context.Context) (*Warehouse, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WarehouseCreate) SaveX(ctx context.Context) *Warehouse {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WarehouseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WarehouseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WarehouseCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := warehouse.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Code(); !ok {
		v := warehouse.DefaultCode
		_c.mutation.SetCode(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WarehouseCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Warehouse.name"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Warehouse.code"`)}
	}
	if _, ok := _c.mutation.StoreID(); !ok {
		return &ValidationError{Name: "store_id", err: errors.New(`ent: missing required field "Warehouse.store_id"`)}
	}
	if len(_c.mutation.StoreIDs()) == 0 {
		return &ValidationError{Name: "store", err: errors.New(`ent: missing required edge "Warehouse.store"`)}
	}
	return nil
}

func (_c *WarehouseCreate) sqlSave(ctx context.Context) (*Warehouse, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WarehouseCreate) createSpec() (*Warehouse, *sqlgraph.CreateSpec) {
	var (
		_node = &Warehouse{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(warehouse.Table, sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(warehouse.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(warehouse.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if nodes := _c.mutation.StoreIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   warehouse.StoreTable,
			Columns: []string{warehouse.StoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StoreID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ShelvesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.ShelvesTable,
			Columns: []string{warehouse.ShelvesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shelf.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PathPlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.PathPlansTable,
			Columns: []string{warehouse.PathPlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pathplan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LandmarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   warehouse.LandmarksTable,
			Columns: []string{warehouse.LandmarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(landmark.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Warehouse.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WarehouseUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *WarehouseCreate) OnConflict(opts ...sql.ConflictOption) *WarehouseUpsertOne {
	_c.conflict = opts
	return &WarehouseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Warehouse.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WarehouseCreate) OnConflictColumns(columns ...string) *WarehouseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WarehouseUpsertOne{
		create: _c,
	}
}

type (
	// WarehouseUpsertOne is the builder for "upsert"-ing
	//  one Warehouse node.
	WarehouseUpsertOne struct {
		create *WarehouseCreate
	}

	// WarehouseUpsert is the "OnConflict" setter.
	WarehouseUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *WarehouseUpsert) SetName(v string) *WarehouseUpsert {
	u.Set(warehouse.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WarehouseUpsert) UpdateName() *WarehouseUpsert {
	u.SetExcluded(warehouse.FieldName)
	return u
}

// SetCode sets the "code" field.
func (u *WarehouseUpsert) SetCode(v string) *WarehouseUpsert {
	u.Set(warehouse.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *WarehouseUpsert) UpdateCode() *WarehouseUpsert {
	u.SetExcluded(warehouse.FieldCode)
	return u
}

// SetStoreID sets the "store_id" field.
func (u *WarehouseUpsert) SetStoreID(v int) *WarehouseUpsert {
	u.Set(warehouse.FieldStoreID, v)
	return u
}

// UpdateStoreID sets the "store_id" field to the value that was provided on create.
func (u *WarehouseUpsert) UpdateStoreID() *WarehouseUpsert {
	u.SetExcluded(warehouse.FieldStoreID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Warehouse.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WarehouseUpsertOne) UpdateNewValues() *WarehouseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Warehouse.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WarehouseUpsertOne) Ignore() *WarehouseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WarehouseUpsertOne) DoNothing() *WarehouseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WarehouseCreate.OnConflict
// documentation for more info.
func (u *WarehouseUpsertOne) Update(set func(*WarehouseUpsert)) *WarehouseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WarehouseUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *WarehouseUpsertOne) SetName(v string) *WarehouseUpsertOne {
	return u.Update(func(s *WarehouseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WarehouseUpsertOne) UpdateName() *WarehouseUpsertOne {
	return u.Update(func(s *WarehouseUpsert) {
		s.UpdateName()
	})
}

// SetCode sets the "code" field.
func (u *WarehouseUpsertOne) SetCode(v string) *WarehouseUpsertOne {
	return u.Update(func(s *WarehouseUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *WarehouseUpsertOne) UpdateCode() *WarehouseUpsertOne {
	return u.Update(func(s *WarehouseUpsert) {
		s.UpdateCode()
	})
}

// SetStoreID sets the "store_id" field.
func (u *WarehouseUpsertOne) SetStoreID(v int) *WarehouseUpsertOne {
	return u.Update(func(s *WarehouseUpsert) {
		s.SetStoreID(v)
	})
}

// UpdateStoreID sets the "store_id" field to the value that was provided on create.
func (u *WarehouseUpsertOne) UpdateStoreID() *WarehouseUpsertOne {
	return u.Update(func(s *WarehouseUpsert) {
		s.UpdateStoreID()
	})
}

// Exec executes the query.
func (u *WarehouseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WarehouseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WarehouseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WarehouseUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WarehouseUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WarehouseCreateBulk is the builder for creating many Warehouse entities in bulk.
type WarehouseCreateBulk struct {
	config
	err      error
	builders []*WarehouseCreate
	conflict []sql.ConflictOption
}

// Save creates the Warehouse entities in the database.
func (_c *WarehouseCreateBulk) Save(ctx context.Context) ([]*Warehouse, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Warehouse, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WarehouseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WarehouseCreateBulk) SaveX(ctx context.Context) []*Warehouse {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WarehouseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WarehouseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Warehouse.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WarehouseUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *WarehouseCreateBulk) OnConflict(opts ...sql.ConflictOption) *WarehouseUpsertBulk {
	_c.conflict = opts
	return &WarehouseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Warehouse.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WarehouseCreateBulk) OnConflictColumns(columns ...string) *WarehouseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WarehouseUpsertBulk{
		create: _c,
	}
}

// WarehouseUpsertBulk is the builder for "upsert"-ing
// a bulk of Warehouse nodes.
type WarehouseUpsertBulk struct {
	create *WarehouseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Warehouse.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WarehouseUpsertBulk) UpdateNewValues() *WarehouseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Warehouse.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WarehouseUpsertBulk) Ignore() *WarehouseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WarehouseUpsertBulk) DoNothing() *WarehouseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WarehouseCreateBulk.OnConflict
// documentation for more info.
func (u *WarehouseUpsertBulk) Update(set func(*WarehouseUpsert)) *WarehouseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WarehouseUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *WarehouseUpsertBulk) SetName(v string) *WarehouseUpsertBulk {
	return u.Update(func(s *WarehouseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WarehouseUpsertBulk) UpdateName() *WarehouseUpsertBulk {
	return u.Update(func(s *WarehouseUpsert) {
		s.UpdateName()
	})
}

// SetCode sets the "code" field.
func (u *WarehouseUpsertBulk) SetCode(v string) *WarehouseUpsertBulk {
	return u.Update(func(s *WarehouseUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *WarehouseUpsertBulk) UpdateCode() *WarehouseUpsertBulk {
	return u.Update(func(s *WarehouseUpsert) {
		s.UpdateCode()
	})
}

// SetStoreID sets the "store_id" field.
func (u *WarehouseUpsertBulk) SetStoreID(v int) *WarehouseUpsertBulk {
	return u.Update(func(s *WarehouseUpsert) {
		s.SetStoreID(v)
	})
}

// UpdateStoreID sets the "store_id" field to the value that was provided on create.
func (u *WarehouseUpsertBulk) UpdateStoreID() *WarehouseUpsertBulk {
	return u.Update(func(s *WarehouseUpsert) {
		s.UpdateStoreID()
	})
}

// Exec executes the query.
func (u *WarehouseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WarehouseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WarehouseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WarehouseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
